// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldExperienceLevel holds the string denoting the experience_level field in the database.
	FieldExperienceLevel = "experience_level"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldRatingCount holds the string denoting the rating_count field in the database.
	FieldRatingCount = "rating_count"
	// FieldDrivingRating holds the string denoting the driving_rating field in the database.
	FieldDrivingRating = "driving_rating"
	// FieldProfilePictureURL holds the string denoting the profile_picture_url field in the database.
	FieldProfilePictureURL = "profile_picture_url"
	// FieldIsVerified holds the string denoting the is_verified field in the database.
	FieldIsVerified = "is_verified"
	// FieldVerifiedID holds the string denoting the verified_id field in the database.
	FieldVerifiedID = "verified_id"
	// FieldConfirmedEmail holds the string denoting the confirmed_email field in the database.
	FieldConfirmedEmail = "confirmed_email"
	// FieldConfirmedPhone holds the string denoting the confirmed_phone field in the database.
	FieldConfirmedPhone = "confirmed_phone"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldPreferences holds the string denoting the preferences field in the database.
	FieldPreferences = "preferences"
	// FieldMembershipType holds the string denoting the membership_type field in the database.
	FieldMembershipType = "membership_type"
	// FieldPublishedRides holds the string denoting the published_rides field in the database.
	FieldPublishedRides = "published_rides"
	// FieldCompletedRides holds the string denoting the completed_rides field in the database.
	FieldCompletedRides = "completed_rides"
	// FieldNeverCancels holds the string denoting the never_cancels field in the database.
	FieldNeverCancels = "never_cancels"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRides holds the string denoting the rides edge name in mutations.
	EdgeRides = "rides"
	// EdgeBookings holds the string denoting the bookings edge name in mutations.
	EdgeBookings = "bookings"
	// EdgeVehicles holds the string denoting the vehicles edge name in mutations.
	EdgeVehicles = "vehicles"
	// Table holds the table name of the user in the database.
	Table = "users"
	// RidesTable is the table that holds the rides relation/edge.
	RidesTable = "rides"
	// RidesInverseTable is the table name for the Ride entity.
	// It exists in this package in order to avoid circular dependency with the "ride" package.
	RidesInverseTable = "rides"
	// RidesColumn is the table column denoting the rides relation/edge.
	RidesColumn = "driver_id"
	// BookingsTable is the table that holds the bookings relation/edge.
	BookingsTable = "bookings"
	// BookingsInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookingsInverseTable = "bookings"
	// BookingsColumn is the table column denoting the bookings relation/edge.
	BookingsColumn = "passenger_id"
	// VehiclesTable is the table that holds the vehicles relation/edge.
	VehiclesTable = "vehicles"
	// VehiclesInverseTable is the table name for the Vehicle entity.
	// It exists in this package in order to avoid circular dependency with the "vehicle" package.
	VehiclesInverseTable = "vehicles"
	// VehiclesColumn is the table column denoting the vehicles relation/edge.
	VehiclesColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPhone,
	FieldPasswordHash,
	FieldAge,
	FieldExperienceLevel,
	FieldRating,
	FieldRatingCount,
	FieldDrivingRating,
	FieldProfilePictureURL,
	FieldIsVerified,
	FieldVerifiedID,
	FieldConfirmedEmail,
	FieldConfirmedPhone,
	FieldBio,
	FieldPreferences,
	FieldMembershipType,
	FieldPublishedRides,
	FieldCompletedRides,
	FieldNeverCancels,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator func(int) error
	// DefaultExperienceLevel holds the default value on creation for the "experience_level" field.
	DefaultExperienceLevel string
	// DefaultRating holds the default value on creation for the "rating" field.
	DefaultRating float64
	// RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	RatingValidator func(float64) error
	// DefaultRatingCount holds the default value on creation for the "rating_count" field.
	DefaultRatingCount int
	// RatingCountValidator is a validator for the "rating_count" field. It is called by the builders before save.
	RatingCountValidator func(int) error
	// DefaultIsVerified holds the default value on creation for the "is_verified" field.
	DefaultIsVerified bool
	// DefaultVerifiedID holds the default value on creation for the "verified_id" field.
	DefaultVerifiedID bool
	// DefaultConfirmedEmail holds the default value on creation for the "confirmed_email" field.
	DefaultConfirmedEmail bool
	// DefaultConfirmedPhone holds the default value on creation for the "confirmed_phone" field.
	DefaultConfirmedPhone bool
	// DefaultMembershipType holds the default value on creation for the "membership_type" field.
	DefaultMembershipType string
	// DefaultPublishedRides holds the default value on creation for the "published_rides" field.
	DefaultPublishedRides int
	// PublishedRidesValidator is a validator for the "published_rides" field. It is called by the builders before save.
	PublishedRidesValidator func(int) error
	// DefaultCompletedRides holds the default value on creation for the "completed_rides" field.
	DefaultCompletedRides int
	// CompletedRidesValidator is a validator for the "completed_rides" field. It is called by the builders before save.
	CompletedRidesValidator func(int) error
	// DefaultNeverCancels holds the default value on creation for the "never_cancels" field.
	DefaultNeverCancels bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByAge orders the results by the age field.
func ByAge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAge, opts...).ToFunc()
}

// ByExperienceLevel orders the results by the experience_level field.
func ByExperienceLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExperienceLevel, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByRatingCount orders the results by the rating_count field.
func ByRatingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatingCount, opts...).ToFunc()
}

// ByDrivingRating orders the results by the driving_rating field.
func ByDrivingRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDrivingRating, opts...).ToFunc()
}

// ByProfilePictureURL orders the results by the profile_picture_url field.
func ByProfilePictureURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfilePictureURL, opts...).ToFunc()
}

// ByIsVerified orders the results by the is_verified field.
func ByIsVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsVerified, opts...).ToFunc()
}

// ByVerifiedID orders the results by the verified_id field.
func ByVerifiedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedID, opts...).ToFunc()
}

// ByConfirmedEmail orders the results by the confirmed_email field.
func ByConfirmedEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedEmail, opts...).ToFunc()
}

// ByConfirmedPhone orders the results by the confirmed_phone field.
func ByConfirmedPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedPhone, opts...).ToFunc()
}

// ByBio orders the results by the bio field.
func ByBio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBio, opts...).ToFunc()
}

// ByMembershipType orders the results by the membership_type field.
func ByMembershipType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMembershipType, opts...).ToFunc()
}

// ByPublishedRides orders the results by the published_rides field.
func ByPublishedRides(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedRides, opts...).ToFunc()
}

// ByCompletedRides orders the results by the completed_rides field.
func ByCompletedRides(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedRides, opts...).ToFunc()
}

// ByNeverCancels orders the results by the never_cancels field.
func ByNeverCancels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNeverCancels, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRidesCount orders the results by rides count.
func ByRidesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRidesStep(), opts...)
	}
}

// ByRides orders the results by rides terms.
func ByRides(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRidesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBookingsCount orders the results by bookings count.
func ByBookingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBookingsStep(), opts...)
	}
}

// ByBookings orders the results by bookings terms.
func ByBookings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBookingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVehiclesCount orders the results by vehicles count.
func ByVehiclesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVehiclesStep(), opts...)
	}
}

// ByVehicles orders the results by vehicles terms.
func ByVehicles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVehiclesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRidesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RidesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RidesTable, RidesColumn),
	)
}
func newBookingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BookingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BookingsTable, BookingsColumn),
	)
}
func newVehiclesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VehiclesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VehiclesTable, VehiclesColumn),
	)
}
