// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/slowtyper/poolie/backend/ent/booking"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/user"
)

// Booking is the model entity for the Booking schema.
type Booking struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RideID holds the value of the "ride_id" field.
	RideID string `json:"ride_id,omitempty"`
	// PassengerID holds the value of the "passenger_id" field.
	PassengerID string `json:"passenger_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PassengerCount holds the value of the "passenger_count" field.
	PassengerCount int `json:"passenger_count,omitempty"`
	// TotalPriceAmount holds the value of the "total_price_amount" field.
	TotalPriceAmount int64 `json:"total_price_amount,omitempty"`
	// TotalPriceCurrency holds the value of the "total_price_currency" field.
	TotalPriceCurrency string `json:"total_price_currency,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// DriverResponseMessage holds the value of the "driver_response_message" field.
	DriverResponseMessage string `json:"driver_response_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// RespondedAt holds the value of the "responded_at" field.
	RespondedAt *time.Time `json:"responded_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BookingQuery when eager-loading is set.
	Edges        BookingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BookingEdges holds the relations/edges for other nodes in the graph.
type BookingEdges struct {
	// Ride holds the value of the ride edge.
	Ride *Ride `json:"ride,omitempty"`
	// Passenger holds the value of the passenger edge.
	Passenger *User `json:"passenger,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RideOrErr returns the Ride value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookingEdges) RideOrErr() (*Ride, error) {
	if e.Ride != nil {
		return e.Ride, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ride.Label}
	}
	return nil, &NotLoadedError{edge: "ride"}
}

// PassengerOrErr returns the Passenger value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookingEdges) PassengerOrErr() (*User, error) {
	if e.Passenger != nil {
		return e.Passenger, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "passenger"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Booking) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case booking.FieldPassengerCount, booking.FieldTotalPriceAmount:
			values[i] = new(sql.NullInt64)
		case booking.FieldID, booking.FieldRideID, booking.FieldPassengerID, booking.FieldStatus, booking.FieldTotalPriceCurrency, booking.FieldMessage, booking.FieldDriverResponseMessage:
			values[i] = new(sql.NullString)
		case booking.FieldCreatedAt, booking.FieldRespondedAt, booking.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Booking fields.
func (_m *Booking) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case booking.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case booking.FieldRideID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ride_id", values[i])
			} else if value.Valid {
				_m.RideID = value.String
			}
		case booking.FieldPassengerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passenger_id", values[i])
			} else if value.Valid {
				_m.PassengerID = value.String
			}
		case booking.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case booking.FieldPassengerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field passenger_count", values[i])
			} else if value.Valid {
				_m.PassengerCount = int(value.Int64)
			}
		case booking.FieldTotalPriceAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_price_amount", values[i])
			} else if value.Valid {
				_m.TotalPriceAmount = value.Int64
			}
		case booking.FieldTotalPriceCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field total_price_currency", values[i])
			} else if value.Valid {
				_m.TotalPriceCurrency = value.String
			}
		case booking.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case booking.FieldDriverResponseMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field driver_response_message", values[i])
			} else if value.Valid {
				_m.DriverResponseMessage = value.String
			}
		case booking.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case booking.FieldRespondedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field responded_at", values[i])
			} else if value.Valid {
				_m.RespondedAt = new(time.Time)
				*_m.RespondedAt = value.Time
			}
		case booking.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Booking.
// This includes values selected through modifiers, order, etc.
func (_m *Booking) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRide queries the "ride" edge of the Booking entity.
func (_m *Booking) QueryRide() *RideQuery {
	return NewBookingClient(_m.config).QueryRide(_m)
}

// QueryPassenger queries the "passenger" edge of the Booking entity.
func (_m *Booking) QueryPassenger() *UserQuery {
	return NewBookingClient(_m.config).QueryPassenger(_m)
}

// Update returns a builder for updating this Booking.
// Note that you need to call Booking.Unwrap() before calling this method if this Booking
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Booking) Update() *BookingUpdateOne {
	return NewBookingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Booking entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Booking) Unwrap() *Booking {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Booking is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Booking) String() string {
	var builder strings.Builder
	builder.WriteString("Booking(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ride_id=")
	builder.WriteString(_m.RideID)
	builder.WriteString(", ")
	builder.WriteString("passenger_id=")
	builder.WriteString(_m.PassengerID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("passenger_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PassengerCount))
	builder.WriteString(", ")
	builder.WriteString("total_price_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPriceAmount))
	builder.WriteString(", ")
	builder.WriteString("total_price_currency=")
	builder.WriteString(_m.TotalPriceCurrency)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("driver_response_message=")
	builder.WriteString(_m.DriverResponseMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RespondedAt; v != nil {
		builder.WriteString("responded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Bookings is a parsable slice of Booking.
type Bookings []*Booking
