// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/slowtyper/poolie/backend/ent/booking"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/user"
	"github.com/slowtyper/poolie/backend/ent/vehicle"
)

// RideCreate is the builder for creating a Ride entity.
type RideCreate struct {
	config
	mutation *RideMutation
	hooks    []Hook
}

// SetDriverID sets the "driver_id" field.
func (_c *RideCreate) SetDriverID(v string) *RideCreate {
	_c.mutation.SetDriverID(v)
	return _c
}

// SetVehicleID sets the "vehicle_id" field.
func (_c *RideCreate) SetVehicleID(v string) *RideCreate {
	_c.mutation.SetVehicleID(v)
	return _c
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_c *RideCreate) SetNillableVehicleID(v *string) *RideCreate {
	if v != nil {
		_c.SetVehicleID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *RideCreate) SetType(v string) *RideCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *RideCreate) SetNillableType(v *string) *RideCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetRideType sets the "ride_type" field.
func (_c *RideCreate) SetRideType(v string) *RideCreate {
	_c.mutation.SetRideType(v)
	return _c
}

// SetNillableRideType sets the "ride_type" field if the given value is not nil.
func (_c *RideCreate) SetNillableRideType(v *string) *RideCreate {
	if v != nil {
		_c.SetRideType(*v)
	}
	return _c
}

// SetRecurrence sets the "recurrence" field.
func (_c *RideCreate) SetRecurrence(v map[string]interface{}) *RideCreate {
	_c.mutation.SetRecurrence(v)
	return _c
}

// SetDepartureTime sets the "departure_time" field.
func (_c *RideCreate) SetDepartureTime(v time.Time) *RideCreate {
	_c.mutation.SetDepartureTime(v)
	return _c
}

// SetArrivalTime sets the "arrival_time" field.
func (_c *RideCreate) SetArrivalTime(v time.Time) *RideCreate {
	_c.mutation.SetArrivalTime(v)
	return _c
}

// SetNillableArrivalTime sets the "arrival_time" field if the given value is not nil.
func (_c *RideCreate) SetNillableArrivalTime(v *time.Time) *RideCreate {
	if v != nil {
		_c.SetArrivalTime(*v)
	}
	return _c
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_c *RideCreate) SetDurationMinutes(v int) *RideCreate {
	_c.mutation.SetDurationMinutes(v)
	return _c
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_c *RideCreate) SetNillableDurationMinutes(v *int) *RideCreate {
	if v != nil {
		_c.SetDurationMinutes(*v)
	}
	return _c
}

// SetOriginCity sets the "origin_city" field.
func (_c *RideCreate) SetOriginCity(v string) *RideCreate {
	_c.mutation.SetOriginCity(v)
	return _c
}

// SetOriginAddress sets the "origin_address" field.
func (_c *RideCreate) SetOriginAddress(v string) *RideCreate {
	_c.mutation.SetOriginAddress(v)
	return _c
}

// SetOriginLocationPoint sets the "origin_location_point" field.
func (_c *RideCreate) SetOriginLocationPoint(v string) *RideCreate {
	_c.mutation.SetOriginLocationPoint(v)
	return _c
}

// SetNillableOriginLocationPoint sets the "origin_location_point" field if the given value is not nil.
func (_c *RideCreate) SetNillableOriginLocationPoint(v *string) *RideCreate {
	if v != nil {
		_c.SetOriginLocationPoint(*v)
	}
	return _c
}

// SetDestinationCity sets the "destination_city" field.
func (_c *RideCreate) SetDestinationCity(v string) *RideCreate {
	_c.mutation.SetDestinationCity(v)
	return _c
}

// SetDestinationAddress sets the "destination_address" field.
func (_c *RideCreate) SetDestinationAddress(v string) *RideCreate {
	_c.mutation.SetDestinationAddress(v)
	return _c
}

// SetDestinationLocationPoint sets the "destination_location_point" field.
func (_c *RideCreate) SetDestinationLocationPoint(v string) *RideCreate {
	_c.mutation.SetDestinationLocationPoint(v)
	return _c
}

// SetNillableDestinationLocationPoint sets the "destination_location_point" field if the given value is not nil.
func (_c *RideCreate) SetNillableDestinationLocationPoint(v *string) *RideCreate {
	if v != nil {
		_c.SetDestinationLocationPoint(*v)
	}
	return _c
}

// SetPriceAmount sets the "price_amount" field.
func (_c *RideCreate) SetPriceAmount(v int64) *RideCreate {
	_c.mutation.SetPriceAmount(v)
	return _c
}

// SetPriceCurrency sets the "price_currency" field.
func (_c *RideCreate) SetPriceCurrency(v string) *RideCreate {
	_c.mutation.SetPriceCurrency(v)
	return _c
}

// SetNillablePriceCurrency sets the "price_currency" field if the given value is not nil.
func (_c *RideCreate) SetNillablePriceCurrency(v *string) *RideCreate {
	if v != nil {
		_c.SetPriceCurrency(*v)
	}
	return _c
}

// SetAvailableSeats sets the "available_seats" field.
func (_c *RideCreate) SetAvailableSeats(v int) *RideCreate {
	_c.mutation.SetAvailableSeats(v)
	return _c
}

// SetTotalSeats sets the "total_seats" field.
func (_c *RideCreate) SetTotalSeats(v int) *RideCreate {
	_c.mutation.SetTotalSeats(v)
	return _c
}

// SetAmenities sets the "amenities" field.
func (_c *RideCreate) SetAmenities(v map[string]interface{}) *RideCreate {
	_c.mutation.SetAmenities(v)
	return _c
}

// SetStops sets the "stops" field.
func (_c *RideCreate) SetStops(v []interface{}) *RideCreate {
	_c.mutation.SetStops(v)
	return _c
}

// SetInstantConfirmation sets the "instant_confirmation" field.
func (_c *RideCreate) SetInstantConfirmation(v bool) *RideCreate {
	_c.mutation.SetInstantConfirmation(v)
	return _c
}

// SetNillableInstantConfirmation sets the "instant_confirmation" field if the given value is not nil.
func (_c *RideCreate) SetNillableInstantConfirmation(v *bool) *RideCreate {
	if v != nil {
		_c.SetInstantConfirmation(*v)
	}
	return _c
}

// SetCancellationPolicy sets the "cancellation_policy" field.
func (_c *RideCreate) SetCancellationPolicy(v string) *RideCreate {
	_c.mutation.SetCancellationPolicy(v)
	return _c
}

// SetNillableCancellationPolicy sets the "cancellation_policy" field if the given value is not nil.
func (_c *RideCreate) SetNillableCancellationPolicy(v *string) *RideCreate {
	if v != nil {
		_c.SetCancellationPolicy(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *RideCreate) SetDescription(v string) *RideCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RideCreate) SetNillableDescription(v *string) *RideCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RideCreate) SetStatus(v string) *RideCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RideCreate) SetNillableStatus(v *string) *RideCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RideCreate) SetCreatedAt(v time.Time) *RideCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RideCreate) SetNillableCreatedAt(v *time.Time) *RideCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RideCreate) SetUpdatedAt(v time.Time) *RideCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RideCreate) SetNillableUpdatedAt(v *time.Time) *RideCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RideCreate) SetID(v string) *RideCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDriver sets the "driver" edge to the User entity.
func (_c *RideCreate) SetDriver(v *User) *RideCreate {
	return _c.SetDriverID(v.ID)
}

// SetVehicle sets the "vehicle" edge to the Vehicle entity.
func (_c *RideCreate) SetVehicle(v *Vehicle) *RideCreate {
	return _c.SetVehicleID(v.ID)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_c *RideCreate) AddBookingIDs(ids ...string) *RideCreate {
	_c.mutation.AddBookingIDs(ids...)
	return _c
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_c *RideCreate) AddBookings(v ...*Booking) *RideCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBookingIDs(ids...)
}

// Mutation returns the RideMutation object of the builder.
func (_c *RideCreate) Mutation() *RideMutation {
	return _c.mutation
}

// Save creates the Ride in the database.
func (_c *RideCreate) Save(ctx context.Context) (*Ride, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RideCreate) SaveX(ctx context.Context) *Ride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RideCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := ride.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.RideType(); !ok {
		v := ride.DefaultRideType
		_c.mutation.SetRideType(v)
	}
	if _, ok := _c.mutation.PriceCurrency(); !ok {
		v := ride.DefaultPriceCurrency
		_c.mutation.SetPriceCurrency(v)
	}
	if _, ok := _c.mutation.InstantConfirmation(); !ok {
		v := ride.DefaultInstantConfirmation
		_c.mutation.SetInstantConfirmation(v)
	}
	if _, ok := _c.mutation.CancellationPolicy(); !ok {
		v := ride.DefaultCancellationPolicy
		_c.mutation.SetCancellationPolicy(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ride.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ride.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ride.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RideCreate) check() error {
	if _, ok := _c.mutation.DriverID(); !ok {
		return &ValidationError{Name: "driver_id", err: errors.New(`ent: missing required field "Ride.driver_id"`)}
	}
	if v, ok := _c.mutation.DriverID(); ok {
		if err := ride.DriverIDValidator(v); err != nil {
			return &ValidationError{Name: "driver_id", err: fmt.Errorf(`ent: validator failed for field "Ride.driver_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Ride.type"`)}
	}
	if _, ok := _c.mutation.RideType(); !ok {
		return &ValidationError{Name: "ride_type", err: errors.New(`ent: missing required field "Ride.ride_type"`)}
	}
	if _, ok := _c.mutation.DepartureTime(); !ok {
		return &ValidationError{Name: "departure_time", err: errors.New(`ent: missing required field "Ride.departure_time"`)}
	}
	if v, ok := _c.mutation.DurationMinutes(); ok {
		if err := ride.DurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "duration_minutes", err: fmt.Errorf(`ent: validator failed for field "Ride.duration_minutes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginCity(); !ok {
		return &ValidationError{Name: "origin_city", err: errors.New(`ent: missing required field "Ride.origin_city"`)}
	}
	if v, ok := _c.mutation.OriginCity(); ok {
		if err := ride.OriginCityValidator(v); err != nil {
			return &ValidationError{Name: "origin_city", err: fmt.Errorf(`ent: validator failed for field "Ride.origin_city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginAddress(); !ok {
		return &ValidationError{Name: "origin_address", err: errors.New(`ent: missing required field "Ride.origin_address"`)}
	}
	if v, ok := _c.mutation.OriginAddress(); ok {
		if err := ride.OriginAddressValidator(v); err != nil {
			return &ValidationError{Name: "origin_address", err: fmt.Errorf(`ent: validator failed for field "Ride.origin_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DestinationCity(); !ok {
		return &ValidationError{Name: "destination_city", err: errors.New(`ent: missing required field "Ride.destination_city"`)}
	}
	if v, ok := _c.mutation.DestinationCity(); ok {
		if err := ride.DestinationCityValidator(v); err != nil {
			return &ValidationError{Name: "destination_city", err: fmt.Errorf(`ent: validator failed for field "Ride.destination_city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DestinationAddress(); !ok {
		return &ValidationError{Name: "destination_address", err: errors.New(`ent: missing required field "Ride.destination_address"`)}
	}
	if v, ok := _c.mutation.DestinationAddress(); ok {
		if err := ride.DestinationAddressValidator(v); err != nil {
			return &ValidationError{Name: "destination_address", err: fmt.Errorf(`ent: validator failed for field "Ride.destination_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceAmount(); !ok {
		return &ValidationError{Name: "price_amount", err: errors.New(`ent: missing required field "Ride.price_amount"`)}
	}
	if v, ok := _c.mutation.PriceAmount(); ok {
		if err := ride.PriceAmountValidator(v); err != nil {
			return &ValidationError{Name: "price_amount", err: fmt.Errorf(`ent: validator failed for field "Ride.price_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceCurrency(); !ok {
		return &ValidationError{Name: "price_currency", err: errors.New(`ent: missing required field "Ride.price_currency"`)}
	}
	if _, ok := _c.mutation.AvailableSeats(); !ok {
		return &ValidationError{Name: "available_seats", err: errors.New(`ent: missing required field "Ride.available_seats"`)}
	}
	if v, ok := _c.mutation.AvailableSeats(); ok {
		if err := ride.AvailableSeatsValidator(v); err != nil {
			return &ValidationError{Name: "available_seats", err: fmt.Errorf(`ent: validator failed for field "Ride.available_seats": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalSeats(); !ok {
		return &ValidationError{Name: "total_seats", err: errors.New(`ent: missing required field "Ride.total_seats"`)}
	}
	if v, ok := _c.mutation.TotalSeats(); ok {
		if err := ride.TotalSeatsValidator(v); err != nil {
			return &ValidationError{Name: "total_seats", err: fmt.Errorf(`ent: validator failed for field "Ride.total_seats": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstantConfirmation(); !ok {
		return &ValidationError{Name: "instant_confirmation", err: errors.New(`ent: missing required field "Ride.instant_confirmation"`)}
	}
	if _, ok := _c.mutation.CancellationPolicy(); !ok {
		return &ValidationError{Name: "cancellation_policy", err: errors.New(`ent: missing required field "Ride.cancellation_policy"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Ride.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ride.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ride.updated_at"`)}
	}
	if len(_c.mutation.DriverIDs()) == 0 {
		return &ValidationError{Name: "driver", err: errors.New(`ent: missing required edge "Ride.driver"`)}
	}
	return nil
}

func (_c *RideCreate) sqlSave(ctx context.Context) (*Ride, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Ride.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RideCreate) createSpec() (*Ride, *sqlgraph.CreateSpec) {
	var (
		_node = &Ride{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ride.Table, sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(ride.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.RideType(); ok {
		_spec.SetField(ride.FieldRideType, field.TypeString, value)
		_node.RideType = value
	}
	if value, ok := _c.mutation.Recurrence(); ok {
		_spec.SetField(ride.FieldRecurrence, field.TypeJSON, value)
		_node.Recurrence = value
	}
	if value, ok := _c.mutation.DepartureTime(); ok {
		_spec.SetField(ride.FieldDepartureTime, field.TypeTime, value)
		_node.DepartureTime = value
	}
	if value, ok := _c.mutation.ArrivalTime(); ok {
		_spec.SetField(ride.FieldArrivalTime, field.TypeTime, value)
		_node.ArrivalTime = &value
	}
	if value, ok := _c.mutation.DurationMinutes(); ok {
		_spec.SetField(ride.FieldDurationMinutes, field.TypeInt, value)
		_node.DurationMinutes = &value
	}
	if value, ok := _c.mutation.OriginCity(); ok {
		_spec.SetField(ride.FieldOriginCity, field.TypeString, value)
		_node.OriginCity = value
	}
	if value, ok := _c.mutation.OriginAddress(); ok {
		_spec.SetField(ride.FieldOriginAddress, field.TypeString, value)
		_node.OriginAddress = value
	}
	if value, ok := _c.mutation.OriginLocationPoint(); ok {
		_spec.SetField(ride.FieldOriginLocationPoint, field.TypeString, value)
		_node.OriginLocationPoint = value
	}
	if value, ok := _c.mutation.DestinationCity(); ok {
		_spec.SetField(ride.FieldDestinationCity, field.TypeString, value)
		_node.DestinationCity = value
	}
	if value, ok := _c.mutation.DestinationAddress(); ok {
		_spec.SetField(ride.FieldDestinationAddress, field.TypeString, value)
		_node.DestinationAddress = value
	}
	if value, ok := _c.mutation.DestinationLocationPoint(); ok {
		_spec.SetField(ride.FieldDestinationLocationPoint, field.TypeString, value)
		_node.DestinationLocationPoint = value
	}
	if value, ok := _c.mutation.PriceAmount(); ok {
		_spec.SetField(ride.FieldPriceAmount, field.TypeInt64, value)
		_node.PriceAmount = value
	}
	if value, ok := _c.mutation.PriceCurrency(); ok {
		_spec.SetField(ride.FieldPriceCurrency, field.TypeString, value)
		_node.PriceCurrency = value
	}
	if value, ok := _c.mutation.AvailableSeats(); ok {
		_spec.SetField(ride.FieldAvailableSeats, field.TypeInt, value)
		_node.AvailableSeats = value
	}
	if value, ok := _c.mutation.TotalSeats(); ok {
		_spec.SetField(ride.FieldTotalSeats, field.TypeInt, value)
		_node.TotalSeats = value
	}
	if value, ok := _c.mutation.Amenities(); ok {
		_spec.SetField(ride.FieldAmenities, field.TypeJSON, value)
		_node.Amenities = value
	}
	if value, ok := _c.mutation.Stops(); ok {
		_spec.SetField(ride.FieldStops, field.TypeJSON, value)
		_node.Stops = value
	}
	if value, ok := _c.mutation.InstantConfirmation(); ok {
		_spec.SetField(ride.FieldInstantConfirmation, field.TypeBool, value)
		_node.InstantConfirmation = value
	}
	if value, ok := _c.mutation.CancellationPolicy(); ok {
		_spec.SetField(ride.FieldCancellationPolicy, field.TypeString, value)
		_node.CancellationPolicy = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(ride.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ride.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ride.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ride.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.DriverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.DriverTable,
			Columns: []string{ride.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DriverID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VehicleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.VehicleTable,
			Columns: []string{ride.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VehicleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ride.BookingsTable,
			Columns: []string{ride.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RideCreateBulk is the builder for creating many Ride entities in bulk.
type RideCreateBulk struct {
	config
	err      error
	builders []*RideCreate
}

// Save creates the Ride entities in the database.
func (_c *RideCreateBulk) Save(ctx context.Context) ([]*Ride, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ride, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RideCreateBulk) SaveX(ctx context.Context) []*Ride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
