// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/user"
	"github.com/slowtyper/poolie/backend/ent/vehicle"
)

// Ride is the model entity for the Ride schema.
type Ride struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// DriverID holds the value of the "driver_id" field.
	DriverID string `json:"driver_id,omitempty"`
	// VehicleID holds the value of the "vehicle_id" field.
	VehicleID string `json:"vehicle_id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// RideType holds the value of the "ride_type" field.
	RideType string `json:"ride_type,omitempty"`
	// Recurrence holds the value of the "recurrence" field.
	Recurrence map[string]interface{} `json:"recurrence,omitempty"`
	// DepartureTime holds the value of the "departure_time" field.
	DepartureTime time.Time `json:"departure_time,omitempty"`
	// ArrivalTime holds the value of the "arrival_time" field.
	ArrivalTime *time.Time `json:"arrival_time,omitempty"`
	// DurationMinutes holds the value of the "duration_minutes" field.
	DurationMinutes *int `json:"duration_minutes,omitempty"`
	// OriginCity holds the value of the "origin_city" field.
	OriginCity string `json:"origin_city,omitempty"`
	// OriginAddress holds the value of the "origin_address" field.
	OriginAddress string `json:"origin_address,omitempty"`
	// OriginLocationPoint holds the value of the "origin_location_point" field.
	OriginLocationPoint string `json:"origin_location_point,omitempty"`
	// DestinationCity holds the value of the "destination_city" field.
	DestinationCity string `json:"destination_city,omitempty"`
	// DestinationAddress holds the value of the "destination_address" field.
	DestinationAddress string `json:"destination_address,omitempty"`
	// DestinationLocationPoint holds the value of the "destination_location_point" field.
	DestinationLocationPoint string `json:"destination_location_point,omitempty"`
	// PriceAmount holds the value of the "price_amount" field.
	PriceAmount int64 `json:"price_amount,omitempty"`
	// PriceCurrency holds the value of the "price_currency" field.
	PriceCurrency string `json:"price_currency,omitempty"`
	// AvailableSeats holds the value of the "available_seats" field.
	AvailableSeats int `json:"available_seats,omitempty"`
	// TotalSeats holds the value of the "total_seats" field.
	TotalSeats int `json:"total_seats,omitempty"`
	// Amenities holds the value of the "amenities" field.
	Amenities map[string]interface{} `json:"amenities,omitempty"`
	// Stops holds the value of the "stops" field.
	Stops []interface{} `json:"stops,omitempty"`
	// InstantConfirmation holds the value of the "instant_confirmation" field.
	InstantConfirmation bool `json:"instant_confirmation,omitempty"`
	// CancellationPolicy holds the value of the "cancellation_policy" field.
	CancellationPolicy string `json:"cancellation_policy,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RideQuery when eager-loading is set.
	Edges        RideEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RideEdges holds the relations/edges for other nodes in the graph.
type RideEdges struct {
	// Driver holds the value of the driver edge.
	Driver *User `json:"driver,omitempty"`
	// Vehicle holds the value of the vehicle edge.
	Vehicle *Vehicle `json:"vehicle,omitempty"`
	// Bookings holds the value of the bookings edge.
	Bookings []*Booking `json:"bookings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DriverOrErr returns the Driver value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RideEdges) DriverOrErr() (*User, error) {
	if e.Driver != nil {
		return e.Driver, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "driver"}
}

// VehicleOrErr returns the Vehicle value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RideEdges) VehicleOrErr() (*Vehicle, error) {
	if e.Vehicle != nil {
		return e.Vehicle, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: vehicle.Label}
	}
	return nil, &NotLoadedError{edge: "vehicle"}
}

// BookingsOrErr returns the Bookings value or an error if the edge
// was not loaded in eager-loading.
func (e RideEdges) BookingsOrErr() ([]*Booking, error) {
	if e.loadedTypes[2] {
		return e.Bookings, nil
	}
	return nil, &NotLoadedError{edge: "bookings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ride.FieldRecurrence, ride.FieldAmenities, ride.FieldStops:
			values[i] = new([]byte)
		case ride.FieldInstantConfirmation:
			values[i] = new(sql.NullBool)
		case ride.FieldDurationMinutes, ride.FieldPriceAmount, ride.FieldAvailableSeats, ride.FieldTotalSeats:
			values[i] = new(sql.NullInt64)
		case ride.FieldID, ride.FieldDriverID, ride.FieldVehicleID, ride.FieldType, ride.FieldRideType, ride.FieldOriginCity, ride.FieldOriginAddress, ride.FieldOriginLocationPoint, ride.FieldDestinationCity, ride.FieldDestinationAddress, ride.FieldDestinationLocationPoint, ride.FieldPriceCurrency, ride.FieldCancellationPolicy, ride.FieldDescription, ride.FieldStatus:
			values[i] = new(sql.NullString)
		case ride.FieldDepartureTime, ride.FieldArrivalTime, ride.FieldCreatedAt, ride.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ride fields.
func (_m *Ride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ride.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ride.FieldDriverID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field driver_id", values[i])
			} else if value.Valid {
				_m.DriverID = value.String
			}
		case ride.FieldVehicleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vehicle_id", values[i])
			} else if value.Valid {
				_m.VehicleID = value.String
			}
		case ride.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case ride.FieldRideType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ride_type", values[i])
			} else if value.Valid {
				_m.RideType = value.String
			}
		case ride.FieldRecurrence:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field recurrence", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Recurrence); err != nil {
					return fmt.Errorf("unmarshal field recurrence: %w", err)
				}
			}
		case ride.FieldDepartureTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field departure_time", values[i])
			} else if value.Valid {
				_m.DepartureTime = value.Time
			}
		case ride.FieldArrivalTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field arrival_time", values[i])
			} else if value.Valid {
				_m.ArrivalTime = new(time.Time)
				*_m.ArrivalTime = value.Time
			}
		case ride.FieldDurationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_minutes", values[i])
			} else if value.Valid {
				_m.DurationMinutes = new(int)
				*_m.DurationMinutes = int(value.Int64)
			}
		case ride.FieldOriginCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin_city", values[i])
			} else if value.Valid {
				_m.OriginCity = value.String
			}
		case ride.FieldOriginAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin_address", values[i])
			} else if value.Valid {
				_m.OriginAddress = value.String
			}
		case ride.FieldOriginLocationPoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin_location_point", values[i])
			} else if value.Valid {
				_m.OriginLocationPoint = value.String
			}
		case ride.FieldDestinationCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination_city", values[i])
			} else if value.Valid {
				_m.DestinationCity = value.String
			}
		case ride.FieldDestinationAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination_address", values[i])
			} else if value.Valid {
				_m.DestinationAddress = value.String
			}
		case ride.FieldDestinationLocationPoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination_location_point", values[i])
			} else if value.Valid {
				_m.DestinationLocationPoint = value.String
			}
		case ride.FieldPriceAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_amount", values[i])
			} else if value.Valid {
				_m.PriceAmount = value.Int64
			}
		case ride.FieldPriceCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_currency", values[i])
			} else if value.Valid {
				_m.PriceCurrency = value.String
			}
		case ride.FieldAvailableSeats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field available_seats", values[i])
			} else if value.Valid {
				_m.AvailableSeats = int(value.Int64)
			}
		case ride.FieldTotalSeats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_seats", values[i])
			} else if value.Valid {
				_m.TotalSeats = int(value.Int64)
			}
		case ride.FieldAmenities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field amenities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Amenities); err != nil {
					return fmt.Errorf("unmarshal field amenities: %w", err)
				}
			}
		case ride.FieldStops:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field stops", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Stops); err != nil {
					return fmt.Errorf("unmarshal field stops: %w", err)
				}
			}
		case ride.FieldInstantConfirmation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field instant_confirmation", values[i])
			} else if value.Valid {
				_m.InstantConfirmation = value.Bool
			}
		case ride.FieldCancellationPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancellation_policy", values[i])
			} else if value.Valid {
				_m.CancellationPolicy = value.String
			}
		case ride.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case ride.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ride.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ride.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ride.
// This includes values selected through modifiers, order, etc.
func (_m *Ride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDriver queries the "driver" edge of the Ride entity.
func (_m *Ride) QueryDriver() *UserQuery {
	return NewRideClient(_m.config).QueryDriver(_m)
}

// QueryVehicle queries the "vehicle" edge of the Ride entity.
func (_m *Ride) QueryVehicle() *VehicleQuery {
	return NewRideClient(_m.config).QueryVehicle(_m)
}

// QueryBookings queries the "bookings" edge of the Ride entity.
func (_m *Ride) QueryBookings() *BookingQuery {
	return NewRideClient(_m.config).QueryBookings(_m)
}

// Update returns a builder for updating this Ride.
// Note that you need to call Ride.Unwrap() before calling this method if this Ride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ride) Update() *RideUpdateOne {
	return NewRideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ride) Unwrap() *Ride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ride) String() string {
	var builder strings.Builder
	builder.WriteString("Ride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("driver_id=")
	builder.WriteString(_m.DriverID)
	builder.WriteString(", ")
	builder.WriteString("vehicle_id=")
	builder.WriteString(_m.VehicleID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("ride_type=")
	builder.WriteString(_m.RideType)
	builder.WriteString(", ")
	builder.WriteString("recurrence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Recurrence))
	builder.WriteString(", ")
	builder.WriteString("departure_time=")
	builder.WriteString(_m.DepartureTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ArrivalTime; v != nil {
		builder.WriteString("arrival_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DurationMinutes; v != nil {
		builder.WriteString("duration_minutes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("origin_city=")
	builder.WriteString(_m.OriginCity)
	builder.WriteString(", ")
	builder.WriteString("origin_address=")
	builder.WriteString(_m.OriginAddress)
	builder.WriteString(", ")
	builder.WriteString("origin_location_point=")
	builder.WriteString(_m.OriginLocationPoint)
	builder.WriteString(", ")
	builder.WriteString("destination_city=")
	builder.WriteString(_m.DestinationCity)
	builder.WriteString(", ")
	builder.WriteString("destination_address=")
	builder.WriteString(_m.DestinationAddress)
	builder.WriteString(", ")
	builder.WriteString("destination_location_point=")
	builder.WriteString(_m.DestinationLocationPoint)
	builder.WriteString(", ")
	builder.WriteString("price_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceAmount))
	builder.WriteString(", ")
	builder.WriteString("price_currency=")
	builder.WriteString(_m.PriceCurrency)
	builder.WriteString(", ")
	builder.WriteString("available_seats=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailableSeats))
	builder.WriteString(", ")
	builder.WriteString("total_seats=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSeats))
	builder.WriteString(", ")
	builder.WriteString("amenities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amenities))
	builder.WriteString(", ")
	builder.WriteString("stops=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stops))
	builder.WriteString(", ")
	builder.WriteString("instant_confirmation=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstantConfirmation))
	builder.WriteString(", ")
	builder.WriteString("cancellation_policy=")
	builder.WriteString(_m.CancellationPolicy)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Rides is a parsable slice of Ride.
type Rides []*Ride
