// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/slowtyper/poolie/backend/ent/booking"
	"github.com/slowtyper/poolie/backend/ent/predicate"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/user"
	"github.com/slowtyper/poolie/backend/ent/vehicle"
)

// RideUpdate is the builder for updating Ride entities.
type RideUpdate struct {
	config
	hooks    []Hook
	mutation *RideMutation
}

// Where appends a list predicates to the RideUpdate builder.
func (_u *RideUpdate) Where(ps ...predicate.Ride) *RideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDriverID sets the "driver_id" field.
func (_u *RideUpdate) SetDriverID(v string) *RideUpdate {
	_u.mutation.SetDriverID(v)
	return _u
}

// SetNillableDriverID sets the "driver_id" field if the given value is not nil.
func (_u *RideUpdate) SetNillableDriverID(v *string) *RideUpdate {
	if v != nil {
		_u.SetDriverID(*v)
	}
	return _u
}

// SetVehicleID sets the "vehicle_id" field.
func (_u *RideUpdate) SetVehicleID(v string) *RideUpdate {
	_u.mutation.SetVehicleID(v)
	return _u
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_u *RideUpdate) SetNillableVehicleID(v *string) *RideUpdate {
	if v != nil {
		_u.SetVehicleID(*v)
	}
	return _u
}

// ClearVehicleID clears the value of the "vehicle_id" field.
func (_u *RideUpdate) ClearVehicleID() *RideUpdate {
	_u.mutation.ClearVehicleID()
	return _u
}

// SetType sets the "type" field.
func (_u *RideUpdate) SetType(v string) *RideUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RideUpdate) SetNillableType(v *string) *RideUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRideType sets the "ride_type" field.
func (_u *RideUpdate) SetRideType(v string) *RideUpdate {
	_u.mutation.SetRideType(v)
	return _u
}

// SetNillableRideType sets the "ride_type" field if the given value is not nil.
func (_u *RideUpdate) SetNillableRideType(v *string) *RideUpdate {
	if v != nil {
		_u.SetRideType(*v)
	}
	return _u
}

// SetRecurrence sets the "recurrence" field.
func (_u *RideUpdate) SetRecurrence(v map[string]interface{}) *RideUpdate {
	_u.mutation.SetRecurrence(v)
	return _u
}

// ClearRecurrence clears the value of the "recurrence" field.
func (_u *RideUpdate) ClearRecurrence() *RideUpdate {
	_u.mutation.ClearRecurrence()
	return _u
}

// SetDepartureTime sets the "departure_time" field.
func (_u *RideUpdate) SetDepartureTime(v time.Time) *RideUpdate {
	_u.mutation.SetDepartureTime(v)
	return _u
}

// SetNillableDepartureTime sets the "departure_time" field if the given value is not nil.
func (_u *RideUpdate) SetNillableDepartureTime(v *time.Time) *RideUpdate {
	if v != nil {
		_u.SetDepartureTime(*v)
	}
	return _u
}

// SetArrivalTime sets the "arrival_time" field.
func (_u *RideUpdate) SetArrivalTime(v time.Time) *RideUpdate {
	_u.mutation.SetArrivalTime(v)
	return _u
}

// SetNillableArrivalTime sets the "arrival_time" field if the given value is not nil.
func (_u *RideUpdate) SetNillableArrivalTime(v *time.Time) *RideUpdate {
	if v != nil {
		_u.SetArrivalTime(*v)
	}
	return _u
}

// ClearArrivalTime clears the value of the "arrival_time" field.
func (_u *RideUpdate) ClearArrivalTime() *RideUpdate {
	_u.mutation.ClearArrivalTime()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *RideUpdate) SetDurationMinutes(v int) *RideUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *RideUpdate) SetNillableDurationMinutes(v *int) *RideUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *RideUpdate) AddDurationMinutes(v int) *RideUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// ClearDurationMinutes clears the value of the "duration_minutes" field.
func (_u *RideUpdate) ClearDurationMinutes() *RideUpdate {
	_u.mutation.ClearDurationMinutes()
	return _u
}

// SetOriginCity sets the "origin_city" field.
func (_u *RideUpdate) SetOriginCity(v string) *RideUpdate {
	_u.mutation.SetOriginCity(v)
	return _u
}

// SetNillableOriginCity sets the "origin_city" field if the given value is not nil.
func (_u *RideUpdate) SetNillableOriginCity(v *string) *RideUpdate {
	if v != nil {
		_u.SetOriginCity(*v)
	}
	return _u
}

// SetOriginAddress sets the "origin_address" field.
func (_u *RideUpdate) SetOriginAddress(v string) *RideUpdate {
	_u.mutation.SetOriginAddress(v)
	return _u
}

// SetNillableOriginAddress sets the "origin_address" field if the given value is not nil.
func (_u *RideUpdate) SetNillableOriginAddress(v *string) *RideUpdate {
	if v != nil {
		_u.SetOriginAddress(*v)
	}
	return _u
}

// SetOriginLocationPoint sets the "origin_location_point" field.
func (_u *RideUpdate) SetOriginLocationPoint(v string) *RideUpdate {
	_u.mutation.SetOriginLocationPoint(v)
	return _u
}

// SetNillableOriginLocationPoint sets the "origin_location_point" field if the given value is not nil.
func (_u *RideUpdate) SetNillableOriginLocationPoint(v *string) *RideUpdate {
	if v != nil {
		_u.SetOriginLocationPoint(*v)
	}
	return _u
}

// ClearOriginLocationPoint clears the value of the "origin_location_point" field.
func (_u *RideUpdate) ClearOriginLocationPoint() *RideUpdate {
	_u.mutation.ClearOriginLocationPoint()
	return _u
}

// SetDestinationCity sets the "destination_city" field.
func (_u *RideUpdate) SetDestinationCity(v string) *RideUpdate {
	_u.mutation.SetDestinationCity(v)
	return _u
}

// SetNillableDestinationCity sets the "destination_city" field if the given value is not nil.
func (_u *RideUpdate) SetNillableDestinationCity(v *string) *RideUpdate {
	if v != nil {
		_u.SetDestinationCity(*v)
	}
	return _u
}

// SetDestinationAddress sets the "destination_address" field.
func (_u *RideUpdate) SetDestinationAddress(v string) *RideUpdate {
	_u.mutation.SetDestinationAddress(v)
	return _u
}

// SetNillableDestinationAddress sets the "destination_address" field if the given value is not nil.
func (_u *RideUpdate) SetNillableDestinationAddress(v *string) *RideUpdate {
	if v != nil {
		_u.SetDestinationAddress(*v)
	}
	return _u
}

// SetDestinationLocationPoint sets the "destination_location_point" field.
func (_u *RideUpdate) SetDestinationLocationPoint(v string) *RideUpdate {
	_u.mutation.SetDestinationLocationPoint(v)
	return _u
}

// SetNillableDestinationLocationPoint sets the "destination_location_point" field if the given value is not nil.
func (_u *RideUpdate) SetNillableDestinationLocationPoint(v *string) *RideUpdate {
	if v != nil {
		_u.SetDestinationLocationPoint(*v)
	}
	return _u
}

// ClearDestinationLocationPoint clears the value of the "destination_location_point" field.
func (_u *RideUpdate) ClearDestinationLocationPoint() *RideUpdate {
	_u.mutation.ClearDestinationLocationPoint()
	return _u
}

// SetPriceAmount sets the "price_amount" field.
func (_u *RideUpdate) SetPriceAmount(v int64) *RideUpdate {
	_u.mutation.ResetPriceAmount()
	_u.mutation.SetPriceAmount(v)
	return _u
}

// SetNillablePriceAmount sets the "price_amount" field if the given value is not nil.
func (_u *RideUpdate) SetNillablePriceAmount(v *int64) *RideUpdate {
	if v != nil {
		_u.SetPriceAmount(*v)
	}
	return _u
}

// AddPriceAmount adds value to the "price_amount" field.
func (_u *RideUpdate) AddPriceAmount(v int64) *RideUpdate {
	_u.mutation.AddPriceAmount(v)
	return _u
}

// SetPriceCurrency sets the "price_currency" field.
func (_u *RideUpdate) SetPriceCurrency(v string) *RideUpdate {
	_u.mutation.SetPriceCurrency(v)
	return _u
}

// SetNillablePriceCurrency sets the "price_currency" field if the given value is not nil.
func (_u *RideUpdate) SetNillablePriceCurrency(v *string) *RideUpdate {
	if v != nil {
		_u.SetPriceCurrency(*v)
	}
	return _u
}

// SetAvailableSeats sets the "available_seats" field.
func (_u *RideUpdate) SetAvailableSeats(v int) *RideUpdate {
	_u.mutation.ResetAvailableSeats()
	_u.mutation.SetAvailableSeats(v)
	return _u
}

// SetNillableAvailableSeats sets the "available_seats" field if the given value is not nil.
func (_u *RideUpdate) SetNillableAvailableSeats(v *int) *RideUpdate {
	if v != nil {
		_u.SetAvailableSeats(*v)
	}
	return _u
}

// AddAvailableSeats adds value to the "available_seats" field.
func (_u *RideUpdate) AddAvailableSeats(v int) *RideUpdate {
	_u.mutation.AddAvailableSeats(v)
	return _u
}

// SetTotalSeats sets the "total_seats" field.
func (_u *RideUpdate) SetTotalSeats(v int) *RideUpdate {
	_u.mutation.ResetTotalSeats()
	_u.mutation.SetTotalSeats(v)
	return _u
}

// SetNillableTotalSeats sets the "total_seats" field if the given value is not nil.
func (_u *RideUpdate) SetNillableTotalSeats(v *int) *RideUpdate {
	if v != nil {
		_u.SetTotalSeats(*v)
	}
	return _u
}

// AddTotalSeats adds value to the "total_seats" field.
func (_u *RideUpdate) AddTotalSeats(v int) *RideUpdate {
	_u.mutation.AddTotalSeats(v)
	return _u
}

// SetAmenities sets the "amenities" field.
func (_u *RideUpdate) SetAmenities(v map[string]interface{}) *RideUpdate {
	_u.mutation.SetAmenities(v)
	return _u
}

// ClearAmenities clears the value of the "amenities" field.
func (_u *RideUpdate) ClearAmenities() *RideUpdate {
	_u.mutation.ClearAmenities()
	return _u
}

// SetStops sets the "stops" field.
func (_u *RideUpdate) SetStops(v []interface{}) *RideUpdate {
	_u.mutation.SetStops(v)
	return _u
}

// AppendStops appends value to the "stops" field.
func (_u *RideUpdate) AppendStops(v []interface{}) *RideUpdate {
	_u.mutation.AppendStops(v)
	return _u
}

// ClearStops clears the value of the "stops" field.
func (_u *RideUpdate) ClearStops() *RideUpdate {
	_u.mutation.ClearStops()
	return _u
}

// SetInstantConfirmation sets the "instant_confirmation" field.
func (_u *RideUpdate) SetInstantConfirmation(v bool) *RideUpdate {
	_u.mutation.SetInstantConfirmation(v)
	return _u
}

// SetNillableInstantConfirmation sets the "instant_confirmation" field if the given value is not nil.
func (_u *RideUpdate) SetNillableInstantConfirmation(v *bool) *RideUpdate {
	if v != nil {
		_u.SetInstantConfirmation(*v)
	}
	return _u
}

// SetCancellationPolicy sets the "cancellation_policy" field.
func (_u *RideUpdate) SetCancellationPolicy(v string) *RideUpdate {
	_u.mutation.SetCancellationPolicy(v)
	return _u
}

// SetNillableCancellationPolicy sets the "cancellation_policy" field if the given value is not nil.
func (_u *RideUpdate) SetNillableCancellationPolicy(v *string) *RideUpdate {
	if v != nil {
		_u.SetCancellationPolicy(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RideUpdate) SetDescription(v string) *RideUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RideUpdate) SetNillableDescription(v *string) *RideUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RideUpdate) ClearDescription() *RideUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RideUpdate) SetStatus(v string) *RideUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RideUpdate) SetNillableStatus(v *string) *RideUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RideUpdate) SetUpdatedAt(v time.Time) *RideUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDriver sets the "driver" edge to the User entity.
func (_u *RideUpdate) SetDriver(v *User) *RideUpdate {
	return _u.SetDriverID(v.ID)
}

// SetVehicle sets the "vehicle" edge to the Vehicle entity.
func (_u *RideUpdate) SetVehicle(v *Vehicle) *RideUpdate {
	return _u.SetVehicleID(v.ID)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *RideUpdate) AddBookingIDs(ids ...string) *RideUpdate {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *RideUpdate) AddBookings(v ...*Booking) *RideUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// Mutation returns the RideMutation object of the builder.
func (_u *RideUpdate) Mutation() *RideMutation {
	return _u.mutation
}

// ClearDriver clears the "driver" edge to the User entity.
func (_u *RideUpdate) ClearDriver() *RideUpdate {
	_u.mutation.ClearDriver()
	return _u
}

// ClearVehicle clears the "vehicle" edge to the Vehicle entity.
func (_u *RideUpdate) ClearVehicle() *RideUpdate {
	_u.mutation.ClearVehicle()
	return _u
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *RideUpdate) ClearBookings() *RideUpdate {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *RideUpdate) RemoveBookingIDs(ids ...string) *RideUpdate {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *RideUpdate) RemoveBookings(v ...*Booking) *RideUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RideUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RideUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RideUpdate) check() error {
	if v, ok := _u.mutation.DriverID(); ok {
		if err := ride.DriverIDValidator(v); err != nil {
			return &ValidationError{Name: "driver_id", err: fmt.Errorf(`ent: validator failed for field "Ride.driver_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMinutes(); ok {
		if err := ride.DurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "duration_minutes", err: fmt.Errorf(`ent: validator failed for field "Ride.duration_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginCity(); ok {
		if err := ride.OriginCityValidator(v); err != nil {
			return &ValidationError{Name: "origin_city", err: fmt.Errorf(`ent: validator failed for field "Ride.origin_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginAddress(); ok {
		if err := ride.OriginAddressValidator(v); err != nil {
			return &ValidationError{Name: "origin_address", err: fmt.Errorf(`ent: validator failed for field "Ride.origin_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationCity(); ok {
		if err := ride.DestinationCityValidator(v); err != nil {
			return &ValidationError{Name: "destination_city", err: fmt.Errorf(`ent: validator failed for field "Ride.destination_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationAddress(); ok {
		if err := ride.DestinationAddressValidator(v); err != nil {
			return &ValidationError{Name: "destination_address", err: fmt.Errorf(`ent: validator failed for field "Ride.destination_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceAmount(); ok {
		if err := ride.PriceAmountValidator(v); err != nil {
			return &ValidationError{Name: "price_amount", err: fmt.Errorf(`ent: validator failed for field "Ride.price_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvailableSeats(); ok {
		if err := ride.AvailableSeatsValidator(v); err != nil {
			return &ValidationError{Name: "available_seats", err: fmt.Errorf(`ent: validator failed for field "Ride.available_seats": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalSeats(); ok {
		if err := ride.TotalSeatsValidator(v); err != nil {
			return &ValidationError{Name: "total_seats", err: fmt.Errorf(`ent: validator failed for field "Ride.total_seats": %w`, err)}
		}
	}
	if _u.mutation.DriverCleared() && len(_u.mutation.DriverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ride.driver"`)
	}
	return nil
}

func (_u *RideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ride.Table, ride.Columns, sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ride.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RideType(); ok {
		_spec.SetField(ride.FieldRideType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recurrence(); ok {
		_spec.SetField(ride.FieldRecurrence, field.TypeJSON, value)
	}
	if _u.mutation.RecurrenceCleared() {
		_spec.ClearField(ride.FieldRecurrence, field.TypeJSON)
	}
	if value, ok := _u.mutation.DepartureTime(); ok {
		_spec.SetField(ride.FieldDepartureTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ArrivalTime(); ok {
		_spec.SetField(ride.FieldArrivalTime, field.TypeTime, value)
	}
	if _u.mutation.ArrivalTimeCleared() {
		_spec.ClearField(ride.FieldArrivalTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(ride.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(ride.FieldDurationMinutes, field.TypeInt, value)
	}
	if _u.mutation.DurationMinutesCleared() {
		_spec.ClearField(ride.FieldDurationMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.OriginCity(); ok {
		_spec.SetField(ride.FieldOriginCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginAddress(); ok {
		_spec.SetField(ride.FieldOriginAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginLocationPoint(); ok {
		_spec.SetField(ride.FieldOriginLocationPoint, field.TypeString, value)
	}
	if _u.mutation.OriginLocationPointCleared() {
		_spec.ClearField(ride.FieldOriginLocationPoint, field.TypeString)
	}
	if value, ok := _u.mutation.DestinationCity(); ok {
		_spec.SetField(ride.FieldDestinationCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.DestinationAddress(); ok {
		_spec.SetField(ride.FieldDestinationAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.DestinationLocationPoint(); ok {
		_spec.SetField(ride.FieldDestinationLocationPoint, field.TypeString, value)
	}
	if _u.mutation.DestinationLocationPointCleared() {
		_spec.ClearField(ride.FieldDestinationLocationPoint, field.TypeString)
	}
	if value, ok := _u.mutation.PriceAmount(); ok {
		_spec.SetField(ride.FieldPriceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceAmount(); ok {
		_spec.AddField(ride.FieldPriceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PriceCurrency(); ok {
		_spec.SetField(ride.FieldPriceCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvailableSeats(); ok {
		_spec.SetField(ride.FieldAvailableSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvailableSeats(); ok {
		_spec.AddField(ride.FieldAvailableSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalSeats(); ok {
		_spec.SetField(ride.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSeats(); ok {
		_spec.AddField(ride.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amenities(); ok {
		_spec.SetField(ride.FieldAmenities, field.TypeJSON, value)
	}
	if _u.mutation.AmenitiesCleared() {
		_spec.ClearField(ride.FieldAmenities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Stops(); ok {
		_spec.SetField(ride.FieldStops, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStops(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ride.FieldStops, value)
		})
	}
	if _u.mutation.StopsCleared() {
		_spec.ClearField(ride.FieldStops, field.TypeJSON)
	}
	if value, ok := _u.mutation.InstantConfirmation(); ok {
		_spec.SetField(ride.FieldInstantConfirmation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CancellationPolicy(); ok {
		_spec.SetField(ride.FieldCancellationPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ride.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ride.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ride.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ride.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DriverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.DriverTable,
			Columns: []string{ride.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DriverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.DriverTable,
			Columns: []string{ride.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.VehicleTable,
			Columns: []string{ride.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehicleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.VehicleTable,
			Columns: []string{ride.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ride.BookingsTable,
			Columns: []string{ride.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ride.BookingsTable,
			Columns: []string{ride.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ride.BookingsTable,
			Columns: []string{ride.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RideUpdateOne is the builder for updating a single Ride entity.
type RideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RideMutation
}

// SetDriverID sets the "driver_id" field.
func (_u *RideUpdateOne) SetDriverID(v string) *RideUpdateOne {
	_u.mutation.SetDriverID(v)
	return _u
}

// SetNillableDriverID sets the "driver_id" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableDriverID(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetDriverID(*v)
	}
	return _u
}

// SetVehicleID sets the "vehicle_id" field.
func (_u *RideUpdateOne) SetVehicleID(v string) *RideUpdateOne {
	_u.mutation.SetVehicleID(v)
	return _u
}

// SetNillableVehicleID sets the "vehicle_id" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableVehicleID(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetVehicleID(*v)
	}
	return _u
}

// ClearVehicleID clears the value of the "vehicle_id" field.
func (_u *RideUpdateOne) ClearVehicleID() *RideUpdateOne {
	_u.mutation.ClearVehicleID()
	return _u
}

// SetType sets the "type" field.
func (_u *RideUpdateOne) SetType(v string) *RideUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableType(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRideType sets the "ride_type" field.
func (_u *RideUpdateOne) SetRideType(v string) *RideUpdateOne {
	_u.mutation.SetRideType(v)
	return _u
}

// SetNillableRideType sets the "ride_type" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableRideType(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetRideType(*v)
	}
	return _u
}

// SetRecurrence sets the "recurrence" field.
func (_u *RideUpdateOne) SetRecurrence(v map[string]interface{}) *RideUpdateOne {
	_u.mutation.SetRecurrence(v)
	return _u
}

// ClearRecurrence clears the value of the "recurrence" field.
func (_u *RideUpdateOne) ClearRecurrence() *RideUpdateOne {
	_u.mutation.ClearRecurrence()
	return _u
}

// SetDepartureTime sets the "departure_time" field.
func (_u *RideUpdateOne) SetDepartureTime(v time.Time) *RideUpdateOne {
	_u.mutation.SetDepartureTime(v)
	return _u
}

// SetNillableDepartureTime sets the "departure_time" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableDepartureTime(v *time.Time) *RideUpdateOne {
	if v != nil {
		_u.SetDepartureTime(*v)
	}
	return _u
}

// SetArrivalTime sets the "arrival_time" field.
func (_u *RideUpdateOne) SetArrivalTime(v time.Time) *RideUpdateOne {
	_u.mutation.SetArrivalTime(v)
	return _u
}

// SetNillableArrivalTime sets the "arrival_time" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableArrivalTime(v *time.Time) *RideUpdateOne {
	if v != nil {
		_u.SetArrivalTime(*v)
	}
	return _u
}

// ClearArrivalTime clears the value of the "arrival_time" field.
func (_u *RideUpdateOne) ClearArrivalTime() *RideUpdateOne {
	_u.mutation.ClearArrivalTime()
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *RideUpdateOne) SetDurationMinutes(v int) *RideUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableDurationMinutes(v *int) *RideUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *RideUpdateOne) AddDurationMinutes(v int) *RideUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// ClearDurationMinutes clears the value of the "duration_minutes" field.
func (_u *RideUpdateOne) ClearDurationMinutes() *RideUpdateOne {
	_u.mutation.ClearDurationMinutes()
	return _u
}

// SetOriginCity sets the "origin_city" field.
func (_u *RideUpdateOne) SetOriginCity(v string) *RideUpdateOne {
	_u.mutation.SetOriginCity(v)
	return _u
}

// SetNillableOriginCity sets the "origin_city" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableOriginCity(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetOriginCity(*v)
	}
	return _u
}

// SetOriginAddress sets the "origin_address" field.
func (_u *RideUpdateOne) SetOriginAddress(v string) *RideUpdateOne {
	_u.mutation.SetOriginAddress(v)
	return _u
}

// SetNillableOriginAddress sets the "origin_address" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableOriginAddress(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetOriginAddress(*v)
	}
	return _u
}

// SetOriginLocationPoint sets the "origin_location_point" field.
func (_u *RideUpdateOne) SetOriginLocationPoint(v string) *RideUpdateOne {
	_u.mutation.SetOriginLocationPoint(v)
	return _u
}

// SetNillableOriginLocationPoint sets the "origin_location_point" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableOriginLocationPoint(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetOriginLocationPoint(*v)
	}
	return _u
}

// ClearOriginLocationPoint clears the value of the "origin_location_point" field.
func (_u *RideUpdateOne) ClearOriginLocationPoint() *RideUpdateOne {
	_u.mutation.ClearOriginLocationPoint()
	return _u
}

// SetDestinationCity sets the "destination_city" field.
func (_u *RideUpdateOne) SetDestinationCity(v string) *RideUpdateOne {
	_u.mutation.SetDestinationCity(v)
	return _u
}

// SetNillableDestinationCity sets the "destination_city" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableDestinationCity(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetDestinationCity(*v)
	}
	return _u
}

// SetDestinationAddress sets the "destination_address" field.
func (_u *RideUpdateOne) SetDestinationAddress(v string) *RideUpdateOne {
	_u.mutation.SetDestinationAddress(v)
	return _u
}

// SetNillableDestinationAddress sets the "destination_address" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableDestinationAddress(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetDestinationAddress(*v)
	}
	return _u
}

// SetDestinationLocationPoint sets the "destination_location_point" field.
func (_u *RideUpdateOne) SetDestinationLocationPoint(v string) *RideUpdateOne {
	_u.mutation.SetDestinationLocationPoint(v)
	return _u
}

// SetNillableDestinationLocationPoint sets the "destination_location_point" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableDestinationLocationPoint(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetDestinationLocationPoint(*v)
	}
	return _u
}

// ClearDestinationLocationPoint clears the value of the "destination_location_point" field.
func (_u *RideUpdateOne) ClearDestinationLocationPoint() *RideUpdateOne {
	_u.mutation.ClearDestinationLocationPoint()
	return _u
}

// SetPriceAmount sets the "price_amount" field.
func (_u *RideUpdateOne) SetPriceAmount(v int64) *RideUpdateOne {
	_u.mutation.ResetPriceAmount()
	_u.mutation.SetPriceAmount(v)
	return _u
}

// SetNillablePriceAmount sets the "price_amount" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillablePriceAmount(v *int64) *RideUpdateOne {
	if v != nil {
		_u.SetPriceAmount(*v)
	}
	return _u
}

// AddPriceAmount adds value to the "price_amount" field.
func (_u *RideUpdateOne) AddPriceAmount(v int64) *RideUpdateOne {
	_u.mutation.AddPriceAmount(v)
	return _u
}

// SetPriceCurrency sets the "price_currency" field.
func (_u *RideUpdateOne) SetPriceCurrency(v string) *RideUpdateOne {
	_u.mutation.SetPriceCurrency(v)
	return _u
}

// SetNillablePriceCurrency sets the "price_currency" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillablePriceCurrency(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetPriceCurrency(*v)
	}
	return _u
}

// SetAvailableSeats sets the "available_seats" field.
func (_u *RideUpdateOne) SetAvailableSeats(v int) *RideUpdateOne {
	_u.mutation.ResetAvailableSeats()
	_u.mutation.SetAvailableSeats(v)
	return _u
}

// SetNillableAvailableSeats sets the "available_seats" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableAvailableSeats(v *int) *RideUpdateOne {
	if v != nil {
		_u.SetAvailableSeats(*v)
	}
	return _u
}

// AddAvailableSeats adds value to the "available_seats" field.
func (_u *RideUpdateOne) AddAvailableSeats(v int) *RideUpdateOne {
	_u.mutation.AddAvailableSeats(v)
	return _u
}

// SetTotalSeats sets the "total_seats" field.
func (_u *RideUpdateOne) SetTotalSeats(v int) *RideUpdateOne {
	_u.mutation.ResetTotalSeats()
	_u.mutation.SetTotalSeats(v)
	return _u
}

// SetNillableTotalSeats sets the "total_seats" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableTotalSeats(v *int) *RideUpdateOne {
	if v != nil {
		_u.SetTotalSeats(*v)
	}
	return _u
}

// AddTotalSeats adds value to the "total_seats" field.
func (_u *RideUpdateOne) AddTotalSeats(v int) *RideUpdateOne {
	_u.mutation.AddTotalSeats(v)
	return _u
}

// SetAmenities sets the "amenities" field.
func (_u *RideUpdateOne) SetAmenities(v map[string]interface{}) *RideUpdateOne {
	_u.mutation.SetAmenities(v)
	return _u
}

// ClearAmenities clears the value of the "amenities" field.
func (_u *RideUpdateOne) ClearAmenities() *RideUpdateOne {
	_u.mutation.ClearAmenities()
	return _u
}

// SetStops sets the "stops" field.
func (_u *RideUpdateOne) SetStops(v []interface{}) *RideUpdateOne {
	_u.mutation.SetStops(v)
	return _u
}

// AppendStops appends value to the "stops" field.
func (_u *RideUpdateOne) AppendStops(v []interface{}) *RideUpdateOne {
	_u.mutation.AppendStops(v)
	return _u
}

// ClearStops clears the value of the "stops" field.
func (_u *RideUpdateOne) ClearStops() *RideUpdateOne {
	_u.mutation.ClearStops()
	return _u
}

// SetInstantConfirmation sets the "instant_confirmation" field.
func (_u *RideUpdateOne) SetInstantConfirmation(v bool) *RideUpdateOne {
	_u.mutation.SetInstantConfirmation(v)
	return _u
}

// SetNillableInstantConfirmation sets the "instant_confirmation" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableInstantConfirmation(v *bool) *RideUpdateOne {
	if v != nil {
		_u.SetInstantConfirmation(*v)
	}
	return _u
}

// SetCancellationPolicy sets the "cancellation_policy" field.
func (_u *RideUpdateOne) SetCancellationPolicy(v string) *RideUpdateOne {
	_u.mutation.SetCancellationPolicy(v)
	return _u
}

// SetNillableCancellationPolicy sets the "cancellation_policy" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableCancellationPolicy(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetCancellationPolicy(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RideUpdateOne) SetDescription(v string) *RideUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableDescription(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RideUpdateOne) ClearDescription() *RideUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RideUpdateOne) SetStatus(v string) *RideUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RideUpdateOne) SetNillableStatus(v *string) *RideUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RideUpdateOne) SetUpdatedAt(v time.Time) *RideUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDriver sets the "driver" edge to the User entity.
func (_u *RideUpdateOne) SetDriver(v *User) *RideUpdateOne {
	return _u.SetDriverID(v.ID)
}

// SetVehicle sets the "vehicle" edge to the Vehicle entity.
func (_u *RideUpdateOne) SetVehicle(v *Vehicle) *RideUpdateOne {
	return _u.SetVehicleID(v.ID)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *RideUpdateOne) AddBookingIDs(ids ...string) *RideUpdateOne {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *RideUpdateOne) AddBookings(v ...*Booking) *RideUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// Mutation returns the RideMutation object of the builder.
func (_u *RideUpdateOne) Mutation() *RideMutation {
	return _u.mutation
}

// ClearDriver clears the "driver" edge to the User entity.
func (_u *RideUpdateOne) ClearDriver() *RideUpdateOne {
	_u.mutation.ClearDriver()
	return _u
}

// ClearVehicle clears the "vehicle" edge to the Vehicle entity.
func (_u *RideUpdateOne) ClearVehicle() *RideUpdateOne {
	_u.mutation.ClearVehicle()
	return _u
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *RideUpdateOne) ClearBookings() *RideUpdateOne {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *RideUpdateOne) RemoveBookingIDs(ids ...string) *RideUpdateOne {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *RideUpdateOne) RemoveBookings(v ...*Booking) *RideUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// Where appends a list predicates to the RideUpdate builder.
func (_u *RideUpdateOne) Where(ps ...predicate.Ride) *RideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RideUpdateOne) Select(field string, fields ...string) *RideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ride entity.
func (_u *RideUpdateOne) Save(ctx context.Context) (*Ride, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RideUpdateOne) SaveX(ctx context.Context) *Ride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RideUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RideUpdateOne) check() error {
	if v, ok := _u.mutation.DriverID(); ok {
		if err := ride.DriverIDValidator(v); err != nil {
			return &ValidationError{Name: "driver_id", err: fmt.Errorf(`ent: validator failed for field "Ride.driver_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMinutes(); ok {
		if err := ride.DurationMinutesValidator(v); err != nil {
			return &ValidationError{Name: "duration_minutes", err: fmt.Errorf(`ent: validator failed for field "Ride.duration_minutes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginCity(); ok {
		if err := ride.OriginCityValidator(v); err != nil {
			return &ValidationError{Name: "origin_city", err: fmt.Errorf(`ent: validator failed for field "Ride.origin_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginAddress(); ok {
		if err := ride.OriginAddressValidator(v); err != nil {
			return &ValidationError{Name: "origin_address", err: fmt.Errorf(`ent: validator failed for field "Ride.origin_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationCity(); ok {
		if err := ride.DestinationCityValidator(v); err != nil {
			return &ValidationError{Name: "destination_city", err: fmt.Errorf(`ent: validator failed for field "Ride.destination_city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DestinationAddress(); ok {
		if err := ride.DestinationAddressValidator(v); err != nil {
			return &ValidationError{Name: "destination_address", err: fmt.Errorf(`ent: validator failed for field "Ride.destination_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceAmount(); ok {
		if err := ride.PriceAmountValidator(v); err != nil {
			return &ValidationError{Name: "price_amount", err: fmt.Errorf(`ent: validator failed for field "Ride.price_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvailableSeats(); ok {
		if err := ride.AvailableSeatsValidator(v); err != nil {
			return &ValidationError{Name: "available_seats", err: fmt.Errorf(`ent: validator failed for field "Ride.available_seats": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalSeats(); ok {
		if err := ride.TotalSeatsValidator(v); err != nil {
			return &ValidationError{Name: "total_seats", err: fmt.Errorf(`ent: validator failed for field "Ride.total_seats": %w`, err)}
		}
	}
	if _u.mutation.DriverCleared() && len(_u.mutation.DriverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ride.driver"`)
	}
	return nil
}

func (_u *RideUpdateOne) sqlSave(ctx context.Context) (_node *Ride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ride.Table, ride.Columns, sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ride.FieldID)
		for _, f := range fields {
			if !ride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ride.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RideType(); ok {
		_spec.SetField(ride.FieldRideType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recurrence(); ok {
		_spec.SetField(ride.FieldRecurrence, field.TypeJSON, value)
	}
	if _u.mutation.RecurrenceCleared() {
		_spec.ClearField(ride.FieldRecurrence, field.TypeJSON)
	}
	if value, ok := _u.mutation.DepartureTime(); ok {
		_spec.SetField(ride.FieldDepartureTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ArrivalTime(); ok {
		_spec.SetField(ride.FieldArrivalTime, field.TypeTime, value)
	}
	if _u.mutation.ArrivalTimeCleared() {
		_spec.ClearField(ride.FieldArrivalTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(ride.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(ride.FieldDurationMinutes, field.TypeInt, value)
	}
	if _u.mutation.DurationMinutesCleared() {
		_spec.ClearField(ride.FieldDurationMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.OriginCity(); ok {
		_spec.SetField(ride.FieldOriginCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginAddress(); ok {
		_spec.SetField(ride.FieldOriginAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginLocationPoint(); ok {
		_spec.SetField(ride.FieldOriginLocationPoint, field.TypeString, value)
	}
	if _u.mutation.OriginLocationPointCleared() {
		_spec.ClearField(ride.FieldOriginLocationPoint, field.TypeString)
	}
	if value, ok := _u.mutation.DestinationCity(); ok {
		_spec.SetField(ride.FieldDestinationCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.DestinationAddress(); ok {
		_spec.SetField(ride.FieldDestinationAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.DestinationLocationPoint(); ok {
		_spec.SetField(ride.FieldDestinationLocationPoint, field.TypeString, value)
	}
	if _u.mutation.DestinationLocationPointCleared() {
		_spec.ClearField(ride.FieldDestinationLocationPoint, field.TypeString)
	}
	if value, ok := _u.mutation.PriceAmount(); ok {
		_spec.SetField(ride.FieldPriceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceAmount(); ok {
		_spec.AddField(ride.FieldPriceAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PriceCurrency(); ok {
		_spec.SetField(ride.FieldPriceCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvailableSeats(); ok {
		_spec.SetField(ride.FieldAvailableSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAvailableSeats(); ok {
		_spec.AddField(ride.FieldAvailableSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalSeats(); ok {
		_spec.SetField(ride.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSeats(); ok {
		_spec.AddField(ride.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amenities(); ok {
		_spec.SetField(ride.FieldAmenities, field.TypeJSON, value)
	}
	if _u.mutation.AmenitiesCleared() {
		_spec.ClearField(ride.FieldAmenities, field.TypeJSON)
	}
	if value, ok := _u.mutation.Stops(); ok {
		_spec.SetField(ride.FieldStops, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStops(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ride.FieldStops, value)
		})
	}
	if _u.mutation.StopsCleared() {
		_spec.ClearField(ride.FieldStops, field.TypeJSON)
	}
	if value, ok := _u.mutation.InstantConfirmation(); ok {
		_spec.SetField(ride.FieldInstantConfirmation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CancellationPolicy(); ok {
		_spec.SetField(ride.FieldCancellationPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ride.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ride.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ride.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ride.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DriverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.DriverTable,
			Columns: []string{ride.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DriverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.DriverTable,
			Columns: []string{ride.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehicleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.VehicleTable,
			Columns: []string{ride.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehicleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ride.VehicleTable,
			Columns: []string{ride.VehicleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ride.BookingsTable,
			Columns: []string{ride.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ride.BookingsTable,
			Columns: []string{ride.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ride.BookingsTable,
			Columns: []string{ride.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
