// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/slowtyper/poolie/backend/ent/booking"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/schema"
	"github.com/slowtyper/poolie/backend/ent/user"
	"github.com/slowtyper/poolie/backend/ent/vehicle"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookingFields := schema.Booking{}.Fields()
	_ = bookingFields
	// bookingDescRideID is the schema descriptor for ride_id field.
	bookingDescRideID := bookingFields[1].Descriptor()
	// booking.RideIDValidator is a validator for the "ride_id" field. It is called by the builders before save.
	booking.RideIDValidator = bookingDescRideID.Validators[0].(func(string) error)
	// bookingDescPassengerID is the schema descriptor for passenger_id field.
	bookingDescPassengerID := bookingFields[2].Descriptor()
	// booking.PassengerIDValidator is a validator for the "passenger_id" field. It is called by the builders before save.
	booking.PassengerIDValidator = bookingDescPassengerID.Validators[0].(func(string) error)
	// bookingDescStatus is the schema descriptor for status field.
	bookingDescStatus := bookingFields[3].Descriptor()
	// booking.DefaultStatus holds the default value on creation for the status field.
	booking.DefaultStatus = bookingDescStatus.Default.(string)
	// bookingDescPassengerCount is the schema descriptor for passenger_count field.
	bookingDescPassengerCount := bookingFields[4].Descriptor()
	// booking.PassengerCountValidator is a validator for the "passenger_count" field. It is called by the builders before save.
	booking.PassengerCountValidator = bookingDescPassengerCount.Validators[0].(func(int) error)
	// bookingDescTotalPriceAmount is the schema descriptor for total_price_amount field.
	bookingDescTotalPriceAmount := bookingFields[5].Descriptor()
	// booking.TotalPriceAmountValidator is a validator for the "total_price_amount" field. It is called by the builders before save.
	booking.TotalPriceAmountValidator = bookingDescTotalPriceAmount.Validators[0].(func(int64) error)
	// bookingDescTotalPriceCurrency is the schema descriptor for total_price_currency field.
	bookingDescTotalPriceCurrency := bookingFields[6].Descriptor()
	// booking.DefaultTotalPriceCurrency holds the default value on creation for the total_price_currency field.
	booking.DefaultTotalPriceCurrency = bookingDescTotalPriceCurrency.Default.(string)
	// bookingDescCreatedAt is the schema descriptor for created_at field.
	bookingDescCreatedAt := bookingFields[9].Descriptor()
	// booking.DefaultCreatedAt holds the default value on creation for the created_at field.
	booking.DefaultCreatedAt = bookingDescCreatedAt.Default.(func() time.Time)
	// bookingDescUpdatedAt is the schema descriptor for updated_at field.
	bookingDescUpdatedAt := bookingFields[11].Descriptor()
	// booking.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	booking.DefaultUpdatedAt = bookingDescUpdatedAt.Default.(func() time.Time)
	// booking.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	booking.UpdateDefaultUpdatedAt = bookingDescUpdatedAt.UpdateDefault.(func() time.Time)
	rideFields := schema.Ride{}.Fields()
	_ = rideFields
	// rideDescDriverID is the schema descriptor for driver_id field.
	rideDescDriverID := rideFields[1].Descriptor()
	// ride.DriverIDValidator is a validator for the "driver_id" field. It is called by the builders before save.
	ride.DriverIDValidator = rideDescDriverID.Validators[0].(func(string) error)
	// rideDescType is the schema descriptor for type field.
	rideDescType := rideFields[3].Descriptor()
	// ride.DefaultType holds the default value on creation for the type field.
	ride.DefaultType = rideDescType.Default.(string)
	// rideDescRideType is the schema descriptor for ride_type field.
	rideDescRideType := rideFields[4].Descriptor()
	// ride.DefaultRideType holds the default value on creation for the ride_type field.
	ride.DefaultRideType = rideDescRideType.Default.(string)
	// rideDescDurationMinutes is the schema descriptor for duration_minutes field.
	rideDescDurationMinutes := rideFields[8].Descriptor()
	// ride.DurationMinutesValidator is a validator for the "duration_minutes" field. It is called by the builders before save.
	ride.DurationMinutesValidator = rideDescDurationMinutes.Validators[0].(func(int) error)
	// rideDescOriginCity is the schema descriptor for origin_city field.
	rideDescOriginCity := rideFields[9].Descriptor()
	// ride.OriginCityValidator is a validator for the "origin_city" field. It is called by the builders before save.
	ride.OriginCityValidator = rideDescOriginCity.Validators[0].(func(string) error)
	// rideDescOriginAddress is the schema descriptor for origin_address field.
	rideDescOriginAddress := rideFields[10].Descriptor()
	// ride.OriginAddressValidator is a validator for the "origin_address" field. It is called by the builders before save.
	ride.OriginAddressValidator = rideDescOriginAddress.Validators[0].(func(string) error)
	// rideDescDestinationCity is the schema descriptor for destination_city field.
	rideDescDestinationCity := rideFields[12].Descriptor()
	// ride.DestinationCityValidator is a validator for the "destination_city" field. It is called by the builders before save.
	ride.DestinationCityValidator = rideDescDestinationCity.Validators[0].(func(string) error)
	// rideDescDestinationAddress is the schema descriptor for destination_address field.
	rideDescDestinationAddress := rideFields[13].Descriptor()
	// ride.DestinationAddressValidator is a validator for the "destination_address" field. It is called by the builders before save.
	ride.DestinationAddressValidator = rideDescDestinationAddress.Validators[0].(func(string) error)
	// rideDescPriceAmount is the schema descriptor for price_amount field.
	rideDescPriceAmount := rideFields[15].Descriptor()
	// ride.PriceAmountValidator is a validator for the "price_amount" field. It is called by the builders before save.
	ride.PriceAmountValidator = rideDescPriceAmount.Validators[0].(func(int64) error)
	// rideDescPriceCurrency is the schema descriptor for price_currency field.
	rideDescPriceCurrency := rideFields[16].Descriptor()
	// ride.DefaultPriceCurrency holds the default value on creation for the price_currency field.
	ride.DefaultPriceCurrency = rideDescPriceCurrency.Default.(string)
	// rideDescAvailableSeats is the schema descriptor for available_seats field.
	rideDescAvailableSeats := rideFields[17].Descriptor()
	// ride.AvailableSeatsValidator is a validator for the "available_seats" field. It is called by the builders before save.
	ride.AvailableSeatsValidator = rideDescAvailableSeats.Validators[0].(func(int) error)
	// rideDescTotalSeats is the schema descriptor for total_seats field.
	rideDescTotalSeats := rideFields[18].Descriptor()
	// ride.TotalSeatsValidator is a validator for the "total_seats" field. It is called by the builders before save.
	ride.TotalSeatsValidator = rideDescTotalSeats.Validators[0].(func(int) error)
	// rideDescInstantConfirmation is the schema descriptor for instant_confirmation field.
	rideDescInstantConfirmation := rideFields[21].Descriptor()
	// ride.DefaultInstantConfirmation holds the default value on creation for the instant_confirmation field.
	ride.DefaultInstantConfirmation = rideDescInstantConfirmation.Default.(bool)
	// rideDescCancellationPolicy is the schema descriptor for cancellation_policy field.
	rideDescCancellationPolicy := rideFields[22].Descriptor()
	// ride.DefaultCancellationPolicy holds the default value on creation for the cancellation_policy field.
	ride.DefaultCancellationPolicy = rideDescCancellationPolicy.Default.(string)
	// rideDescStatus is the schema descriptor for status field.
	rideDescStatus := rideFields[24].Descriptor()
	// ride.DefaultStatus holds the default value on creation for the status field.
	ride.DefaultStatus = rideDescStatus.Default.(string)
	// rideDescCreatedAt is the schema descriptor for created_at field.
	rideDescCreatedAt := rideFields[25].Descriptor()
	// ride.DefaultCreatedAt holds the default value on creation for the created_at field.
	ride.DefaultCreatedAt = rideDescCreatedAt.Default.(func() time.Time)
	// rideDescUpdatedAt is the schema descriptor for updated_at field.
	rideDescUpdatedAt := rideFields[26].Descriptor()
	// ride.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ride.DefaultUpdatedAt = rideDescUpdatedAt.Default.(func() time.Time)
	// ride.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ride.UpdateDefaultUpdatedAt = rideDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[5].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescExperienceLevel is the schema descriptor for experience_level field.
	userDescExperienceLevel := userFields[6].Descriptor()
	// user.DefaultExperienceLevel holds the default value on creation for the experience_level field.
	user.DefaultExperienceLevel = userDescExperienceLevel.Default.(string)
	// userDescRating is the schema descriptor for rating field.
	userDescRating := userFields[7].Descriptor()
	// user.DefaultRating holds the default value on creation for the rating field.
	user.DefaultRating = userDescRating.Default.(float64)
	// user.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	user.RatingValidator = func() func(float64) error {
		validators := userDescRating.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(rating float64) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRatingCount is the schema descriptor for rating_count field.
	userDescRatingCount := userFields[8].Descriptor()
	// user.DefaultRatingCount holds the default value on creation for the rating_count field.
	user.DefaultRatingCount = userDescRatingCount.Default.(int)
	// user.RatingCountValidator is a validator for the "rating_count" field. It is called by the builders before save.
	user.RatingCountValidator = userDescRatingCount.Validators[0].(func(int) error)
	// userDescIsVerified is the schema descriptor for is_verified field.
	userDescIsVerified := userFields[11].Descriptor()
	// user.DefaultIsVerified holds the default value on creation for the is_verified field.
	user.DefaultIsVerified = userDescIsVerified.Default.(bool)
	// userDescVerifiedID is the schema descriptor for verified_id field.
	userDescVerifiedID := userFields[12].Descriptor()
	// user.DefaultVerifiedID holds the default value on creation for the verified_id field.
	user.DefaultVerifiedID = userDescVerifiedID.Default.(bool)
	// userDescConfirmedEmail is the schema descriptor for confirmed_email field.
	userDescConfirmedEmail := userFields[13].Descriptor()
	// user.DefaultConfirmedEmail holds the default value on creation for the confirmed_email field.
	user.DefaultConfirmedEmail = userDescConfirmedEmail.Default.(bool)
	// userDescConfirmedPhone is the schema descriptor for confirmed_phone field.
	userDescConfirmedPhone := userFields[14].Descriptor()
	// user.DefaultConfirmedPhone holds the default value on creation for the confirmed_phone field.
	user.DefaultConfirmedPhone = userDescConfirmedPhone.Default.(bool)
	// userDescMembershipType is the schema descriptor for membership_type field.
	userDescMembershipType := userFields[17].Descriptor()
	// user.DefaultMembershipType holds the default value on creation for the membership_type field.
	user.DefaultMembershipType = userDescMembershipType.Default.(string)
	// userDescPublishedRides is the schema descriptor for published_rides field.
	userDescPublishedRides := userFields[18].Descriptor()
	// user.DefaultPublishedRides holds the default value on creation for the published_rides field.
	user.DefaultPublishedRides = userDescPublishedRides.Default.(int)
	// user.PublishedRidesValidator is a validator for the "published_rides" field. It is called by the builders before save.
	user.PublishedRidesValidator = userDescPublishedRides.Validators[0].(func(int) error)
	// userDescCompletedRides is the schema descriptor for completed_rides field.
	userDescCompletedRides := userFields[19].Descriptor()
	// user.DefaultCompletedRides holds the default value on creation for the completed_rides field.
	user.DefaultCompletedRides = userDescCompletedRides.Default.(int)
	// user.CompletedRidesValidator is a validator for the "completed_rides" field. It is called by the builders before save.
	user.CompletedRidesValidator = userDescCompletedRides.Validators[0].(func(int) error)
	// userDescNeverCancels is the schema descriptor for never_cancels field.
	userDescNeverCancels := userFields[20].Descriptor()
	// user.DefaultNeverCancels holds the default value on creation for the never_cancels field.
	user.DefaultNeverCancels = userDescNeverCancels.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[21].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[22].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	vehicleFields := schema.Vehicle{}.Fields()
	_ = vehicleFields
	// vehicleDescUserID is the schema descriptor for user_id field.
	vehicleDescUserID := vehicleFields[1].Descriptor()
	// vehicle.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	vehicle.UserIDValidator = vehicleDescUserID.Validators[0].(func(string) error)
	// vehicleDescMake is the schema descriptor for make field.
	vehicleDescMake := vehicleFields[2].Descriptor()
	// vehicle.MakeValidator is a validator for the "make" field. It is called by the builders before save.
	vehicle.MakeValidator = vehicleDescMake.Validators[0].(func(string) error)
	// vehicleDescModel is the schema descriptor for model field.
	vehicleDescModel := vehicleFields[3].Descriptor()
	// vehicle.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	vehicle.ModelValidator = vehicleDescModel.Validators[0].(func(string) error)
	// vehicleDescColor is the schema descriptor for color field.
	vehicleDescColor := vehicleFields[4].Descriptor()
	// vehicle.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	vehicle.ColorValidator = vehicleDescColor.Validators[0].(func(string) error)
	// vehicleDescYear is the schema descriptor for year field.
	vehicleDescYear := vehicleFields[6].Descriptor()
	// vehicle.YearValidator is a validator for the "year" field. It is called by the builders before save.
	vehicle.YearValidator = vehicleDescYear.Validators[0].(func(int) error)
	// vehicleDescCreatedAt is the schema descriptor for created_at field.
	vehicleDescCreatedAt := vehicleFields[7].Descriptor()
	// vehicle.DefaultCreatedAt holds the default value on creation for the created_at field.
	vehicle.DefaultCreatedAt = vehicleDescCreatedAt.Default.(func() time.Time)
	// vehicleDescUpdatedAt is the schema descriptor for updated_at field.
	vehicleDescUpdatedAt := vehicleFields[8].Descriptor()
	// vehicle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vehicle.DefaultUpdatedAt = vehicleDescUpdatedAt.Default.(func() time.Time)
	// vehicle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vehicle.UpdateDefaultUpdatedAt = vehicleDescUpdatedAt.UpdateDefault.(func() time.Time)
}
