// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/slowtyper/poolie/backend/ent/booking"
	"github.com/slowtyper/poolie/backend/ent/predicate"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/user"
	"github.com/slowtyper/poolie/backend/ent/vehicle"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdate) SetPhone(v string) *UserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePhone(v *string) *UserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdate) ClearPhone() *UserUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAge sets the "age" field.
func (_u *UserUpdate) SetAge(v int) *UserUpdate {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAge(v *int) *UserUpdate {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *UserUpdate) AddAge(v int) *UserUpdate {
	_u.mutation.AddAge(v)
	return _u
}

// ClearAge clears the value of the "age" field.
func (_u *UserUpdate) ClearAge() *UserUpdate {
	_u.mutation.ClearAge()
	return _u
}

// SetExperienceLevel sets the "experience_level" field.
func (_u *UserUpdate) SetExperienceLevel(v string) *UserUpdate {
	_u.mutation.SetExperienceLevel(v)
	return _u
}

// SetNillableExperienceLevel sets the "experience_level" field if the given value is not nil.
func (_u *UserUpdate) SetNillableExperienceLevel(v *string) *UserUpdate {
	if v != nil {
		_u.SetExperienceLevel(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *UserUpdate) SetRating(v float64) *UserUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRating(v *float64) *UserUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *UserUpdate) AddRating(v float64) *UserUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetRatingCount sets the "rating_count" field.
func (_u *UserUpdate) SetRatingCount(v int) *UserUpdate {
	_u.mutation.ResetRatingCount()
	_u.mutation.SetRatingCount(v)
	return _u
}

// SetNillableRatingCount sets the "rating_count" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRatingCount(v *int) *UserUpdate {
	if v != nil {
		_u.SetRatingCount(*v)
	}
	return _u
}

// AddRatingCount adds value to the "rating_count" field.
func (_u *UserUpdate) AddRatingCount(v int) *UserUpdate {
	_u.mutation.AddRatingCount(v)
	return _u
}

// SetDrivingRating sets the "driving_rating" field.
func (_u *UserUpdate) SetDrivingRating(v string) *UserUpdate {
	_u.mutation.SetDrivingRating(v)
	return _u
}

// SetNillableDrivingRating sets the "driving_rating" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDrivingRating(v *string) *UserUpdate {
	if v != nil {
		_u.SetDrivingRating(*v)
	}
	return _u
}

// ClearDrivingRating clears the value of the "driving_rating" field.
func (_u *UserUpdate) ClearDrivingRating() *UserUpdate {
	_u.mutation.ClearDrivingRating()
	return _u
}

// SetProfilePictureURL sets the "profile_picture_url" field.
func (_u *UserUpdate) SetProfilePictureURL(v string) *UserUpdate {
	_u.mutation.SetProfilePictureURL(v)
	return _u
}

// SetNillableProfilePictureURL sets the "profile_picture_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableProfilePictureURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetProfilePictureURL(*v)
	}
	return _u
}

// ClearProfilePictureURL clears the value of the "profile_picture_url" field.
func (_u *UserUpdate) ClearProfilePictureURL() *UserUpdate {
	_u.mutation.ClearProfilePictureURL()
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *UserUpdate) SetIsVerified(v bool) *UserUpdate {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsVerified(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetVerifiedID sets the "verified_id" field.
func (_u *UserUpdate) SetVerifiedID(v bool) *UserUpdate {
	_u.mutation.SetVerifiedID(v)
	return _u
}

// SetNillableVerifiedID sets the "verified_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableVerifiedID(v *bool) *UserUpdate {
	if v != nil {
		_u.SetVerifiedID(*v)
	}
	return _u
}

// SetConfirmedEmail sets the "confirmed_email" field.
func (_u *UserUpdate) SetConfirmedEmail(v bool) *UserUpdate {
	_u.mutation.SetConfirmedEmail(v)
	return _u
}

// SetNillableConfirmedEmail sets the "confirmed_email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableConfirmedEmail(v *bool) *UserUpdate {
	if v != nil {
		_u.SetConfirmedEmail(*v)
	}
	return _u
}

// SetConfirmedPhone sets the "confirmed_phone" field.
func (_u *UserUpdate) SetConfirmedPhone(v bool) *UserUpdate {
	_u.mutation.SetConfirmedPhone(v)
	return _u
}

// SetNillableConfirmedPhone sets the "confirmed_phone" field if the given value is not nil.
func (_u *UserUpdate) SetNillableConfirmedPhone(v *bool) *UserUpdate {
	if v != nil {
		_u.SetConfirmedPhone(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *UserUpdate) SetBio(v string) *UserUpdate {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBio(v *string) *UserUpdate {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// ClearBio clears the value of the "bio" field.
func (_u *UserUpdate) ClearBio() *UserUpdate {
	_u.mutation.ClearBio()
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *UserUpdate) SetPreferences(v map[string]interface{}) *UserUpdate {
	_u.mutation.SetPreferences(v)
	return _u
}

// ClearPreferences clears the value of the "preferences" field.
func (_u *UserUpdate) ClearPreferences() *UserUpdate {
	_u.mutation.ClearPreferences()
	return _u
}

// SetMembershipType sets the "membership_type" field.
func (_u *UserUpdate) SetMembershipType(v string) *UserUpdate {
	_u.mutation.SetMembershipType(v)
	return _u
}

// SetNillableMembershipType sets the "membership_type" field if the given value is not nil.
func (_u *UserUpdate) SetNillableMembershipType(v *string) *UserUpdate {
	if v != nil {
		_u.SetMembershipType(*v)
	}
	return _u
}

// SetPublishedRides sets the "published_rides" field.
func (_u *UserUpdate) SetPublishedRides(v int) *UserUpdate {
	_u.mutation.ResetPublishedRides()
	_u.mutation.SetPublishedRides(v)
	return _u
}

// SetNillablePublishedRides sets the "published_rides" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePublishedRides(v *int) *UserUpdate {
	if v != nil {
		_u.SetPublishedRides(*v)
	}
	return _u
}

// AddPublishedRides adds value to the "published_rides" field.
func (_u *UserUpdate) AddPublishedRides(v int) *UserUpdate {
	_u.mutation.AddPublishedRides(v)
	return _u
}

// SetCompletedRides sets the "completed_rides" field.
func (_u *UserUpdate) SetCompletedRides(v int) *UserUpdate {
	_u.mutation.ResetCompletedRides()
	_u.mutation.SetCompletedRides(v)
	return _u
}

// SetNillableCompletedRides sets the "completed_rides" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCompletedRides(v *int) *UserUpdate {
	if v != nil {
		_u.SetCompletedRides(*v)
	}
	return _u
}

// AddCompletedRides adds value to the "completed_rides" field.
func (_u *UserUpdate) AddCompletedRides(v int) *UserUpdate {
	_u.mutation.AddCompletedRides(v)
	return _u
}

// SetNeverCancels sets the "never_cancels" field.
func (_u *UserUpdate) SetNeverCancels(v bool) *UserUpdate {
	_u.mutation.SetNeverCancels(v)
	return _u
}

// SetNillableNeverCancels sets the "never_cancels" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNeverCancels(v *bool) *UserUpdate {
	if v != nil {
		_u.SetNeverCancels(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRideIDs adds the "rides" edge to the Ride entity by IDs.
func (_u *UserUpdate) AddRideIDs(ids ...string) *UserUpdate {
	_u.mutation.AddRideIDs(ids...)
	return _u
}

// AddRides adds the "rides" edges to the Ride entity.
func (_u *UserUpdate) AddRides(v ...*Ride) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRideIDs(ids...)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *UserUpdate) AddBookingIDs(ids ...string) *UserUpdate {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *UserUpdate) AddBookings(v ...*Booking) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// AddVehicleIDs adds the "vehicles" edge to the Vehicle entity by IDs.
func (_u *UserUpdate) AddVehicleIDs(ids ...string) *UserUpdate {
	_u.mutation.AddVehicleIDs(ids...)
	return _u
}

// AddVehicles adds the "vehicles" edges to the Vehicle entity.
func (_u *UserUpdate) AddVehicles(v ...*Vehicle) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVehicleIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRides clears all "rides" edges to the Ride entity.
func (_u *UserUpdate) ClearRides() *UserUpdate {
	_u.mutation.ClearRides()
	return _u
}

// RemoveRideIDs removes the "rides" edge to Ride entities by IDs.
func (_u *UserUpdate) RemoveRideIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveRideIDs(ids...)
	return _u
}

// RemoveRides removes "rides" edges to Ride entities.
func (_u *UserUpdate) RemoveRides(v ...*Ride) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRideIDs(ids...)
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *UserUpdate) ClearBookings() *UserUpdate {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *UserUpdate) RemoveBookingIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *UserUpdate) RemoveBookings(v ...*Booking) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// ClearVehicles clears all "vehicles" edges to the Vehicle entity.
func (_u *UserUpdate) ClearVehicles() *UserUpdate {
	_u.mutation.ClearVehicles()
	return _u
}

// RemoveVehicleIDs removes the "vehicles" edge to Vehicle entities by IDs.
func (_u *UserUpdate) RemoveVehicleIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveVehicleIDs(ids...)
	return _u
}

// RemoveVehicles removes "vehicles" edges to Vehicle entities.
func (_u *UserUpdate) RemoveVehicles(v ...*Vehicle) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVehicleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Age(); ok {
		if err := user.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`ent: validator failed for field "User.age": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := user.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "User.rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RatingCount(); ok {
		if err := user.RatingCountValidator(v); err != nil {
			return &ValidationError{Name: "rating_count", err: fmt.Errorf(`ent: validator failed for field "User.rating_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublishedRides(); ok {
		if err := user.PublishedRidesValidator(v); err != nil {
			return &ValidationError{Name: "published_rides", err: fmt.Errorf(`ent: validator failed for field "User.published_rides": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompletedRides(); ok {
		if err := user.CompletedRidesValidator(v); err != nil {
			return &ValidationError{Name: "completed_rides", err: fmt.Errorf(`ent: validator failed for field "User.completed_rides": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(user.FieldAge, field.TypeInt, value)
	}
	if _u.mutation.AgeCleared() {
		_spec.ClearField(user.FieldAge, field.TypeInt)
	}
	if value, ok := _u.mutation.ExperienceLevel(); ok {
		_spec.SetField(user.FieldExperienceLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(user.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(user.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RatingCount(); ok {
		_spec.SetField(user.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRatingCount(); ok {
		_spec.AddField(user.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DrivingRating(); ok {
		_spec.SetField(user.FieldDrivingRating, field.TypeString, value)
	}
	if _u.mutation.DrivingRatingCleared() {
		_spec.ClearField(user.FieldDrivingRating, field.TypeString)
	}
	if value, ok := _u.mutation.ProfilePictureURL(); ok {
		_spec.SetField(user.FieldProfilePictureURL, field.TypeString, value)
	}
	if _u.mutation.ProfilePictureURLCleared() {
		_spec.ClearField(user.FieldProfilePictureURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(user.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VerifiedID(); ok {
		_spec.SetField(user.FieldVerifiedID, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfirmedEmail(); ok {
		_spec.SetField(user.FieldConfirmedEmail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfirmedPhone(); ok {
		_spec.SetField(user.FieldConfirmedPhone, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(user.FieldBio, field.TypeString, value)
	}
	if _u.mutation.BioCleared() {
		_spec.ClearField(user.FieldBio, field.TypeString)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
	}
	if _u.mutation.PreferencesCleared() {
		_spec.ClearField(user.FieldPreferences, field.TypeJSON)
	}
	if value, ok := _u.mutation.MembershipType(); ok {
		_spec.SetField(user.FieldMembershipType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishedRides(); ok {
		_spec.SetField(user.FieldPublishedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublishedRides(); ok {
		_spec.AddField(user.FieldPublishedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedRides(); ok {
		_spec.SetField(user.FieldCompletedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedRides(); ok {
		_spec.AddField(user.FieldCompletedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NeverCancels(); ok {
		_spec.SetField(user.FieldNeverCancels, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RidesTable,
			Columns: []string{user.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRidesIDs(); len(nodes) > 0 && !_u.mutation.RidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RidesTable,
			Columns: []string{user.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RidesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RidesTable,
			Columns: []string{user.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.VehiclesTable,
			Columns: []string{user.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVehiclesIDs(); len(nodes) > 0 && !_u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.VehiclesTable,
			Columns: []string{user.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehiclesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.VehiclesTable,
			Columns: []string{user.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdateOne) SetPhone(v string) *UserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePhone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdateOne) ClearPhone() *UserUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAge sets the "age" field.
func (_u *UserUpdateOne) SetAge(v int) *UserUpdateOne {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAge(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *UserUpdateOne) AddAge(v int) *UserUpdateOne {
	_u.mutation.AddAge(v)
	return _u
}

// ClearAge clears the value of the "age" field.
func (_u *UserUpdateOne) ClearAge() *UserUpdateOne {
	_u.mutation.ClearAge()
	return _u
}

// SetExperienceLevel sets the "experience_level" field.
func (_u *UserUpdateOne) SetExperienceLevel(v string) *UserUpdateOne {
	_u.mutation.SetExperienceLevel(v)
	return _u
}

// SetNillableExperienceLevel sets the "experience_level" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableExperienceLevel(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetExperienceLevel(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *UserUpdateOne) SetRating(v float64) *UserUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRating(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *UserUpdateOne) AddRating(v float64) *UserUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetRatingCount sets the "rating_count" field.
func (_u *UserUpdateOne) SetRatingCount(v int) *UserUpdateOne {
	_u.mutation.ResetRatingCount()
	_u.mutation.SetRatingCount(v)
	return _u
}

// SetNillableRatingCount sets the "rating_count" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRatingCount(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetRatingCount(*v)
	}
	return _u
}

// AddRatingCount adds value to the "rating_count" field.
func (_u *UserUpdateOne) AddRatingCount(v int) *UserUpdateOne {
	_u.mutation.AddRatingCount(v)
	return _u
}

// SetDrivingRating sets the "driving_rating" field.
func (_u *UserUpdateOne) SetDrivingRating(v string) *UserUpdateOne {
	_u.mutation.SetDrivingRating(v)
	return _u
}

// SetNillableDrivingRating sets the "driving_rating" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDrivingRating(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetDrivingRating(*v)
	}
	return _u
}

// ClearDrivingRating clears the value of the "driving_rating" field.
func (_u *UserUpdateOne) ClearDrivingRating() *UserUpdateOne {
	_u.mutation.ClearDrivingRating()
	return _u
}

// SetProfilePictureURL sets the "profile_picture_url" field.
func (_u *UserUpdateOne) SetProfilePictureURL(v string) *UserUpdateOne {
	_u.mutation.SetProfilePictureURL(v)
	return _u
}

// SetNillableProfilePictureURL sets the "profile_picture_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableProfilePictureURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetProfilePictureURL(*v)
	}
	return _u
}

// ClearProfilePictureURL clears the value of the "profile_picture_url" field.
func (_u *UserUpdateOne) ClearProfilePictureURL() *UserUpdateOne {
	_u.mutation.ClearProfilePictureURL()
	return _u
}

// SetIsVerified sets the "is_verified" field.
func (_u *UserUpdateOne) SetIsVerified(v bool) *UserUpdateOne {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsVerified(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetVerifiedID sets the "verified_id" field.
func (_u *UserUpdateOne) SetVerifiedID(v bool) *UserUpdateOne {
	_u.mutation.SetVerifiedID(v)
	return _u
}

// SetNillableVerifiedID sets the "verified_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableVerifiedID(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetVerifiedID(*v)
	}
	return _u
}

// SetConfirmedEmail sets the "confirmed_email" field.
func (_u *UserUpdateOne) SetConfirmedEmail(v bool) *UserUpdateOne {
	_u.mutation.SetConfirmedEmail(v)
	return _u
}

// SetNillableConfirmedEmail sets the "confirmed_email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableConfirmedEmail(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetConfirmedEmail(*v)
	}
	return _u
}

// SetConfirmedPhone sets the "confirmed_phone" field.
func (_u *UserUpdateOne) SetConfirmedPhone(v bool) *UserUpdateOne {
	_u.mutation.SetConfirmedPhone(v)
	return _u
}

// SetNillableConfirmedPhone sets the "confirmed_phone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableConfirmedPhone(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetConfirmedPhone(*v)
	}
	return _u
}

// SetBio sets the "bio" field.
func (_u *UserUpdateOne) SetBio(v string) *UserUpdateOne {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBio(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// ClearBio clears the value of the "bio" field.
func (_u *UserUpdateOne) ClearBio() *UserUpdateOne {
	_u.mutation.ClearBio()
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *UserUpdateOne) SetPreferences(v map[string]interface{}) *UserUpdateOne {
	_u.mutation.SetPreferences(v)
	return _u
}

// ClearPreferences clears the value of the "preferences" field.
func (_u *UserUpdateOne) ClearPreferences() *UserUpdateOne {
	_u.mutation.ClearPreferences()
	return _u
}

// SetMembershipType sets the "membership_type" field.
func (_u *UserUpdateOne) SetMembershipType(v string) *UserUpdateOne {
	_u.mutation.SetMembershipType(v)
	return _u
}

// SetNillableMembershipType sets the "membership_type" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableMembershipType(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetMembershipType(*v)
	}
	return _u
}

// SetPublishedRides sets the "published_rides" field.
func (_u *UserUpdateOne) SetPublishedRides(v int) *UserUpdateOne {
	_u.mutation.ResetPublishedRides()
	_u.mutation.SetPublishedRides(v)
	return _u
}

// SetNillablePublishedRides sets the "published_rides" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePublishedRides(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetPublishedRides(*v)
	}
	return _u
}

// AddPublishedRides adds value to the "published_rides" field.
func (_u *UserUpdateOne) AddPublishedRides(v int) *UserUpdateOne {
	_u.mutation.AddPublishedRides(v)
	return _u
}

// SetCompletedRides sets the "completed_rides" field.
func (_u *UserUpdateOne) SetCompletedRides(v int) *UserUpdateOne {
	_u.mutation.ResetCompletedRides()
	_u.mutation.SetCompletedRides(v)
	return _u
}

// SetNillableCompletedRides sets the "completed_rides" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCompletedRides(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetCompletedRides(*v)
	}
	return _u
}

// AddCompletedRides adds value to the "completed_rides" field.
func (_u *UserUpdateOne) AddCompletedRides(v int) *UserUpdateOne {
	_u.mutation.AddCompletedRides(v)
	return _u
}

// SetNeverCancels sets the "never_cancels" field.
func (_u *UserUpdateOne) SetNeverCancels(v bool) *UserUpdateOne {
	_u.mutation.SetNeverCancels(v)
	return _u
}

// SetNillableNeverCancels sets the "never_cancels" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNeverCancels(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetNeverCancels(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRideIDs adds the "rides" edge to the Ride entity by IDs.
func (_u *UserUpdateOne) AddRideIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddRideIDs(ids...)
	return _u
}

// AddRides adds the "rides" edges to the Ride entity.
func (_u *UserUpdateOne) AddRides(v ...*Ride) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRideIDs(ids...)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *UserUpdateOne) AddBookingIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *UserUpdateOne) AddBookings(v ...*Booking) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// AddVehicleIDs adds the "vehicles" edge to the Vehicle entity by IDs.
func (_u *UserUpdateOne) AddVehicleIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddVehicleIDs(ids...)
	return _u
}

// AddVehicles adds the "vehicles" edges to the Vehicle entity.
func (_u *UserUpdateOne) AddVehicles(v ...*Vehicle) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVehicleIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRides clears all "rides" edges to the Ride entity.
func (_u *UserUpdateOne) ClearRides() *UserUpdateOne {
	_u.mutation.ClearRides()
	return _u
}

// RemoveRideIDs removes the "rides" edge to Ride entities by IDs.
func (_u *UserUpdateOne) RemoveRideIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveRideIDs(ids...)
	return _u
}

// RemoveRides removes "rides" edges to Ride entities.
func (_u *UserUpdateOne) RemoveRides(v ...*Ride) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRideIDs(ids...)
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *UserUpdateOne) ClearBookings() *UserUpdateOne {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *UserUpdateOne) RemoveBookingIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *UserUpdateOne) RemoveBookings(v ...*Booking) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// ClearVehicles clears all "vehicles" edges to the Vehicle entity.
func (_u *UserUpdateOne) ClearVehicles() *UserUpdateOne {
	_u.mutation.ClearVehicles()
	return _u
}

// RemoveVehicleIDs removes the "vehicles" edge to Vehicle entities by IDs.
func (_u *UserUpdateOne) RemoveVehicleIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveVehicleIDs(ids...)
	return _u
}

// RemoveVehicles removes "vehicles" edges to Vehicle entities.
func (_u *UserUpdateOne) RemoveVehicles(v ...*Vehicle) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVehicleIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Age(); ok {
		if err := user.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`ent: validator failed for field "User.age": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := user.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "User.rating": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RatingCount(); ok {
		if err := user.RatingCountValidator(v); err != nil {
			return &ValidationError{Name: "rating_count", err: fmt.Errorf(`ent: validator failed for field "User.rating_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublishedRides(); ok {
		if err := user.PublishedRidesValidator(v); err != nil {
			return &ValidationError{Name: "published_rides", err: fmt.Errorf(`ent: validator failed for field "User.published_rides": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CompletedRides(); ok {
		if err := user.CompletedRidesValidator(v); err != nil {
			return &ValidationError{Name: "completed_rides", err: fmt.Errorf(`ent: validator failed for field "User.completed_rides": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(user.FieldAge, field.TypeInt, value)
	}
	if _u.mutation.AgeCleared() {
		_spec.ClearField(user.FieldAge, field.TypeInt)
	}
	if value, ok := _u.mutation.ExperienceLevel(); ok {
		_spec.SetField(user.FieldExperienceLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(user.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(user.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RatingCount(); ok {
		_spec.SetField(user.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRatingCount(); ok {
		_spec.AddField(user.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DrivingRating(); ok {
		_spec.SetField(user.FieldDrivingRating, field.TypeString, value)
	}
	if _u.mutation.DrivingRatingCleared() {
		_spec.ClearField(user.FieldDrivingRating, field.TypeString)
	}
	if value, ok := _u.mutation.ProfilePictureURL(); ok {
		_spec.SetField(user.FieldProfilePictureURL, field.TypeString, value)
	}
	if _u.mutation.ProfilePictureURLCleared() {
		_spec.ClearField(user.FieldProfilePictureURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(user.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VerifiedID(); ok {
		_spec.SetField(user.FieldVerifiedID, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfirmedEmail(); ok {
		_spec.SetField(user.FieldConfirmedEmail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfirmedPhone(); ok {
		_spec.SetField(user.FieldConfirmedPhone, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(user.FieldBio, field.TypeString, value)
	}
	if _u.mutation.BioCleared() {
		_spec.ClearField(user.FieldBio, field.TypeString)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
	}
	if _u.mutation.PreferencesCleared() {
		_spec.ClearField(user.FieldPreferences, field.TypeJSON)
	}
	if value, ok := _u.mutation.MembershipType(); ok {
		_spec.SetField(user.FieldMembershipType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishedRides(); ok {
		_spec.SetField(user.FieldPublishedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublishedRides(); ok {
		_spec.AddField(user.FieldPublishedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedRides(); ok {
		_spec.SetField(user.FieldCompletedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedRides(); ok {
		_spec.AddField(user.FieldCompletedRides, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NeverCancels(); ok {
		_spec.SetField(user.FieldNeverCancels, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RidesTable,
			Columns: []string{user.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRidesIDs(); len(nodes) > 0 && !_u.mutation.RidesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RidesTable,
			Columns: []string{user.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RidesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RidesTable,
			Columns: []string{user.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.VehiclesTable,
			Columns: []string{user.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVehiclesIDs(); len(nodes) > 0 && !_u.mutation.VehiclesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.VehiclesTable,
			Columns: []string{user.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VehiclesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.VehiclesTable,
			Columns: []string{user.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
