// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/slowtyper/poolie/backend/ent/booking"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/user"
	"github.com/slowtyper/poolie/backend/ent/vehicle"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *UserCreate) SetPhone(v string) *UserCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *UserCreate) SetNillablePhone(v *string) *UserCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetAge sets the "age" field.
func (_c *UserCreate) SetAge(v int) *UserCreate {
	_c.mutation.SetAge(v)
	return _c
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_c *UserCreate) SetNillableAge(v *int) *UserCreate {
	if v != nil {
		_c.SetAge(*v)
	}
	return _c
}

// SetExperienceLevel sets the "experience_level" field.
func (_c *UserCreate) SetExperienceLevel(v string) *UserCreate {
	_c.mutation.SetExperienceLevel(v)
	return _c
}

// SetNillableExperienceLevel sets the "experience_level" field if the given value is not nil.
func (_c *UserCreate) SetNillableExperienceLevel(v *string) *UserCreate {
	if v != nil {
		_c.SetExperienceLevel(*v)
	}
	return _c
}

// SetRating sets the "rating" field.
func (_c *UserCreate) SetRating(v float64) *UserCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *UserCreate) SetNillableRating(v *float64) *UserCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetRatingCount sets the "rating_count" field.
func (_c *UserCreate) SetRatingCount(v int) *UserCreate {
	_c.mutation.SetRatingCount(v)
	return _c
}

// SetNillableRatingCount sets the "rating_count" field if the given value is not nil.
func (_c *UserCreate) SetNillableRatingCount(v *int) *UserCreate {
	if v != nil {
		_c.SetRatingCount(*v)
	}
	return _c
}

// SetDrivingRating sets the "driving_rating" field.
func (_c *UserCreate) SetDrivingRating(v string) *UserCreate {
	_c.mutation.SetDrivingRating(v)
	return _c
}

// SetNillableDrivingRating sets the "driving_rating" field if the given value is not nil.
func (_c *UserCreate) SetNillableDrivingRating(v *string) *UserCreate {
	if v != nil {
		_c.SetDrivingRating(*v)
	}
	return _c
}

// SetProfilePictureURL sets the "profile_picture_url" field.
func (_c *UserCreate) SetProfilePictureURL(v string) *UserCreate {
	_c.mutation.SetProfilePictureURL(v)
	return _c
}

// SetNillableProfilePictureURL sets the "profile_picture_url" field if the given value is not nil.
func (_c *UserCreate) SetNillableProfilePictureURL(v *string) *UserCreate {
	if v != nil {
		_c.SetProfilePictureURL(*v)
	}
	return _c
}

// SetIsVerified sets the "is_verified" field.
func (_c *UserCreate) SetIsVerified(v bool) *UserCreate {
	_c.mutation.SetIsVerified(v)
	return _c
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsVerified(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsVerified(*v)
	}
	return _c
}

// SetVerifiedID sets the "verified_id" field.
func (_c *UserCreate) SetVerifiedID(v bool) *UserCreate {
	_c.mutation.SetVerifiedID(v)
	return _c
}

// SetNillableVerifiedID sets the "verified_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableVerifiedID(v *bool) *UserCreate {
	if v != nil {
		_c.SetVerifiedID(*v)
	}
	return _c
}

// SetConfirmedEmail sets the "confirmed_email" field.
func (_c *UserCreate) SetConfirmedEmail(v bool) *UserCreate {
	_c.mutation.SetConfirmedEmail(v)
	return _c
}

// SetNillableConfirmedEmail sets the "confirmed_email" field if the given value is not nil.
func (_c *UserCreate) SetNillableConfirmedEmail(v *bool) *UserCreate {
	if v != nil {
		_c.SetConfirmedEmail(*v)
	}
	return _c
}

// SetConfirmedPhone sets the "confirmed_phone" field.
func (_c *UserCreate) SetConfirmedPhone(v bool) *UserCreate {
	_c.mutation.SetConfirmedPhone(v)
	return _c
}

// SetNillableConfirmedPhone sets the "confirmed_phone" field if the given value is not nil.
func (_c *UserCreate) SetNillableConfirmedPhone(v *bool) *UserCreate {
	if v != nil {
		_c.SetConfirmedPhone(*v)
	}
	return _c
}

// SetBio sets the "bio" field.
func (_c *UserCreate) SetBio(v string) *UserCreate {
	_c.mutation.SetBio(v)
	return _c
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_c *UserCreate) SetNillableBio(v *string) *UserCreate {
	if v != nil {
		_c.SetBio(*v)
	}
	return _c
}

// SetPreferences sets the "preferences" field.
func (_c *UserCreate) SetPreferences(v map[string]interface{}) *UserCreate {
	_c.mutation.SetPreferences(v)
	return _c
}

// SetMembershipType sets the "membership_type" field.
func (_c *UserCreate) SetMembershipType(v string) *UserCreate {
	_c.mutation.SetMembershipType(v)
	return _c
}

// SetNillableMembershipType sets the "membership_type" field if the given value is not nil.
func (_c *UserCreate) SetNillableMembershipType(v *string) *UserCreate {
	if v != nil {
		_c.SetMembershipType(*v)
	}
	return _c
}

// SetPublishedRides sets the "published_rides" field.
func (_c *UserCreate) SetPublishedRides(v int) *UserCreate {
	_c.mutation.SetPublishedRides(v)
	return _c
}

// SetNillablePublishedRides sets the "published_rides" field if the given value is not nil.
func (_c *UserCreate) SetNillablePublishedRides(v *int) *UserCreate {
	if v != nil {
		_c.SetPublishedRides(*v)
	}
	return _c
}

// SetCompletedRides sets the "completed_rides" field.
func (_c *UserCreate) SetCompletedRides(v int) *UserCreate {
	_c.mutation.SetCompletedRides(v)
	return _c
}

// SetNillableCompletedRides sets the "completed_rides" field if the given value is not nil.
func (_c *UserCreate) SetNillableCompletedRides(v *int) *UserCreate {
	if v != nil {
		_c.SetCompletedRides(*v)
	}
	return _c
}

// SetNeverCancels sets the "never_cancels" field.
func (_c *UserCreate) SetNeverCancels(v bool) *UserCreate {
	_c.mutation.SetNeverCancels(v)
	return _c
}

// SetNillableNeverCancels sets the "never_cancels" field if the given value is not nil.
func (_c *UserCreate) SetNillableNeverCancels(v *bool) *UserCreate {
	if v != nil {
		_c.SetNeverCancels(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v string) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRideIDs adds the "rides" edge to the Ride entity by IDs.
func (_c *UserCreate) AddRideIDs(ids ...string) *UserCreate {
	_c.mutation.AddRideIDs(ids...)
	return _c
}

// AddRides adds the "rides" edges to the Ride entity.
func (_c *UserCreate) AddRides(v ...*Ride) *UserCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRideIDs(ids...)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_c *UserCreate) AddBookingIDs(ids ...string) *UserCreate {
	_c.mutation.AddBookingIDs(ids...)
	return _c
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_c *UserCreate) AddBookings(v ...*Booking) *UserCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBookingIDs(ids...)
}

// AddVehicleIDs adds the "vehicles" edge to the Vehicle entity by IDs.
func (_c *UserCreate) AddVehicleIDs(ids ...string) *UserCreate {
	_c.mutation.AddVehicleIDs(ids...)
	return _c
}

// AddVehicles adds the "vehicles" edges to the Vehicle entity.
func (_c *UserCreate) AddVehicles(v ...*Vehicle) *UserCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVehicleIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.ExperienceLevel(); !ok {
		v := user.DefaultExperienceLevel
		_c.mutation.SetExperienceLevel(v)
	}
	if _, ok := _c.mutation.Rating(); !ok {
		v := user.DefaultRating
		_c.mutation.SetRating(v)
	}
	if _, ok := _c.mutation.RatingCount(); !ok {
		v := user.DefaultRatingCount
		_c.mutation.SetRatingCount(v)
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		v := user.DefaultIsVerified
		_c.mutation.SetIsVerified(v)
	}
	if _, ok := _c.mutation.VerifiedID(); !ok {
		v := user.DefaultVerifiedID
		_c.mutation.SetVerifiedID(v)
	}
	if _, ok := _c.mutation.ConfirmedEmail(); !ok {
		v := user.DefaultConfirmedEmail
		_c.mutation.SetConfirmedEmail(v)
	}
	if _, ok := _c.mutation.ConfirmedPhone(); !ok {
		v := user.DefaultConfirmedPhone
		_c.mutation.SetConfirmedPhone(v)
	}
	if _, ok := _c.mutation.MembershipType(); !ok {
		v := user.DefaultMembershipType
		_c.mutation.SetMembershipType(v)
	}
	if _, ok := _c.mutation.PublishedRides(); !ok {
		v := user.DefaultPublishedRides
		_c.mutation.SetPublishedRides(v)
	}
	if _, ok := _c.mutation.CompletedRides(); !ok {
		v := user.DefaultCompletedRides
		_c.mutation.SetCompletedRides(v)
	}
	if _, ok := _c.mutation.NeverCancels(); !ok {
		v := user.DefaultNeverCancels
		_c.mutation.SetNeverCancels(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if v, ok := _c.mutation.Age(); ok {
		if err := user.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`ent: validator failed for field "User.age": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExperienceLevel(); !ok {
		return &ValidationError{Name: "experience_level", err: errors.New(`ent: missing required field "User.experience_level"`)}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "User.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := user.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "User.rating": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RatingCount(); !ok {
		return &ValidationError{Name: "rating_count", err: errors.New(`ent: missing required field "User.rating_count"`)}
	}
	if v, ok := _c.mutation.RatingCount(); ok {
		if err := user.RatingCountValidator(v); err != nil {
			return &ValidationError{Name: "rating_count", err: fmt.Errorf(`ent: validator failed for field "User.rating_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "User.is_verified"`)}
	}
	if _, ok := _c.mutation.VerifiedID(); !ok {
		return &ValidationError{Name: "verified_id", err: errors.New(`ent: missing required field "User.verified_id"`)}
	}
	if _, ok := _c.mutation.ConfirmedEmail(); !ok {
		return &ValidationError{Name: "confirmed_email", err: errors.New(`ent: missing required field "User.confirmed_email"`)}
	}
	if _, ok := _c.mutation.ConfirmedPhone(); !ok {
		return &ValidationError{Name: "confirmed_phone", err: errors.New(`ent: missing required field "User.confirmed_phone"`)}
	}
	if _, ok := _c.mutation.MembershipType(); !ok {
		return &ValidationError{Name: "membership_type", err: errors.New(`ent: missing required field "User.membership_type"`)}
	}
	if _, ok := _c.mutation.PublishedRides(); !ok {
		return &ValidationError{Name: "published_rides", err: errors.New(`ent: missing required field "User.published_rides"`)}
	}
	if v, ok := _c.mutation.PublishedRides(); ok {
		if err := user.PublishedRidesValidator(v); err != nil {
			return &ValidationError{Name: "published_rides", err: fmt.Errorf(`ent: validator failed for field "User.published_rides": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CompletedRides(); !ok {
		return &ValidationError{Name: "completed_rides", err: errors.New(`ent: missing required field "User.completed_rides"`)}
	}
	if v, ok := _c.mutation.CompletedRides(); ok {
		if err := user.CompletedRidesValidator(v); err != nil {
			return &ValidationError{Name: "completed_rides", err: fmt.Errorf(`ent: validator failed for field "User.completed_rides": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NeverCancels(); !ok {
		return &ValidationError{Name: "never_cancels", err: errors.New(`ent: missing required field "User.never_cancels"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected User.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
		_node.Age = &value
	}
	if value, ok := _c.mutation.ExperienceLevel(); ok {
		_spec.SetField(user.FieldExperienceLevel, field.TypeString, value)
		_node.ExperienceLevel = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(user.FieldRating, field.TypeFloat64, value)
		_node.Rating = value
	}
	if value, ok := _c.mutation.RatingCount(); ok {
		_spec.SetField(user.FieldRatingCount, field.TypeInt, value)
		_node.RatingCount = value
	}
	if value, ok := _c.mutation.DrivingRating(); ok {
		_spec.SetField(user.FieldDrivingRating, field.TypeString, value)
		_node.DrivingRating = &value
	}
	if value, ok := _c.mutation.ProfilePictureURL(); ok {
		_spec.SetField(user.FieldProfilePictureURL, field.TypeString, value)
		_node.ProfilePictureURL = value
	}
	if value, ok := _c.mutation.IsVerified(); ok {
		_spec.SetField(user.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	if value, ok := _c.mutation.VerifiedID(); ok {
		_spec.SetField(user.FieldVerifiedID, field.TypeBool, value)
		_node.VerifiedID = value
	}
	if value, ok := _c.mutation.ConfirmedEmail(); ok {
		_spec.SetField(user.FieldConfirmedEmail, field.TypeBool, value)
		_node.ConfirmedEmail = value
	}
	if value, ok := _c.mutation.ConfirmedPhone(); ok {
		_spec.SetField(user.FieldConfirmedPhone, field.TypeBool, value)
		_node.ConfirmedPhone = value
	}
	if value, ok := _c.mutation.Bio(); ok {
		_spec.SetField(user.FieldBio, field.TypeString, value)
		_node.Bio = &value
	}
	if value, ok := _c.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
		_node.Preferences = value
	}
	if value, ok := _c.mutation.MembershipType(); ok {
		_spec.SetField(user.FieldMembershipType, field.TypeString, value)
		_node.MembershipType = value
	}
	if value, ok := _c.mutation.PublishedRides(); ok {
		_spec.SetField(user.FieldPublishedRides, field.TypeInt, value)
		_node.PublishedRides = value
	}
	if value, ok := _c.mutation.CompletedRides(); ok {
		_spec.SetField(user.FieldCompletedRides, field.TypeInt, value)
		_node.CompletedRides = value
	}
	if value, ok := _c.mutation.NeverCancels(); ok {
		_spec.SetField(user.FieldNeverCancels, field.TypeBool, value)
		_node.NeverCancels = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RidesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RidesTable,
			Columns: []string{user.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VehiclesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.VehiclesTable,
			Columns: []string{user.VehiclesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
