// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/slowtyper/poolie/backend/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// Age holds the value of the "age" field.
	Age *int `json:"age,omitempty"`
	// ExperienceLevel holds the value of the "experience_level" field.
	ExperienceLevel string `json:"experience_level,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating float64 `json:"rating,omitempty"`
	// RatingCount holds the value of the "rating_count" field.
	RatingCount int `json:"rating_count,omitempty"`
	// DrivingRating holds the value of the "driving_rating" field.
	DrivingRating *string `json:"driving_rating,omitempty"`
	// ProfilePictureURL holds the value of the "profile_picture_url" field.
	ProfilePictureURL string `json:"profile_picture_url,omitempty"`
	// IsVerified holds the value of the "is_verified" field.
	IsVerified bool `json:"is_verified,omitempty"`
	// VerifiedID holds the value of the "verified_id" field.
	VerifiedID bool `json:"verified_id,omitempty"`
	// ConfirmedEmail holds the value of the "confirmed_email" field.
	ConfirmedEmail bool `json:"confirmed_email,omitempty"`
	// ConfirmedPhone holds the value of the "confirmed_phone" field.
	ConfirmedPhone bool `json:"confirmed_phone,omitempty"`
	// Bio holds the value of the "bio" field.
	Bio *string `json:"bio,omitempty"`
	// Preferences holds the value of the "preferences" field.
	Preferences map[string]interface{} `json:"preferences,omitempty"`
	// MembershipType holds the value of the "membership_type" field.
	MembershipType string `json:"membership_type,omitempty"`
	// PublishedRides holds the value of the "published_rides" field.
	PublishedRides int `json:"published_rides,omitempty"`
	// CompletedRides holds the value of the "completed_rides" field.
	CompletedRides int `json:"completed_rides,omitempty"`
	// NeverCancels holds the value of the "never_cancels" field.
	NeverCancels bool `json:"never_cancels,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Rides holds the value of the rides edge.
	Rides []*Ride `json:"rides,omitempty"`
	// Bookings holds the value of the bookings edge.
	Bookings []*Booking `json:"bookings,omitempty"`
	// Vehicles holds the value of the vehicles edge.
	Vehicles []*Vehicle `json:"vehicles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// RidesOrErr returns the Rides value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RidesOrErr() ([]*Ride, error) {
	if e.loadedTypes[0] {
		return e.Rides, nil
	}
	return nil, &NotLoadedError{edge: "rides"}
}

// BookingsOrErr returns the Bookings value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) BookingsOrErr() ([]*Booking, error) {
	if e.loadedTypes[1] {
		return e.Bookings, nil
	}
	return nil, &NotLoadedError{edge: "bookings"}
}

// VehiclesOrErr returns the Vehicles value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) VehiclesOrErr() ([]*Vehicle, error) {
	if e.loadedTypes[2] {
		return e.Vehicles, nil
	}
	return nil, &NotLoadedError{edge: "vehicles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldPreferences:
			values[i] = new([]byte)
		case user.FieldIsVerified, user.FieldVerifiedID, user.FieldConfirmedEmail, user.FieldConfirmedPhone, user.FieldNeverCancels:
			values[i] = new(sql.NullBool)
		case user.FieldRating:
			values[i] = new(sql.NullFloat64)
		case user.FieldAge, user.FieldRatingCount, user.FieldPublishedRides, user.FieldCompletedRides:
			values[i] = new(sql.NullInt64)
		case user.FieldID, user.FieldName, user.FieldEmail, user.FieldPhone, user.FieldPasswordHash, user.FieldExperienceLevel, user.FieldDrivingRating, user.FieldProfilePictureURL, user.FieldBio, user.FieldMembershipType:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				_m.Age = new(int)
				*_m.Age = int(value.Int64)
			}
		case user.FieldExperienceLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field experience_level", values[i])
			} else if value.Valid {
				_m.ExperienceLevel = value.String
			}
		case user.FieldRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = value.Float64
			}
		case user.FieldRatingCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating_count", values[i])
			} else if value.Valid {
				_m.RatingCount = int(value.Int64)
			}
		case user.FieldDrivingRating:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field driving_rating", values[i])
			} else if value.Valid {
				_m.DrivingRating = new(string)
				*_m.DrivingRating = value.String
			}
		case user.FieldProfilePictureURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_picture_url", values[i])
			} else if value.Valid {
				_m.ProfilePictureURL = value.String
			}
		case user.FieldIsVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_verified", values[i])
			} else if value.Valid {
				_m.IsVerified = value.Bool
			}
		case user.FieldVerifiedID:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified_id", values[i])
			} else if value.Valid {
				_m.VerifiedID = value.Bool
			}
		case user.FieldConfirmedEmail:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_email", values[i])
			} else if value.Valid {
				_m.ConfirmedEmail = value.Bool
			}
		case user.FieldConfirmedPhone:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_phone", values[i])
			} else if value.Valid {
				_m.ConfirmedPhone = value.Bool
			}
		case user.FieldBio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bio", values[i])
			} else if value.Valid {
				_m.Bio = new(string)
				*_m.Bio = value.String
			}
		case user.FieldPreferences:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field preferences", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Preferences); err != nil {
					return fmt.Errorf("unmarshal field preferences: %w", err)
				}
			}
		case user.FieldMembershipType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field membership_type", values[i])
			} else if value.Valid {
				_m.MembershipType = value.String
			}
		case user.FieldPublishedRides:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field published_rides", values[i])
			} else if value.Valid {
				_m.PublishedRides = int(value.Int64)
			}
		case user.FieldCompletedRides:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_rides", values[i])
			} else if value.Valid {
				_m.CompletedRides = int(value.Int64)
			}
		case user.FieldNeverCancels:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field never_cancels", values[i])
			} else if value.Valid {
				_m.NeverCancels = value.Bool
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRides queries the "rides" edge of the User entity.
func (_m *User) QueryRides() *RideQuery {
	return NewUserClient(_m.config).QueryRides(_m)
}

// QueryBookings queries the "bookings" edge of the User entity.
func (_m *User) QueryBookings() *BookingQuery {
	return NewUserClient(_m.config).QueryBookings(_m)
}

// QueryVehicles queries the "vehicles" edge of the User entity.
func (_m *User) QueryVehicles() *VehicleQuery {
	return NewUserClient(_m.config).QueryVehicles(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(_m.Phone)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	if v := _m.Age; v != nil {
		builder.WriteString("age=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("experience_level=")
	builder.WriteString(_m.ExperienceLevel)
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("rating_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RatingCount))
	builder.WriteString(", ")
	if v := _m.DrivingRating; v != nil {
		builder.WriteString("driving_rating=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("profile_picture_url=")
	builder.WriteString(_m.ProfilePictureURL)
	builder.WriteString(", ")
	builder.WriteString("is_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsVerified))
	builder.WriteString(", ")
	builder.WriteString("verified_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VerifiedID))
	builder.WriteString(", ")
	builder.WriteString("confirmed_email=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfirmedEmail))
	builder.WriteString(", ")
	builder.WriteString("confirmed_phone=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfirmedPhone))
	builder.WriteString(", ")
	if v := _m.Bio; v != nil {
		builder.WriteString("bio=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("preferences=")
	builder.WriteString(fmt.Sprintf("%v", _m.Preferences))
	builder.WriteString(", ")
	builder.WriteString("membership_type=")
	builder.WriteString(_m.MembershipType)
	builder.WriteString(", ")
	builder.WriteString("published_rides=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublishedRides))
	builder.WriteString(", ")
	builder.WriteString("completed_rides=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedRides))
	builder.WriteString(", ")
	builder.WriteString("never_cancels=")
	builder.WriteString(fmt.Sprintf("%v", _m.NeverCancels))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
