// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/slowtyper/poolie/backend/ent/ride"
	"github.com/slowtyper/poolie/backend/ent/user"
	"github.com/slowtyper/poolie/backend/ent/vehicle"
)

// VehicleCreate is the builder for creating a Vehicle entity.
type VehicleCreate struct {
	config
	mutation *VehicleMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *VehicleCreate) SetUserID(v string) *VehicleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetMake sets the "make" field.
func (_c *VehicleCreate) SetMake(v string) *VehicleCreate {
	_c.mutation.SetMake(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *VehicleCreate) SetModel(v string) *VehicleCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *VehicleCreate) SetColor(v string) *VehicleCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetLicensePlate sets the "license_plate" field.
func (_c *VehicleCreate) SetLicensePlate(v string) *VehicleCreate {
	_c.mutation.SetLicensePlate(v)
	return _c
}

// SetNillableLicensePlate sets the "license_plate" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableLicensePlate(v *string) *VehicleCreate {
	if v != nil {
		_c.SetLicensePlate(*v)
	}
	return _c
}

// SetYear sets the "year" field.
func (_c *VehicleCreate) SetYear(v int) *VehicleCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableYear(v *int) *VehicleCreate {
	if v != nil {
		_c.SetYear(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VehicleCreate) SetCreatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableCreatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VehicleCreate) SetUpdatedAt(v time.Time) *VehicleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VehicleCreate) SetNillableUpdatedAt(v *time.Time) *VehicleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VehicleCreate) SetID(v string) *VehicleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *VehicleCreate) SetOwnerID(id string) *VehicleCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *VehicleCreate) SetOwner(v *User) *VehicleCreate {
	return _c.SetOwnerID(v.ID)
}

// AddRideIDs adds the "rides" edge to the Ride entity by IDs.
func (_c *VehicleCreate) AddRideIDs(ids ...string) *VehicleCreate {
	_c.mutation.AddRideIDs(ids...)
	return _c
}

// AddRides adds the "rides" edges to the Ride entity.
func (_c *VehicleCreate) AddRides(v ...*Ride) *VehicleCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRideIDs(ids...)
}

// Mutation returns the VehicleMutation object of the builder.
func (_c *VehicleCreate) Mutation() *VehicleMutation {
	return _c.mutation
}

// Save creates the Vehicle in the database.
func (_c *VehicleCreate) Save(ctx context.Context) (*Vehicle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VehicleCreate) SaveX(ctx context.Context) *Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VehicleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vehicle.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vehicle.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VehicleCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Vehicle.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := vehicle.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Vehicle.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Make(); !ok {
		return &ValidationError{Name: "make", err: errors.New(`ent: missing required field "Vehicle.make"`)}
	}
	if v, ok := _c.mutation.Make(); ok {
		if err := vehicle.MakeValidator(v); err != nil {
			return &ValidationError{Name: "make", err: fmt.Errorf(`ent: validator failed for field "Vehicle.make": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "Vehicle.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := vehicle.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Vehicle.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Vehicle.color"`)}
	}
	if v, ok := _c.mutation.Color(); ok {
		if err := vehicle.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Vehicle.color": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Year(); ok {
		if err := vehicle.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Vehicle.year": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vehicle.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Vehicle.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Vehicle.owner"`)}
	}
	return nil
}

func (_c *VehicleCreate) sqlSave(ctx context.Context) (*Vehicle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Vehicle.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VehicleCreate) createSpec() (*Vehicle, *sqlgraph.CreateSpec) {
	var (
		_node = &Vehicle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vehicle.Table, sqlgraph.NewFieldSpec(vehicle.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Make(); ok {
		_spec.SetField(vehicle.FieldMake, field.TypeString, value)
		_node.Make = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(vehicle.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(vehicle.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.LicensePlate(); ok {
		_spec.SetField(vehicle.FieldLicensePlate, field.TypeString, value)
		_node.LicensePlate = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(vehicle.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vehicle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vehicle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vehicle.OwnerTable,
			Columns: []string{vehicle.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RidesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vehicle.RidesTable,
			Columns: []string{vehicle.RidesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ride.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VehicleCreateBulk is the builder for creating many Vehicle entities in bulk.
type VehicleCreateBulk struct {
	config
	err      error
	builders []*VehicleCreate
}

// Save creates the Vehicle entities in the database.
func (_c *VehicleCreateBulk) Save(ctx context.Context) ([]*Vehicle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vehicle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VehicleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VehicleCreateBulk) SaveX(ctx context.Context) []*Vehicle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VehicleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VehicleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
