// Code generated by ent, DO NOT EDIT.

package booking

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the booking type in the database.
	Label = "booking"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRideID holds the string denoting the ride_id field in the database.
	FieldRideID = "ride_id"
	// FieldPassengerID holds the string denoting the passenger_id field in the database.
	FieldPassengerID = "passenger_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPassengerCount holds the string denoting the passenger_count field in the database.
	FieldPassengerCount = "passenger_count"
	// FieldTotalPriceAmount holds the string denoting the total_price_amount field in the database.
	FieldTotalPriceAmount = "total_price_amount"
	// FieldTotalPriceCurrency holds the string denoting the total_price_currency field in the database.
	FieldTotalPriceCurrency = "total_price_currency"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldDriverResponseMessage holds the string denoting the driver_response_message field in the database.
	FieldDriverResponseMessage = "driver_response_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRespondedAt holds the string denoting the responded_at field in the database.
	FieldRespondedAt = "responded_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRide holds the string denoting the ride edge name in mutations.
	EdgeRide = "ride"
	// EdgePassenger holds the string denoting the passenger edge name in mutations.
	EdgePassenger = "passenger"
	// Table holds the table name of the booking in the database.
	Table = "bookings"
	// RideTable is the table that holds the ride relation/edge.
	RideTable = "bookings"
	// RideInverseTable is the table name for the Ride entity.
	// It exists in this package in order to avoid circular dependency with the "ride" package.
	RideInverseTable = "rides"
	// RideColumn is the table column denoting the ride relation/edge.
	RideColumn = "ride_id"
	// PassengerTable is the table that holds the passenger relation/edge.
	PassengerTable = "bookings"
	// PassengerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PassengerInverseTable = "users"
	// PassengerColumn is the table column denoting the passenger relation/edge.
	PassengerColumn = "passenger_id"
)

// Columns holds all SQL columns for booking fields.
var Columns = []string{
	FieldID,
	FieldRideID,
	FieldPassengerID,
	FieldStatus,
	FieldPassengerCount,
	FieldTotalPriceAmount,
	FieldTotalPriceCurrency,
	FieldMessage,
	FieldDriverResponseMessage,
	FieldCreatedAt,
	FieldRespondedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RideIDValidator is a validator for the "ride_id" field. It is called by the builders before save.
	RideIDValidator func(string) error
	// PassengerIDValidator is a validator for the "passenger_id" field. It is called by the builders before save.
	PassengerIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// PassengerCountValidator is a validator for the "passenger_count" field. It is called by the builders before save.
	PassengerCountValidator func(int) error
	// TotalPriceAmountValidator is a validator for the "total_price_amount" field. It is called by the builders before save.
	TotalPriceAmountValidator func(int64) error
	// DefaultTotalPriceCurrency holds the default value on creation for the "total_price_currency" field.
	DefaultTotalPriceCurrency string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Booking queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRideID orders the results by the ride_id field.
func ByRideID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRideID, opts...).ToFunc()
}

// ByPassengerID orders the results by the passenger_id field.
func ByPassengerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPassengerCount orders the results by the passenger_count field.
func ByPassengerCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerCount, opts...).ToFunc()
}

// ByTotalPriceAmount orders the results by the total_price_amount field.
func ByTotalPriceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPriceAmount, opts...).ToFunc()
}

// ByTotalPriceCurrency orders the results by the total_price_currency field.
func ByTotalPriceCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPriceCurrency, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByDriverResponseMessage orders the results by the driver_response_message field.
func ByDriverResponseMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriverResponseMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRespondedAt orders the results by the responded_at field.
func ByRespondedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRespondedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRideField orders the results by ride field.
func ByRideField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRideStep(), sql.OrderByField(field, opts...))
	}
}

// ByPassengerField orders the results by passenger field.
func ByPassengerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPassengerStep(), sql.OrderByField(field, opts...))
	}
}
func newRideStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RideInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RideTable, RideColumn),
	)
}
func newPassengerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PassengerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PassengerTable, PassengerColumn),
	)
}
