// Code generated by ent, DO NOT EDIT.

package booking

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/slowtyper/poolie/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Booking {
	return predicate.Booking(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Booking {
	return predicate.Booking(sql.FieldContainsFold(FieldID, id))
}

// RideID applies equality check predicate on the "ride_id" field. It's identical to RideIDEQ.
func RideID(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldRideID, v))
}

// PassengerID applies equality check predicate on the "passenger_id" field. It's identical to PassengerIDEQ.
func PassengerID(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldPassengerID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldStatus, v))
}

// PassengerCount applies equality check predicate on the "passenger_count" field. It's identical to PassengerCountEQ.
func PassengerCount(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldPassengerCount, v))
}

// TotalPriceAmount applies equality check predicate on the "total_price_amount" field. It's identical to TotalPriceAmountEQ.
func TotalPriceAmount(v int64) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldTotalPriceAmount, v))
}

// TotalPriceCurrency applies equality check predicate on the "total_price_currency" field. It's identical to TotalPriceCurrencyEQ.
func TotalPriceCurrency(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldTotalPriceCurrency, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldMessage, v))
}

// DriverResponseMessage applies equality check predicate on the "driver_response_message" field. It's identical to DriverResponseMessageEQ.
func DriverResponseMessage(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldDriverResponseMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldCreatedAt, v))
}

// RespondedAt applies equality check predicate on the "responded_at" field. It's identical to RespondedAtEQ.
func RespondedAt(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldRespondedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldUpdatedAt, v))
}

// RideIDEQ applies the EQ predicate on the "ride_id" field.
func RideIDEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldRideID, v))
}

// RideIDNEQ applies the NEQ predicate on the "ride_id" field.
func RideIDNEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldRideID, v))
}

// RideIDIn applies the In predicate on the "ride_id" field.
func RideIDIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldRideID, vs...))
}

// RideIDNotIn applies the NotIn predicate on the "ride_id" field.
func RideIDNotIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldRideID, vs...))
}

// RideIDGT applies the GT predicate on the "ride_id" field.
func RideIDGT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldRideID, v))
}

// RideIDGTE applies the GTE predicate on the "ride_id" field.
func RideIDGTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldRideID, v))
}

// RideIDLT applies the LT predicate on the "ride_id" field.
func RideIDLT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldRideID, v))
}

// RideIDLTE applies the LTE predicate on the "ride_id" field.
func RideIDLTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldRideID, v))
}

// RideIDContains applies the Contains predicate on the "ride_id" field.
func RideIDContains(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContains(FieldRideID, v))
}

// RideIDHasPrefix applies the HasPrefix predicate on the "ride_id" field.
func RideIDHasPrefix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasPrefix(FieldRideID, v))
}

// RideIDHasSuffix applies the HasSuffix predicate on the "ride_id" field.
func RideIDHasSuffix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasSuffix(FieldRideID, v))
}

// RideIDEqualFold applies the EqualFold predicate on the "ride_id" field.
func RideIDEqualFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEqualFold(FieldRideID, v))
}

// RideIDContainsFold applies the ContainsFold predicate on the "ride_id" field.
func RideIDContainsFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContainsFold(FieldRideID, v))
}

// PassengerIDEQ applies the EQ predicate on the "passenger_id" field.
func PassengerIDEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldPassengerID, v))
}

// PassengerIDNEQ applies the NEQ predicate on the "passenger_id" field.
func PassengerIDNEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldPassengerID, v))
}

// PassengerIDIn applies the In predicate on the "passenger_id" field.
func PassengerIDIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldPassengerID, vs...))
}

// PassengerIDNotIn applies the NotIn predicate on the "passenger_id" field.
func PassengerIDNotIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldPassengerID, vs...))
}

// PassengerIDGT applies the GT predicate on the "passenger_id" field.
func PassengerIDGT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldPassengerID, v))
}

// PassengerIDGTE applies the GTE predicate on the "passenger_id" field.
func PassengerIDGTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldPassengerID, v))
}

// PassengerIDLT applies the LT predicate on the "passenger_id" field.
func PassengerIDLT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldPassengerID, v))
}

// PassengerIDLTE applies the LTE predicate on the "passenger_id" field.
func PassengerIDLTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldPassengerID, v))
}

// PassengerIDContains applies the Contains predicate on the "passenger_id" field.
func PassengerIDContains(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContains(FieldPassengerID, v))
}

// PassengerIDHasPrefix applies the HasPrefix predicate on the "passenger_id" field.
func PassengerIDHasPrefix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasPrefix(FieldPassengerID, v))
}

// PassengerIDHasSuffix applies the HasSuffix predicate on the "passenger_id" field.
func PassengerIDHasSuffix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasSuffix(FieldPassengerID, v))
}

// PassengerIDEqualFold applies the EqualFold predicate on the "passenger_id" field.
func PassengerIDEqualFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEqualFold(FieldPassengerID, v))
}

// PassengerIDContainsFold applies the ContainsFold predicate on the "passenger_id" field.
func PassengerIDContainsFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContainsFold(FieldPassengerID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContainsFold(FieldStatus, v))
}

// PassengerCountEQ applies the EQ predicate on the "passenger_count" field.
func PassengerCountEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldPassengerCount, v))
}

// PassengerCountNEQ applies the NEQ predicate on the "passenger_count" field.
func PassengerCountNEQ(v int) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldPassengerCount, v))
}

// PassengerCountIn applies the In predicate on the "passenger_count" field.
func PassengerCountIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldPassengerCount, vs...))
}

// PassengerCountNotIn applies the NotIn predicate on the "passenger_count" field.
func PassengerCountNotIn(vs ...int) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldPassengerCount, vs...))
}

// PassengerCountGT applies the GT predicate on the "passenger_count" field.
func PassengerCountGT(v int) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldPassengerCount, v))
}

// PassengerCountGTE applies the GTE predicate on the "passenger_count" field.
func PassengerCountGTE(v int) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldPassengerCount, v))
}

// PassengerCountLT applies the LT predicate on the "passenger_count" field.
func PassengerCountLT(v int) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldPassengerCount, v))
}

// PassengerCountLTE applies the LTE predicate on the "passenger_count" field.
func PassengerCountLTE(v int) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldPassengerCount, v))
}

// TotalPriceAmountEQ applies the EQ predicate on the "total_price_amount" field.
func TotalPriceAmountEQ(v int64) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldTotalPriceAmount, v))
}

// TotalPriceAmountNEQ applies the NEQ predicate on the "total_price_amount" field.
func TotalPriceAmountNEQ(v int64) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldTotalPriceAmount, v))
}

// TotalPriceAmountIn applies the In predicate on the "total_price_amount" field.
func TotalPriceAmountIn(vs ...int64) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldTotalPriceAmount, vs...))
}

// TotalPriceAmountNotIn applies the NotIn predicate on the "total_price_amount" field.
func TotalPriceAmountNotIn(vs ...int64) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldTotalPriceAmount, vs...))
}

// TotalPriceAmountGT applies the GT predicate on the "total_price_amount" field.
func TotalPriceAmountGT(v int64) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldTotalPriceAmount, v))
}

// TotalPriceAmountGTE applies the GTE predicate on the "total_price_amount" field.
func TotalPriceAmountGTE(v int64) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldTotalPriceAmount, v))
}

// TotalPriceAmountLT applies the LT predicate on the "total_price_amount" field.
func TotalPriceAmountLT(v int64) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldTotalPriceAmount, v))
}

// TotalPriceAmountLTE applies the LTE predicate on the "total_price_amount" field.
func TotalPriceAmountLTE(v int64) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldTotalPriceAmount, v))
}

// TotalPriceCurrencyEQ applies the EQ predicate on the "total_price_currency" field.
func TotalPriceCurrencyEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyNEQ applies the NEQ predicate on the "total_price_currency" field.
func TotalPriceCurrencyNEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyIn applies the In predicate on the "total_price_currency" field.
func TotalPriceCurrencyIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldTotalPriceCurrency, vs...))
}

// TotalPriceCurrencyNotIn applies the NotIn predicate on the "total_price_currency" field.
func TotalPriceCurrencyNotIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldTotalPriceCurrency, vs...))
}

// TotalPriceCurrencyGT applies the GT predicate on the "total_price_currency" field.
func TotalPriceCurrencyGT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyGTE applies the GTE predicate on the "total_price_currency" field.
func TotalPriceCurrencyGTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyLT applies the LT predicate on the "total_price_currency" field.
func TotalPriceCurrencyLT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyLTE applies the LTE predicate on the "total_price_currency" field.
func TotalPriceCurrencyLTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyContains applies the Contains predicate on the "total_price_currency" field.
func TotalPriceCurrencyContains(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContains(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyHasPrefix applies the HasPrefix predicate on the "total_price_currency" field.
func TotalPriceCurrencyHasPrefix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasPrefix(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyHasSuffix applies the HasSuffix predicate on the "total_price_currency" field.
func TotalPriceCurrencyHasSuffix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasSuffix(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyEqualFold applies the EqualFold predicate on the "total_price_currency" field.
func TotalPriceCurrencyEqualFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEqualFold(FieldTotalPriceCurrency, v))
}

// TotalPriceCurrencyContainsFold applies the ContainsFold predicate on the "total_price_currency" field.
func TotalPriceCurrencyContainsFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContainsFold(FieldTotalPriceCurrency, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.Booking {
	return predicate.Booking(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.Booking {
	return predicate.Booking(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContainsFold(FieldMessage, v))
}

// DriverResponseMessageEQ applies the EQ predicate on the "driver_response_message" field.
func DriverResponseMessageEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldDriverResponseMessage, v))
}

// DriverResponseMessageNEQ applies the NEQ predicate on the "driver_response_message" field.
func DriverResponseMessageNEQ(v string) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldDriverResponseMessage, v))
}

// DriverResponseMessageIn applies the In predicate on the "driver_response_message" field.
func DriverResponseMessageIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldDriverResponseMessage, vs...))
}

// DriverResponseMessageNotIn applies the NotIn predicate on the "driver_response_message" field.
func DriverResponseMessageNotIn(vs ...string) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldDriverResponseMessage, vs...))
}

// DriverResponseMessageGT applies the GT predicate on the "driver_response_message" field.
func DriverResponseMessageGT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldDriverResponseMessage, v))
}

// DriverResponseMessageGTE applies the GTE predicate on the "driver_response_message" field.
func DriverResponseMessageGTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldDriverResponseMessage, v))
}

// DriverResponseMessageLT applies the LT predicate on the "driver_response_message" field.
func DriverResponseMessageLT(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldDriverResponseMessage, v))
}

// DriverResponseMessageLTE applies the LTE predicate on the "driver_response_message" field.
func DriverResponseMessageLTE(v string) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldDriverResponseMessage, v))
}

// DriverResponseMessageContains applies the Contains predicate on the "driver_response_message" field.
func DriverResponseMessageContains(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContains(FieldDriverResponseMessage, v))
}

// DriverResponseMessageHasPrefix applies the HasPrefix predicate on the "driver_response_message" field.
func DriverResponseMessageHasPrefix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasPrefix(FieldDriverResponseMessage, v))
}

// DriverResponseMessageHasSuffix applies the HasSuffix predicate on the "driver_response_message" field.
func DriverResponseMessageHasSuffix(v string) predicate.Booking {
	return predicate.Booking(sql.FieldHasSuffix(FieldDriverResponseMessage, v))
}

// DriverResponseMessageIsNil applies the IsNil predicate on the "driver_response_message" field.
func DriverResponseMessageIsNil() predicate.Booking {
	return predicate.Booking(sql.FieldIsNull(FieldDriverResponseMessage))
}

// DriverResponseMessageNotNil applies the NotNil predicate on the "driver_response_message" field.
func DriverResponseMessageNotNil() predicate.Booking {
	return predicate.Booking(sql.FieldNotNull(FieldDriverResponseMessage))
}

// DriverResponseMessageEqualFold applies the EqualFold predicate on the "driver_response_message" field.
func DriverResponseMessageEqualFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldEqualFold(FieldDriverResponseMessage, v))
}

// DriverResponseMessageContainsFold applies the ContainsFold predicate on the "driver_response_message" field.
func DriverResponseMessageContainsFold(v string) predicate.Booking {
	return predicate.Booking(sql.FieldContainsFold(FieldDriverResponseMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldCreatedAt, v))
}

// RespondedAtEQ applies the EQ predicate on the "responded_at" field.
func RespondedAtEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldRespondedAt, v))
}

// RespondedAtNEQ applies the NEQ predicate on the "responded_at" field.
func RespondedAtNEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldRespondedAt, v))
}

// RespondedAtIn applies the In predicate on the "responded_at" field.
func RespondedAtIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldRespondedAt, vs...))
}

// RespondedAtNotIn applies the NotIn predicate on the "responded_at" field.
func RespondedAtNotIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldRespondedAt, vs...))
}

// RespondedAtGT applies the GT predicate on the "responded_at" field.
func RespondedAtGT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldRespondedAt, v))
}

// RespondedAtGTE applies the GTE predicate on the "responded_at" field.
func RespondedAtGTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldRespondedAt, v))
}

// RespondedAtLT applies the LT predicate on the "responded_at" field.
func RespondedAtLT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldRespondedAt, v))
}

// RespondedAtLTE applies the LTE predicate on the "responded_at" field.
func RespondedAtLTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldRespondedAt, v))
}

// RespondedAtIsNil applies the IsNil predicate on the "responded_at" field.
func RespondedAtIsNil() predicate.Booking {
	return predicate.Booking(sql.FieldIsNull(FieldRespondedAt))
}

// RespondedAtNotNil applies the NotNil predicate on the "responded_at" field.
func RespondedAtNotNil() predicate.Booking {
	return predicate.Booking(sql.FieldNotNull(FieldRespondedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Booking {
	return predicate.Booking(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasRide applies the HasEdge predicate on the "ride" edge.
func HasRide() predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RideTable, RideColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRideWith applies the HasEdge predicate on the "ride" edge with a given conditions (other predicates).
func HasRideWith(preds ...predicate.Ride) predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := newRideStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPassenger applies the HasEdge predicate on the "passenger" edge.
func HasPassenger() predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PassengerTable, PassengerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPassengerWith applies the HasEdge predicate on the "passenger" edge with a given conditions (other predicates).
func HasPassengerWith(preds ...predicate.User) predicate.Booking {
	return predicate.Booking(func(s *sql.Selector) {
		step := newPassengerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Booking) predicate.Booking {
	return predicate.Booking(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Booking) predicate.Booking {
	return predicate.Booking(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Booking) predicate.Booking {
	return predicate.Booking(sql.NotPredicates(p))
}
