// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BookingsColumns holds the columns for the "bookings" table.
	BookingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "passenger_count", Type: field.TypeInt},
		{Name: "total_price_amount", Type: field.TypeInt64},
		{Name: "total_price_currency", Type: field.TypeString, Default: "IDR"},
		{Name: "message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "driver_response_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "responded_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "ride_id", Type: field.TypeString},
		{Name: "passenger_id", Type: field.TypeString},
	}
	// BookingsTable holds the schema information for the "bookings" table.
	BookingsTable = &schema.Table{
		Name:       "bookings",
		Columns:    BookingsColumns,
		PrimaryKey: []*schema.Column{BookingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "bookings_rides_bookings",
				Columns:    []*schema.Column{BookingsColumns[10]},
				RefColumns: []*schema.Column{RidesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "bookings_users_bookings",
				Columns:    []*schema.Column{BookingsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "booking_ride_id",
				Unique:  false,
				Columns: []*schema.Column{BookingsColumns[10]},
			},
			{
				Name:    "booking_passenger_id",
				Unique:  false,
				Columns: []*schema.Column{BookingsColumns[11]},
			},
			{
				Name:    "booking_status",
				Unique:  false,
				Columns: []*schema.Column{BookingsColumns[1]},
			},
		},
	}
	// RidesColumns holds the columns for the "rides" table.
	RidesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString, Default: "carpool"},
		{Name: "ride_type", Type: field.TypeString, Default: "one_time"},
		{Name: "recurrence", Type: field.TypeJSON, Nullable: true},
		{Name: "departure_time", Type: field.TypeTime},
		{Name: "arrival_time", Type: field.TypeTime, Nullable: true},
		{Name: "duration_minutes", Type: field.TypeInt, Nullable: true},
		{Name: "origin_city", Type: field.TypeString},
		{Name: "origin_address", Type: field.TypeString},
		{Name: "origin_location_point", Type: field.TypeString, Nullable: true},
		{Name: "destination_city", Type: field.TypeString},
		{Name: "destination_address", Type: field.TypeString},
		{Name: "destination_location_point", Type: field.TypeString, Nullable: true},
		{Name: "price_amount", Type: field.TypeInt64},
		{Name: "price_currency", Type: field.TypeString, Default: "IDR"},
		{Name: "available_seats", Type: field.TypeInt},
		{Name: "total_seats", Type: field.TypeInt},
		{Name: "amenities", Type: field.TypeJSON, Nullable: true},
		{Name: "stops", Type: field.TypeJSON, Nullable: true},
		{Name: "instant_confirmation", Type: field.TypeBool, Default: true},
		{Name: "cancellation_policy", Type: field.TypeString, Default: "never_cancels"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "driver_id", Type: field.TypeString},
		{Name: "vehicle_id", Type: field.TypeString, Nullable: true},
	}
	// RidesTable holds the schema information for the "rides" table.
	RidesTable = &schema.Table{
		Name:       "rides",
		Columns:    RidesColumns,
		PrimaryKey: []*schema.Column{RidesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rides_users_rides",
				Columns:    []*schema.Column{RidesColumns[25]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "rides_vehicles_rides",
				Columns:    []*schema.Column{RidesColumns[26]},
				RefColumns: []*schema.Column{VehiclesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ride_origin_city_destination_city_departure_time",
				Unique:  false,
				Columns: []*schema.Column{RidesColumns[7], RidesColumns[10], RidesColumns[4]},
			},
			{
				Name:    "ride_driver_id",
				Unique:  false,
				Columns: []*schema.Column{RidesColumns[25]},
			},
			{
				Name:    "ride_status",
				Unique:  false,
				Columns: []*schema.Column{RidesColumns[22]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt, Nullable: true},
		{Name: "experience_level", Type: field.TypeString, Default: "beginner"},
		{Name: "rating", Type: field.TypeFloat64, Default: 0},
		{Name: "rating_count", Type: field.TypeInt, Default: 0},
		{Name: "driving_rating", Type: field.TypeString, Nullable: true},
		{Name: "profile_picture_url", Type: field.TypeString, Nullable: true},
		{Name: "is_verified", Type: field.TypeBool, Default: false},
		{Name: "verified_id", Type: field.TypeBool, Default: false},
		{Name: "confirmed_email", Type: field.TypeBool, Default: false},
		{Name: "confirmed_phone", Type: field.TypeBool, Default: false},
		{Name: "bio", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "preferences", Type: field.TypeJSON, Nullable: true},
		{Name: "membership_type", Type: field.TypeString, Default: "non_professional"},
		{Name: "published_rides", Type: field.TypeInt, Default: 0},
		{Name: "completed_rides", Type: field.TypeInt, Default: 0},
		{Name: "never_cancels", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VehiclesColumns holds the columns for the "vehicles" table.
	VehiclesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "make", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "color", Type: field.TypeString},
		{Name: "license_plate", Type: field.TypeString, Nullable: true},
		{Name: "year", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
	}
	// VehiclesTable holds the schema information for the "vehicles" table.
	VehiclesTable = &schema.Table{
		Name:       "vehicles",
		Columns:    VehiclesColumns,
		PrimaryKey: []*schema.Column{VehiclesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "vehicles_users_vehicles",
				Columns:    []*schema.Column{VehiclesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BookingsTable,
		RidesTable,
		UsersTable,
		VehiclesTable,
	}
)

func init() {
	BookingsTable.ForeignKeys[0].RefTable = RidesTable
	BookingsTable.ForeignKeys[1].RefTable = UsersTable
	RidesTable.ForeignKeys[0].RefTable = UsersTable
	RidesTable.ForeignKeys[1].RefTable = VehiclesTable
	VehiclesTable.ForeignKeys[0].RefTable = UsersTable
}
