// Code generated by ent, DO NOT EDIT.

package ride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ride type in the database.
	Label = "ride"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDriverID holds the string denoting the driver_id field in the database.
	FieldDriverID = "driver_id"
	// FieldVehicleID holds the string denoting the vehicle_id field in the database.
	FieldVehicleID = "vehicle_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldRideType holds the string denoting the ride_type field in the database.
	FieldRideType = "ride_type"
	// FieldRecurrence holds the string denoting the recurrence field in the database.
	FieldRecurrence = "recurrence"
	// FieldDepartureTime holds the string denoting the departure_time field in the database.
	FieldDepartureTime = "departure_time"
	// FieldArrivalTime holds the string denoting the arrival_time field in the database.
	FieldArrivalTime = "arrival_time"
	// FieldDurationMinutes holds the string denoting the duration_minutes field in the database.
	FieldDurationMinutes = "duration_minutes"
	// FieldOriginCity holds the string denoting the origin_city field in the database.
	FieldOriginCity = "origin_city"
	// FieldOriginAddress holds the string denoting the origin_address field in the database.
	FieldOriginAddress = "origin_address"
	// FieldOriginLocationPoint holds the string denoting the origin_location_point field in the database.
	FieldOriginLocationPoint = "origin_location_point"
	// FieldDestinationCity holds the string denoting the destination_city field in the database.
	FieldDestinationCity = "destination_city"
	// FieldDestinationAddress holds the string denoting the destination_address field in the database.
	FieldDestinationAddress = "destination_address"
	// FieldDestinationLocationPoint holds the string denoting the destination_location_point field in the database.
	FieldDestinationLocationPoint = "destination_location_point"
	// FieldPriceAmount holds the string denoting the price_amount field in the database.
	FieldPriceAmount = "price_amount"
	// FieldPriceCurrency holds the string denoting the price_currency field in the database.
	FieldPriceCurrency = "price_currency"
	// FieldAvailableSeats holds the string denoting the available_seats field in the database.
	FieldAvailableSeats = "available_seats"
	// FieldTotalSeats holds the string denoting the total_seats field in the database.
	FieldTotalSeats = "total_seats"
	// FieldAmenities holds the string denoting the amenities field in the database.
	FieldAmenities = "amenities"
	// FieldStops holds the string denoting the stops field in the database.
	FieldStops = "stops"
	// FieldInstantConfirmation holds the string denoting the instant_confirmation field in the database.
	FieldInstantConfirmation = "instant_confirmation"
	// FieldCancellationPolicy holds the string denoting the cancellation_policy field in the database.
	FieldCancellationPolicy = "cancellation_policy"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDriver holds the string denoting the driver edge name in mutations.
	EdgeDriver = "driver"
	// EdgeVehicle holds the string denoting the vehicle edge name in mutations.
	EdgeVehicle = "vehicle"
	// EdgeBookings holds the string denoting the bookings edge name in mutations.
	EdgeBookings = "bookings"
	// Table holds the table name of the ride in the database.
	Table = "rides"
	// DriverTable is the table that holds the driver relation/edge.
	DriverTable = "rides"
	// DriverInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DriverInverseTable = "users"
	// DriverColumn is the table column denoting the driver relation/edge.
	DriverColumn = "driver_id"
	// VehicleTable is the table that holds the vehicle relation/edge.
	VehicleTable = "rides"
	// VehicleInverseTable is the table name for the Vehicle entity.
	// It exists in this package in order to avoid circular dependency with the "vehicle" package.
	VehicleInverseTable = "vehicles"
	// VehicleColumn is the table column denoting the vehicle relation/edge.
	VehicleColumn = "vehicle_id"
	// BookingsTable is the table that holds the bookings relation/edge.
	BookingsTable = "bookings"
	// BookingsInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookingsInverseTable = "bookings"
	// BookingsColumn is the table column denoting the bookings relation/edge.
	BookingsColumn = "ride_id"
)

// Columns holds all SQL columns for ride fields.
var Columns = []string{
	FieldID,
	FieldDriverID,
	FieldVehicleID,
	FieldType,
	FieldRideType,
	FieldRecurrence,
	FieldDepartureTime,
	FieldArrivalTime,
	FieldDurationMinutes,
	FieldOriginCity,
	FieldOriginAddress,
	FieldOriginLocationPoint,
	FieldDestinationCity,
	FieldDestinationAddress,
	FieldDestinationLocationPoint,
	FieldPriceAmount,
	FieldPriceCurrency,
	FieldAvailableSeats,
	FieldTotalSeats,
	FieldAmenities,
	FieldStops,
	FieldInstantConfirmation,
	FieldCancellationPolicy,
	FieldDescription,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DriverIDValidator is a validator for the "driver_id" field. It is called by the builders before save.
	DriverIDValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultRideType holds the default value on creation for the "ride_type" field.
	DefaultRideType string
	// DurationMinutesValidator is a validator for the "duration_minutes" field. It is called by the builders before save.
	DurationMinutesValidator func(int) error
	// OriginCityValidator is a validator for the "origin_city" field. It is called by the builders before save.
	OriginCityValidator func(string) error
	// OriginAddressValidator is a validator for the "origin_address" field. It is called by the builders before save.
	OriginAddressValidator func(string) error
	// DestinationCityValidator is a validator for the "destination_city" field. It is called by the builders before save.
	DestinationCityValidator func(string) error
	// DestinationAddressValidator is a validator for the "destination_address" field. It is called by the builders before save.
	DestinationAddressValidator func(string) error
	// PriceAmountValidator is a validator for the "price_amount" field. It is called by the builders before save.
	PriceAmountValidator func(int64) error
	// DefaultPriceCurrency holds the default value on creation for the "price_currency" field.
	DefaultPriceCurrency string
	// AvailableSeatsValidator is a validator for the "available_seats" field. It is called by the builders before save.
	AvailableSeatsValidator func(int) error
	// TotalSeatsValidator is a validator for the "total_seats" field. It is called by the builders before save.
	TotalSeatsValidator func(int) error
	// DefaultInstantConfirmation holds the default value on creation for the "instant_confirmation" field.
	DefaultInstantConfirmation bool
	// DefaultCancellationPolicy holds the default value on creation for the "cancellation_policy" field.
	DefaultCancellationPolicy string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Ride queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDriverID orders the results by the driver_id field.
func ByDriverID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriverID, opts...).ToFunc()
}

// ByVehicleID orders the results by the vehicle_id field.
func ByVehicleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVehicleID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByRideType orders the results by the ride_type field.
func ByRideType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRideType, opts...).ToFunc()
}

// ByDepartureTime orders the results by the departure_time field.
func ByDepartureTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartureTime, opts...).ToFunc()
}

// ByArrivalTime orders the results by the arrival_time field.
func ByArrivalTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArrivalTime, opts...).ToFunc()
}

// ByDurationMinutes orders the results by the duration_minutes field.
func ByDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMinutes, opts...).ToFunc()
}

// ByOriginCity orders the results by the origin_city field.
func ByOriginCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginCity, opts...).ToFunc()
}

// ByOriginAddress orders the results by the origin_address field.
func ByOriginAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginAddress, opts...).ToFunc()
}

// ByOriginLocationPoint orders the results by the origin_location_point field.
func ByOriginLocationPoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginLocationPoint, opts...).ToFunc()
}

// ByDestinationCity orders the results by the destination_city field.
func ByDestinationCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinationCity, opts...).ToFunc()
}

// ByDestinationAddress orders the results by the destination_address field.
func ByDestinationAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinationAddress, opts...).ToFunc()
}

// ByDestinationLocationPoint orders the results by the destination_location_point field.
func ByDestinationLocationPoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestinationLocationPoint, opts...).ToFunc()
}

// ByPriceAmount orders the results by the price_amount field.
func ByPriceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceAmount, opts...).ToFunc()
}

// ByPriceCurrency orders the results by the price_currency field.
func ByPriceCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceCurrency, opts...).ToFunc()
}

// ByAvailableSeats orders the results by the available_seats field.
func ByAvailableSeats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableSeats, opts...).ToFunc()
}

// ByTotalSeats orders the results by the total_seats field.
func ByTotalSeats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalSeats, opts...).ToFunc()
}

// ByInstantConfirmation orders the results by the instant_confirmation field.
func ByInstantConfirmation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstantConfirmation, opts...).ToFunc()
}

// ByCancellationPolicy orders the results by the cancellation_policy field.
func ByCancellationPolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancellationPolicy, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDriverField orders the results by driver field.
func ByDriverField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDriverStep(), sql.OrderByField(field, opts...))
	}
}

// ByVehicleField orders the results by vehicle field.
func ByVehicleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVehicleStep(), sql.OrderByField(field, opts...))
	}
}

// ByBookingsCount orders the results by bookings count.
func ByBookingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBookingsStep(), opts...)
	}
}

// ByBookings orders the results by bookings terms.
func ByBookings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBookingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDriverStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DriverInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DriverTable, DriverColumn),
	)
}
func newVehicleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VehicleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VehicleTable, VehicleColumn),
	)
}
func newBookingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BookingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BookingsTable, BookingsColumn),
	)
}
