// Code generated by ent, DO NOT EDIT.

package ride

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/slowtyper/poolie/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldID, id))
}

// DriverID applies equality check predicate on the "driver_id" field. It's identical to DriverIDEQ.
func DriverID(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDriverID, v))
}

// VehicleID applies equality check predicate on the "vehicle_id" field. It's identical to VehicleIDEQ.
func VehicleID(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldVehicleID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldType, v))
}

// RideType applies equality check predicate on the "ride_type" field. It's identical to RideTypeEQ.
func RideType(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldRideType, v))
}

// DepartureTime applies equality check predicate on the "departure_time" field. It's identical to DepartureTimeEQ.
func DepartureTime(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDepartureTime, v))
}

// ArrivalTime applies equality check predicate on the "arrival_time" field. It's identical to ArrivalTimeEQ.
func ArrivalTime(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldArrivalTime, v))
}

// DurationMinutes applies equality check predicate on the "duration_minutes" field. It's identical to DurationMinutesEQ.
func DurationMinutes(v int) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDurationMinutes, v))
}

// OriginCity applies equality check predicate on the "origin_city" field. It's identical to OriginCityEQ.
func OriginCity(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldOriginCity, v))
}

// OriginAddress applies equality check predicate on the "origin_address" field. It's identical to OriginAddressEQ.
func OriginAddress(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldOriginAddress, v))
}

// OriginLocationPoint applies equality check predicate on the "origin_location_point" field. It's identical to OriginLocationPointEQ.
func OriginLocationPoint(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldOriginLocationPoint, v))
}

// DestinationCity applies equality check predicate on the "destination_city" field. It's identical to DestinationCityEQ.
func DestinationCity(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDestinationCity, v))
}

// DestinationAddress applies equality check predicate on the "destination_address" field. It's identical to DestinationAddressEQ.
func DestinationAddress(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDestinationAddress, v))
}

// DestinationLocationPoint applies equality check predicate on the "destination_location_point" field. It's identical to DestinationLocationPointEQ.
func DestinationLocationPoint(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDestinationLocationPoint, v))
}

// PriceAmount applies equality check predicate on the "price_amount" field. It's identical to PriceAmountEQ.
func PriceAmount(v int64) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldPriceAmount, v))
}

// PriceCurrency applies equality check predicate on the "price_currency" field. It's identical to PriceCurrencyEQ.
func PriceCurrency(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldPriceCurrency, v))
}

// AvailableSeats applies equality check predicate on the "available_seats" field. It's identical to AvailableSeatsEQ.
func AvailableSeats(v int) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldAvailableSeats, v))
}

// TotalSeats applies equality check predicate on the "total_seats" field. It's identical to TotalSeatsEQ.
func TotalSeats(v int) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldTotalSeats, v))
}

// InstantConfirmation applies equality check predicate on the "instant_confirmation" field. It's identical to InstantConfirmationEQ.
func InstantConfirmation(v bool) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldInstantConfirmation, v))
}

// CancellationPolicy applies equality check predicate on the "cancellation_policy" field. It's identical to CancellationPolicyEQ.
func CancellationPolicy(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldCancellationPolicy, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldUpdatedAt, v))
}

// DriverIDEQ applies the EQ predicate on the "driver_id" field.
func DriverIDEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDriverID, v))
}

// DriverIDNEQ applies the NEQ predicate on the "driver_id" field.
func DriverIDNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldDriverID, v))
}

// DriverIDIn applies the In predicate on the "driver_id" field.
func DriverIDIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldDriverID, vs...))
}

// DriverIDNotIn applies the NotIn predicate on the "driver_id" field.
func DriverIDNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldDriverID, vs...))
}

// DriverIDGT applies the GT predicate on the "driver_id" field.
func DriverIDGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldDriverID, v))
}

// DriverIDGTE applies the GTE predicate on the "driver_id" field.
func DriverIDGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldDriverID, v))
}

// DriverIDLT applies the LT predicate on the "driver_id" field.
func DriverIDLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldDriverID, v))
}

// DriverIDLTE applies the LTE predicate on the "driver_id" field.
func DriverIDLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldDriverID, v))
}

// DriverIDContains applies the Contains predicate on the "driver_id" field.
func DriverIDContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldDriverID, v))
}

// DriverIDHasPrefix applies the HasPrefix predicate on the "driver_id" field.
func DriverIDHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldDriverID, v))
}

// DriverIDHasSuffix applies the HasSuffix predicate on the "driver_id" field.
func DriverIDHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldDriverID, v))
}

// DriverIDEqualFold applies the EqualFold predicate on the "driver_id" field.
func DriverIDEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldDriverID, v))
}

// DriverIDContainsFold applies the ContainsFold predicate on the "driver_id" field.
func DriverIDContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldDriverID, v))
}

// VehicleIDEQ applies the EQ predicate on the "vehicle_id" field.
func VehicleIDEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldVehicleID, v))
}

// VehicleIDNEQ applies the NEQ predicate on the "vehicle_id" field.
func VehicleIDNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldVehicleID, v))
}

// VehicleIDIn applies the In predicate on the "vehicle_id" field.
func VehicleIDIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldVehicleID, vs...))
}

// VehicleIDNotIn applies the NotIn predicate on the "vehicle_id" field.
func VehicleIDNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldVehicleID, vs...))
}

// VehicleIDGT applies the GT predicate on the "vehicle_id" field.
func VehicleIDGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldVehicleID, v))
}

// VehicleIDGTE applies the GTE predicate on the "vehicle_id" field.
func VehicleIDGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldVehicleID, v))
}

// VehicleIDLT applies the LT predicate on the "vehicle_id" field.
func VehicleIDLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldVehicleID, v))
}

// VehicleIDLTE applies the LTE predicate on the "vehicle_id" field.
func VehicleIDLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldVehicleID, v))
}

// VehicleIDContains applies the Contains predicate on the "vehicle_id" field.
func VehicleIDContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldVehicleID, v))
}

// VehicleIDHasPrefix applies the HasPrefix predicate on the "vehicle_id" field.
func VehicleIDHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldVehicleID, v))
}

// VehicleIDHasSuffix applies the HasSuffix predicate on the "vehicle_id" field.
func VehicleIDHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldVehicleID, v))
}

// VehicleIDIsNil applies the IsNil predicate on the "vehicle_id" field.
func VehicleIDIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldVehicleID))
}

// VehicleIDNotNil applies the NotNil predicate on the "vehicle_id" field.
func VehicleIDNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldVehicleID))
}

// VehicleIDEqualFold applies the EqualFold predicate on the "vehicle_id" field.
func VehicleIDEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldVehicleID, v))
}

// VehicleIDContainsFold applies the ContainsFold predicate on the "vehicle_id" field.
func VehicleIDContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldVehicleID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldType, v))
}

// RideTypeEQ applies the EQ predicate on the "ride_type" field.
func RideTypeEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldRideType, v))
}

// RideTypeNEQ applies the NEQ predicate on the "ride_type" field.
func RideTypeNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldRideType, v))
}

// RideTypeIn applies the In predicate on the "ride_type" field.
func RideTypeIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldRideType, vs...))
}

// RideTypeNotIn applies the NotIn predicate on the "ride_type" field.
func RideTypeNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldRideType, vs...))
}

// RideTypeGT applies the GT predicate on the "ride_type" field.
func RideTypeGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldRideType, v))
}

// RideTypeGTE applies the GTE predicate on the "ride_type" field.
func RideTypeGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldRideType, v))
}

// RideTypeLT applies the LT predicate on the "ride_type" field.
func RideTypeLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldRideType, v))
}

// RideTypeLTE applies the LTE predicate on the "ride_type" field.
func RideTypeLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldRideType, v))
}

// RideTypeContains applies the Contains predicate on the "ride_type" field.
func RideTypeContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldRideType, v))
}

// RideTypeHasPrefix applies the HasPrefix predicate on the "ride_type" field.
func RideTypeHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldRideType, v))
}

// RideTypeHasSuffix applies the HasSuffix predicate on the "ride_type" field.
func RideTypeHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldRideType, v))
}

// RideTypeEqualFold applies the EqualFold predicate on the "ride_type" field.
func RideTypeEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldRideType, v))
}

// RideTypeContainsFold applies the ContainsFold predicate on the "ride_type" field.
func RideTypeContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldRideType, v))
}

// RecurrenceIsNil applies the IsNil predicate on the "recurrence" field.
func RecurrenceIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldRecurrence))
}

// RecurrenceNotNil applies the NotNil predicate on the "recurrence" field.
func RecurrenceNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldRecurrence))
}

// DepartureTimeEQ applies the EQ predicate on the "departure_time" field.
func DepartureTimeEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDepartureTime, v))
}

// DepartureTimeNEQ applies the NEQ predicate on the "departure_time" field.
func DepartureTimeNEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldDepartureTime, v))
}

// DepartureTimeIn applies the In predicate on the "departure_time" field.
func DepartureTimeIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldDepartureTime, vs...))
}

// DepartureTimeNotIn applies the NotIn predicate on the "departure_time" field.
func DepartureTimeNotIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldDepartureTime, vs...))
}

// DepartureTimeGT applies the GT predicate on the "departure_time" field.
func DepartureTimeGT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldDepartureTime, v))
}

// DepartureTimeGTE applies the GTE predicate on the "departure_time" field.
func DepartureTimeGTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldDepartureTime, v))
}

// DepartureTimeLT applies the LT predicate on the "departure_time" field.
func DepartureTimeLT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldDepartureTime, v))
}

// DepartureTimeLTE applies the LTE predicate on the "departure_time" field.
func DepartureTimeLTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldDepartureTime, v))
}

// ArrivalTimeEQ applies the EQ predicate on the "arrival_time" field.
func ArrivalTimeEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldArrivalTime, v))
}

// ArrivalTimeNEQ applies the NEQ predicate on the "arrival_time" field.
func ArrivalTimeNEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldArrivalTime, v))
}

// ArrivalTimeIn applies the In predicate on the "arrival_time" field.
func ArrivalTimeIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldArrivalTime, vs...))
}

// ArrivalTimeNotIn applies the NotIn predicate on the "arrival_time" field.
func ArrivalTimeNotIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldArrivalTime, vs...))
}

// ArrivalTimeGT applies the GT predicate on the "arrival_time" field.
func ArrivalTimeGT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldArrivalTime, v))
}

// ArrivalTimeGTE applies the GTE predicate on the "arrival_time" field.
func ArrivalTimeGTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldArrivalTime, v))
}

// ArrivalTimeLT applies the LT predicate on the "arrival_time" field.
func ArrivalTimeLT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldArrivalTime, v))
}

// ArrivalTimeLTE applies the LTE predicate on the "arrival_time" field.
func ArrivalTimeLTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldArrivalTime, v))
}

// ArrivalTimeIsNil applies the IsNil predicate on the "arrival_time" field.
func ArrivalTimeIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldArrivalTime))
}

// ArrivalTimeNotNil applies the NotNil predicate on the "arrival_time" field.
func ArrivalTimeNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldArrivalTime))
}

// DurationMinutesEQ applies the EQ predicate on the "duration_minutes" field.
func DurationMinutesEQ(v int) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDurationMinutes, v))
}

// DurationMinutesNEQ applies the NEQ predicate on the "duration_minutes" field.
func DurationMinutesNEQ(v int) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldDurationMinutes, v))
}

// DurationMinutesIn applies the In predicate on the "duration_minutes" field.
func DurationMinutesIn(vs ...int) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldDurationMinutes, vs...))
}

// DurationMinutesNotIn applies the NotIn predicate on the "duration_minutes" field.
func DurationMinutesNotIn(vs ...int) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldDurationMinutes, vs...))
}

// DurationMinutesGT applies the GT predicate on the "duration_minutes" field.
func DurationMinutesGT(v int) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldDurationMinutes, v))
}

// DurationMinutesGTE applies the GTE predicate on the "duration_minutes" field.
func DurationMinutesGTE(v int) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldDurationMinutes, v))
}

// DurationMinutesLT applies the LT predicate on the "duration_minutes" field.
func DurationMinutesLT(v int) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldDurationMinutes, v))
}

// DurationMinutesLTE applies the LTE predicate on the "duration_minutes" field.
func DurationMinutesLTE(v int) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldDurationMinutes, v))
}

// DurationMinutesIsNil applies the IsNil predicate on the "duration_minutes" field.
func DurationMinutesIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldDurationMinutes))
}

// DurationMinutesNotNil applies the NotNil predicate on the "duration_minutes" field.
func DurationMinutesNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldDurationMinutes))
}

// OriginCityEQ applies the EQ predicate on the "origin_city" field.
func OriginCityEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldOriginCity, v))
}

// OriginCityNEQ applies the NEQ predicate on the "origin_city" field.
func OriginCityNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldOriginCity, v))
}

// OriginCityIn applies the In predicate on the "origin_city" field.
func OriginCityIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldOriginCity, vs...))
}

// OriginCityNotIn applies the NotIn predicate on the "origin_city" field.
func OriginCityNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldOriginCity, vs...))
}

// OriginCityGT applies the GT predicate on the "origin_city" field.
func OriginCityGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldOriginCity, v))
}

// OriginCityGTE applies the GTE predicate on the "origin_city" field.
func OriginCityGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldOriginCity, v))
}

// OriginCityLT applies the LT predicate on the "origin_city" field.
func OriginCityLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldOriginCity, v))
}

// OriginCityLTE applies the LTE predicate on the "origin_city" field.
func OriginCityLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldOriginCity, v))
}

// OriginCityContains applies the Contains predicate on the "origin_city" field.
func OriginCityContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldOriginCity, v))
}

// OriginCityHasPrefix applies the HasPrefix predicate on the "origin_city" field.
func OriginCityHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldOriginCity, v))
}

// OriginCityHasSuffix applies the HasSuffix predicate on the "origin_city" field.
func OriginCityHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldOriginCity, v))
}

// OriginCityEqualFold applies the EqualFold predicate on the "origin_city" field.
func OriginCityEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldOriginCity, v))
}

// OriginCityContainsFold applies the ContainsFold predicate on the "origin_city" field.
func OriginCityContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldOriginCity, v))
}

// OriginAddressEQ applies the EQ predicate on the "origin_address" field.
func OriginAddressEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldOriginAddress, v))
}

// OriginAddressNEQ applies the NEQ predicate on the "origin_address" field.
func OriginAddressNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldOriginAddress, v))
}

// OriginAddressIn applies the In predicate on the "origin_address" field.
func OriginAddressIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldOriginAddress, vs...))
}

// OriginAddressNotIn applies the NotIn predicate on the "origin_address" field.
func OriginAddressNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldOriginAddress, vs...))
}

// OriginAddressGT applies the GT predicate on the "origin_address" field.
func OriginAddressGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldOriginAddress, v))
}

// OriginAddressGTE applies the GTE predicate on the "origin_address" field.
func OriginAddressGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldOriginAddress, v))
}

// OriginAddressLT applies the LT predicate on the "origin_address" field.
func OriginAddressLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldOriginAddress, v))
}

// OriginAddressLTE applies the LTE predicate on the "origin_address" field.
func OriginAddressLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldOriginAddress, v))
}

// OriginAddressContains applies the Contains predicate on the "origin_address" field.
func OriginAddressContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldOriginAddress, v))
}

// OriginAddressHasPrefix applies the HasPrefix predicate on the "origin_address" field.
func OriginAddressHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldOriginAddress, v))
}

// OriginAddressHasSuffix applies the HasSuffix predicate on the "origin_address" field.
func OriginAddressHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldOriginAddress, v))
}

// OriginAddressEqualFold applies the EqualFold predicate on the "origin_address" field.
func OriginAddressEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldOriginAddress, v))
}

// OriginAddressContainsFold applies the ContainsFold predicate on the "origin_address" field.
func OriginAddressContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldOriginAddress, v))
}

// OriginLocationPointEQ applies the EQ predicate on the "origin_location_point" field.
func OriginLocationPointEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldOriginLocationPoint, v))
}

// OriginLocationPointNEQ applies the NEQ predicate on the "origin_location_point" field.
func OriginLocationPointNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldOriginLocationPoint, v))
}

// OriginLocationPointIn applies the In predicate on the "origin_location_point" field.
func OriginLocationPointIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldOriginLocationPoint, vs...))
}

// OriginLocationPointNotIn applies the NotIn predicate on the "origin_location_point" field.
func OriginLocationPointNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldOriginLocationPoint, vs...))
}

// OriginLocationPointGT applies the GT predicate on the "origin_location_point" field.
func OriginLocationPointGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldOriginLocationPoint, v))
}

// OriginLocationPointGTE applies the GTE predicate on the "origin_location_point" field.
func OriginLocationPointGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldOriginLocationPoint, v))
}

// OriginLocationPointLT applies the LT predicate on the "origin_location_point" field.
func OriginLocationPointLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldOriginLocationPoint, v))
}

// OriginLocationPointLTE applies the LTE predicate on the "origin_location_point" field.
func OriginLocationPointLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldOriginLocationPoint, v))
}

// OriginLocationPointContains applies the Contains predicate on the "origin_location_point" field.
func OriginLocationPointContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldOriginLocationPoint, v))
}

// OriginLocationPointHasPrefix applies the HasPrefix predicate on the "origin_location_point" field.
func OriginLocationPointHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldOriginLocationPoint, v))
}

// OriginLocationPointHasSuffix applies the HasSuffix predicate on the "origin_location_point" field.
func OriginLocationPointHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldOriginLocationPoint, v))
}

// OriginLocationPointIsNil applies the IsNil predicate on the "origin_location_point" field.
func OriginLocationPointIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldOriginLocationPoint))
}

// OriginLocationPointNotNil applies the NotNil predicate on the "origin_location_point" field.
func OriginLocationPointNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldOriginLocationPoint))
}

// OriginLocationPointEqualFold applies the EqualFold predicate on the "origin_location_point" field.
func OriginLocationPointEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldOriginLocationPoint, v))
}

// OriginLocationPointContainsFold applies the ContainsFold predicate on the "origin_location_point" field.
func OriginLocationPointContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldOriginLocationPoint, v))
}

// DestinationCityEQ applies the EQ predicate on the "destination_city" field.
func DestinationCityEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDestinationCity, v))
}

// DestinationCityNEQ applies the NEQ predicate on the "destination_city" field.
func DestinationCityNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldDestinationCity, v))
}

// DestinationCityIn applies the In predicate on the "destination_city" field.
func DestinationCityIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldDestinationCity, vs...))
}

// DestinationCityNotIn applies the NotIn predicate on the "destination_city" field.
func DestinationCityNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldDestinationCity, vs...))
}

// DestinationCityGT applies the GT predicate on the "destination_city" field.
func DestinationCityGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldDestinationCity, v))
}

// DestinationCityGTE applies the GTE predicate on the "destination_city" field.
func DestinationCityGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldDestinationCity, v))
}

// DestinationCityLT applies the LT predicate on the "destination_city" field.
func DestinationCityLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldDestinationCity, v))
}

// DestinationCityLTE applies the LTE predicate on the "destination_city" field.
func DestinationCityLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldDestinationCity, v))
}

// DestinationCityContains applies the Contains predicate on the "destination_city" field.
func DestinationCityContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldDestinationCity, v))
}

// DestinationCityHasPrefix applies the HasPrefix predicate on the "destination_city" field.
func DestinationCityHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldDestinationCity, v))
}

// DestinationCityHasSuffix applies the HasSuffix predicate on the "destination_city" field.
func DestinationCityHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldDestinationCity, v))
}

// DestinationCityEqualFold applies the EqualFold predicate on the "destination_city" field.
func DestinationCityEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldDestinationCity, v))
}

// DestinationCityContainsFold applies the ContainsFold predicate on the "destination_city" field.
func DestinationCityContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldDestinationCity, v))
}

// DestinationAddressEQ applies the EQ predicate on the "destination_address" field.
func DestinationAddressEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDestinationAddress, v))
}

// DestinationAddressNEQ applies the NEQ predicate on the "destination_address" field.
func DestinationAddressNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldDestinationAddress, v))
}

// DestinationAddressIn applies the In predicate on the "destination_address" field.
func DestinationAddressIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldDestinationAddress, vs...))
}

// DestinationAddressNotIn applies the NotIn predicate on the "destination_address" field.
func DestinationAddressNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldDestinationAddress, vs...))
}

// DestinationAddressGT applies the GT predicate on the "destination_address" field.
func DestinationAddressGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldDestinationAddress, v))
}

// DestinationAddressGTE applies the GTE predicate on the "destination_address" field.
func DestinationAddressGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldDestinationAddress, v))
}

// DestinationAddressLT applies the LT predicate on the "destination_address" field.
func DestinationAddressLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldDestinationAddress, v))
}

// DestinationAddressLTE applies the LTE predicate on the "destination_address" field.
func DestinationAddressLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldDestinationAddress, v))
}

// DestinationAddressContains applies the Contains predicate on the "destination_address" field.
func DestinationAddressContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldDestinationAddress, v))
}

// DestinationAddressHasPrefix applies the HasPrefix predicate on the "destination_address" field.
func DestinationAddressHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldDestinationAddress, v))
}

// DestinationAddressHasSuffix applies the HasSuffix predicate on the "destination_address" field.
func DestinationAddressHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldDestinationAddress, v))
}

// DestinationAddressEqualFold applies the EqualFold predicate on the "destination_address" field.
func DestinationAddressEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldDestinationAddress, v))
}

// DestinationAddressContainsFold applies the ContainsFold predicate on the "destination_address" field.
func DestinationAddressContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldDestinationAddress, v))
}

// DestinationLocationPointEQ applies the EQ predicate on the "destination_location_point" field.
func DestinationLocationPointEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointNEQ applies the NEQ predicate on the "destination_location_point" field.
func DestinationLocationPointNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointIn applies the In predicate on the "destination_location_point" field.
func DestinationLocationPointIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldDestinationLocationPoint, vs...))
}

// DestinationLocationPointNotIn applies the NotIn predicate on the "destination_location_point" field.
func DestinationLocationPointNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldDestinationLocationPoint, vs...))
}

// DestinationLocationPointGT applies the GT predicate on the "destination_location_point" field.
func DestinationLocationPointGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointGTE applies the GTE predicate on the "destination_location_point" field.
func DestinationLocationPointGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointLT applies the LT predicate on the "destination_location_point" field.
func DestinationLocationPointLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointLTE applies the LTE predicate on the "destination_location_point" field.
func DestinationLocationPointLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointContains applies the Contains predicate on the "destination_location_point" field.
func DestinationLocationPointContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointHasPrefix applies the HasPrefix predicate on the "destination_location_point" field.
func DestinationLocationPointHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointHasSuffix applies the HasSuffix predicate on the "destination_location_point" field.
func DestinationLocationPointHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointIsNil applies the IsNil predicate on the "destination_location_point" field.
func DestinationLocationPointIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldDestinationLocationPoint))
}

// DestinationLocationPointNotNil applies the NotNil predicate on the "destination_location_point" field.
func DestinationLocationPointNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldDestinationLocationPoint))
}

// DestinationLocationPointEqualFold applies the EqualFold predicate on the "destination_location_point" field.
func DestinationLocationPointEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldDestinationLocationPoint, v))
}

// DestinationLocationPointContainsFold applies the ContainsFold predicate on the "destination_location_point" field.
func DestinationLocationPointContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldDestinationLocationPoint, v))
}

// PriceAmountEQ applies the EQ predicate on the "price_amount" field.
func PriceAmountEQ(v int64) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldPriceAmount, v))
}

// PriceAmountNEQ applies the NEQ predicate on the "price_amount" field.
func PriceAmountNEQ(v int64) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldPriceAmount, v))
}

// PriceAmountIn applies the In predicate on the "price_amount" field.
func PriceAmountIn(vs ...int64) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldPriceAmount, vs...))
}

// PriceAmountNotIn applies the NotIn predicate on the "price_amount" field.
func PriceAmountNotIn(vs ...int64) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldPriceAmount, vs...))
}

// PriceAmountGT applies the GT predicate on the "price_amount" field.
func PriceAmountGT(v int64) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldPriceAmount, v))
}

// PriceAmountGTE applies the GTE predicate on the "price_amount" field.
func PriceAmountGTE(v int64) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldPriceAmount, v))
}

// PriceAmountLT applies the LT predicate on the "price_amount" field.
func PriceAmountLT(v int64) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldPriceAmount, v))
}

// PriceAmountLTE applies the LTE predicate on the "price_amount" field.
func PriceAmountLTE(v int64) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldPriceAmount, v))
}

// PriceCurrencyEQ applies the EQ predicate on the "price_currency" field.
func PriceCurrencyEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldPriceCurrency, v))
}

// PriceCurrencyNEQ applies the NEQ predicate on the "price_currency" field.
func PriceCurrencyNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldPriceCurrency, v))
}

// PriceCurrencyIn applies the In predicate on the "price_currency" field.
func PriceCurrencyIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldPriceCurrency, vs...))
}

// PriceCurrencyNotIn applies the NotIn predicate on the "price_currency" field.
func PriceCurrencyNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldPriceCurrency, vs...))
}

// PriceCurrencyGT applies the GT predicate on the "price_currency" field.
func PriceCurrencyGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldPriceCurrency, v))
}

// PriceCurrencyGTE applies the GTE predicate on the "price_currency" field.
func PriceCurrencyGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldPriceCurrency, v))
}

// PriceCurrencyLT applies the LT predicate on the "price_currency" field.
func PriceCurrencyLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldPriceCurrency, v))
}

// PriceCurrencyLTE applies the LTE predicate on the "price_currency" field.
func PriceCurrencyLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldPriceCurrency, v))
}

// PriceCurrencyContains applies the Contains predicate on the "price_currency" field.
func PriceCurrencyContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldPriceCurrency, v))
}

// PriceCurrencyHasPrefix applies the HasPrefix predicate on the "price_currency" field.
func PriceCurrencyHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldPriceCurrency, v))
}

// PriceCurrencyHasSuffix applies the HasSuffix predicate on the "price_currency" field.
func PriceCurrencyHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldPriceCurrency, v))
}

// PriceCurrencyEqualFold applies the EqualFold predicate on the "price_currency" field.
func PriceCurrencyEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldPriceCurrency, v))
}

// PriceCurrencyContainsFold applies the ContainsFold predicate on the "price_currency" field.
func PriceCurrencyContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldPriceCurrency, v))
}

// AvailableSeatsEQ applies the EQ predicate on the "available_seats" field.
func AvailableSeatsEQ(v int) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldAvailableSeats, v))
}

// AvailableSeatsNEQ applies the NEQ predicate on the "available_seats" field.
func AvailableSeatsNEQ(v int) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldAvailableSeats, v))
}

// AvailableSeatsIn applies the In predicate on the "available_seats" field.
func AvailableSeatsIn(vs ...int) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldAvailableSeats, vs...))
}

// AvailableSeatsNotIn applies the NotIn predicate on the "available_seats" field.
func AvailableSeatsNotIn(vs ...int) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldAvailableSeats, vs...))
}

// AvailableSeatsGT applies the GT predicate on the "available_seats" field.
func AvailableSeatsGT(v int) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldAvailableSeats, v))
}

// AvailableSeatsGTE applies the GTE predicate on the "available_seats" field.
func AvailableSeatsGTE(v int) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldAvailableSeats, v))
}

// AvailableSeatsLT applies the LT predicate on the "available_seats" field.
func AvailableSeatsLT(v int) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldAvailableSeats, v))
}

// AvailableSeatsLTE applies the LTE predicate on the "available_seats" field.
func AvailableSeatsLTE(v int) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldAvailableSeats, v))
}

// TotalSeatsEQ applies the EQ predicate on the "total_seats" field.
func TotalSeatsEQ(v int) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldTotalSeats, v))
}

// TotalSeatsNEQ applies the NEQ predicate on the "total_seats" field.
func TotalSeatsNEQ(v int) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldTotalSeats, v))
}

// TotalSeatsIn applies the In predicate on the "total_seats" field.
func TotalSeatsIn(vs ...int) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldTotalSeats, vs...))
}

// TotalSeatsNotIn applies the NotIn predicate on the "total_seats" field.
func TotalSeatsNotIn(vs ...int) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldTotalSeats, vs...))
}

// TotalSeatsGT applies the GT predicate on the "total_seats" field.
func TotalSeatsGT(v int) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldTotalSeats, v))
}

// TotalSeatsGTE applies the GTE predicate on the "total_seats" field.
func TotalSeatsGTE(v int) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldTotalSeats, v))
}

// TotalSeatsLT applies the LT predicate on the "total_seats" field.
func TotalSeatsLT(v int) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldTotalSeats, v))
}

// TotalSeatsLTE applies the LTE predicate on the "total_seats" field.
func TotalSeatsLTE(v int) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldTotalSeats, v))
}

// AmenitiesIsNil applies the IsNil predicate on the "amenities" field.
func AmenitiesIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldAmenities))
}

// AmenitiesNotNil applies the NotNil predicate on the "amenities" field.
func AmenitiesNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldAmenities))
}

// StopsIsNil applies the IsNil predicate on the "stops" field.
func StopsIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldStops))
}

// StopsNotNil applies the NotNil predicate on the "stops" field.
func StopsNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldStops))
}

// InstantConfirmationEQ applies the EQ predicate on the "instant_confirmation" field.
func InstantConfirmationEQ(v bool) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldInstantConfirmation, v))
}

// InstantConfirmationNEQ applies the NEQ predicate on the "instant_confirmation" field.
func InstantConfirmationNEQ(v bool) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldInstantConfirmation, v))
}

// CancellationPolicyEQ applies the EQ predicate on the "cancellation_policy" field.
func CancellationPolicyEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldCancellationPolicy, v))
}

// CancellationPolicyNEQ applies the NEQ predicate on the "cancellation_policy" field.
func CancellationPolicyNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldCancellationPolicy, v))
}

// CancellationPolicyIn applies the In predicate on the "cancellation_policy" field.
func CancellationPolicyIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldCancellationPolicy, vs...))
}

// CancellationPolicyNotIn applies the NotIn predicate on the "cancellation_policy" field.
func CancellationPolicyNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldCancellationPolicy, vs...))
}

// CancellationPolicyGT applies the GT predicate on the "cancellation_policy" field.
func CancellationPolicyGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldCancellationPolicy, v))
}

// CancellationPolicyGTE applies the GTE predicate on the "cancellation_policy" field.
func CancellationPolicyGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldCancellationPolicy, v))
}

// CancellationPolicyLT applies the LT predicate on the "cancellation_policy" field.
func CancellationPolicyLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldCancellationPolicy, v))
}

// CancellationPolicyLTE applies the LTE predicate on the "cancellation_policy" field.
func CancellationPolicyLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldCancellationPolicy, v))
}

// CancellationPolicyContains applies the Contains predicate on the "cancellation_policy" field.
func CancellationPolicyContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldCancellationPolicy, v))
}

// CancellationPolicyHasPrefix applies the HasPrefix predicate on the "cancellation_policy" field.
func CancellationPolicyHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldCancellationPolicy, v))
}

// CancellationPolicyHasSuffix applies the HasSuffix predicate on the "cancellation_policy" field.
func CancellationPolicyHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldCancellationPolicy, v))
}

// CancellationPolicyEqualFold applies the EqualFold predicate on the "cancellation_policy" field.
func CancellationPolicyEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldCancellationPolicy, v))
}

// CancellationPolicyContainsFold applies the ContainsFold predicate on the "cancellation_policy" field.
func CancellationPolicyContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldCancellationPolicy, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Ride {
	return predicate.Ride(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Ride {
	return predicate.Ride(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Ride {
	return predicate.Ride(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Ride {
	return predicate.Ride(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Ride {
	return predicate.Ride(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasDriver applies the HasEdge predicate on the "driver" edge.
func HasDriver() predicate.Ride {
	return predicate.Ride(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DriverTable, DriverColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDriverWith applies the HasEdge predicate on the "driver" edge with a given conditions (other predicates).
func HasDriverWith(preds ...predicate.User) predicate.Ride {
	return predicate.Ride(func(s *sql.Selector) {
		step := newDriverStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVehicle applies the HasEdge predicate on the "vehicle" edge.
func HasVehicle() predicate.Ride {
	return predicate.Ride(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VehicleTable, VehicleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVehicleWith applies the HasEdge predicate on the "vehicle" edge with a given conditions (other predicates).
func HasVehicleWith(preds ...predicate.Vehicle) predicate.Ride {
	return predicate.Ride(func(s *sql.Selector) {
		step := newVehicleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBookings applies the HasEdge predicate on the "bookings" edge.
func HasBookings() predicate.Ride {
	return predicate.Ride(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BookingsTable, BookingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBookingsWith applies the HasEdge predicate on the "bookings" edge with a given conditions (other predicates).
func HasBookingsWith(preds ...predicate.Booking) predicate.Ride {
	return predicate.Ride(func(s *sql.Selector) {
		step := newBookingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ride) predicate.Ride {
	return predicate.Ride(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ride) predicate.Ride {
	return predicate.Ride(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ride) predicate.Ride {
	return predicate.Ride(sql.NotPredicates(p))
}
